### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by PatchworkBoy** [PatchworkBoy/homebridge-eDomoticz#1]
>---
>Loaded config.json with 0 accessories and 1 platforms.
>---
>Loading 1 platforms...
>[eDomoticz] Initializing eDomoticz platform...
>[eDomoticz] Fetching Domoticz lights and switches...
>Loading 0 accessories...
>[eDomoticz] Initializing platform accessory 'Amp'...
>[eDomoticz] Initializing platform accessory 'Amp Background Volume'...
>[eDomoticz] Initializing platform accessory 'Amp Vol Normal'...
>[eDomoticz] Initializing platform accessory 'AppleTV'...
>[eDomoticz] Initializing platform accessory 'Barometer'...
>[eDomoticz] Initializing platform accessory 'CPU_Usage'...
>[eDomoticz] Initializing platform accessory 'HDD /'...
>[eDomoticz] Initializing platform accessory 'HDD /boot'...
>[eDomoticz] Initializing platform accessory 'Helens Light'...
>[eDomoticz] Initializing platform accessory 'Homebridge Temp'...
>[eDomoticz] Initializing platform accessory 'Household Electricity'...
>/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:52
>      this.getCharacteristic(Characteristic.Name) ||
>           ^
>TypeError: undefined is not a function
>    at Function.Service (/usr/local/lib/node_modules/homebridge/node_modules/hap->nodejs/lib/Service.js:52:12)
>    at Function.eDomoticzPlatform.MeterDeviceService (/usr/local/lib/node_modules/homebridge->eDomoticz/index.js:119:10)
>    at Object.eDomoticzAccessory.getServices (/usr/local/lib/node_modules/homebridge->eDomoticz/index.js:364:49)
>    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:235:36)
>    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:221:32)
>    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
>    at callbackLater (/usr/local/lib/node_modules/homebridge-eDomoticz/index.js:132:27)
>    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-eDomoticz/index.js:159:5)
>    at Request.self.callback (/usr/local/lib/node_modules/homebridge->eDomoticz/node_modules/request/request.js:198:22)
>    at Request.emit (events.js:110:17)

There’s something I’m not understanding about custom characteristics and services... when it comes to adding a “General” sensor of SubType “kWh” (i.e.: a General Power Meter Virtual Sensor for CC EnvIR in Domoticz), the above error is thrown.

Code for creating custom characteristics and services was based on [homebridge-yamaha](https://github.com/neonightmare/homebridge-yamaha)

**Comment by nfarina** [comment]
When adding Characteristics, they must be "instances" not "classes" - so for instance this line:

```js
	this.addCharacteristic(eDomoticzPlatform.CurrentConsumption);
```

should look something like:

```js
	this.addCharacteristic(new eDomoticzPlatform.CurrentConsumption());
```

**Comment by PatchworkBoy** [comment]
D00d... I think I love you. Perfect! Cheers!
