### ISSUE TITLE
Owl 113 / Electrisave Current Meter

### ISSUE THREAD

**Issue by jem101** [PatchworkBoy/homebridge-eDomoticz#10]
json output from my Owl electricity monitor in Domoticz as requested on the Domoticz forums

{
   "ActTime" : 1454858626,
   "ServerTime" : "2016-02-07 15:23:46",
   "Sunrise" : "07:29",
   "Sunset" : "16:57",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "529 Watt",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveTimeout" : false,
         "ID" : "6C00",
         "LastUpdate" : "2016-02-07 15:23:00",
         "Name" : "Electricity Consumption",
         "Notifications" : "false",
         "PlanID" : "11",
         "PlanIDs" : [ 11 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 7,
         "SubType" : "CM113, Electrisave",
         "Timers" : "false",
         "Type" : "Current",
         "TypeImg" : "current",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "displaytype" : 1,
         "idx" : "203"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

Many thanks if this could be added as a supported device in the next build.

**Comment by PatchworkBoy** [comment]
Should be fixed by https://github.com/PatchworkBoy/homebridge-eDomoticz/commit/50a20da7e0aa8169a9afcf2e3e915e99f62876ca - update and let me know.

**Comment by PatchworkBoy** [comment]
Confirmed working!
