### ISSUE TITLE
wall socket and button

### ISSUE THREAD

**Issue by theo-69** [PatchworkBoy/homebridge-edomoticz#103]
I use wall sockets via domoticz, they are shows in domoticz as wall socket, however within homebridge they are switches?

Second, i us buttons with three options (klick, double klick, long klick) these type is supported in homKit as well but via this plugin it shows them as not supported?

**Comment by theo-69** [comment]
really nobody...

**Comment by PatchworkBoy** [comment]
1st - this is done within whatever iOS app you’re using. Within Home app and Eve is the ability to edit a switch and define it as a wall socket, fan, media unit, whatever. This is all handled by your HomeKit app of choice not the homebridge-edomoticz plugin.

2nd - not supported by homebridge-edomoticz plugin at this time.

**Comment by theo-69** [comment]
1st thats not true if its a switch you can define it as a lamp or fan but not asa a wall socket or whatever...

**Comment by PatchworkBoy** [comment]
1st - that IS true. I don’t recommend accusing voluntary developers of free software of lying if you want any support from those developers...

![img_1364](https://user-images.githubusercontent.com/3514253/35187712-0b0805f8-fe20-11e7-960d-10934db67568.jpg)
![img_1365](https://user-images.githubusercontent.com/3514253/35187713-0b221100-fe20-11e7-8bb1-b9fba3f6f9f6.jpg)
![img_1366](https://user-images.githubusercontent.com/3514253/35187714-0b409e2c-fe20-11e7-8efe-462e180cd066.jpg)
