### ISSUE TITLE
C vs F For Temperature

### ISSUE THREAD

**Issue by GreenTentacle** [PatchworkBoy/homebridge-edomoticz#106]
If I have Domoticz' `Setup>Settings>Meters/Counters>Temperature Display` set to **Celsius**, then HomeKit translates correctly to **Fahrenheit** for me, and shows it in the home app correctly.

However, if I set the setting in Domoticz to Fahrenheit, HomeKit shows the value as if it was translated from Celsius.

Is there a way to have eDomoticz accept **F** or **C** as the _incoming_ unit type from Domoticz, and then convert to **C** when it sends it to homekit/homebridge (because it seems to expect **C**) ?

Ideally, I'd like to be able to view F temperatures in Domoticz' web interface, but have it send C temperatures in MQTT, JSON, etc.  But I haven't found a way to do that.

Thanks !

**Comment by GreenTentacle** [comment]
So it looks like when the display units are set to Celsius in Domoticz settings, the JSON from `/json.htm?type=devices&rid=<IDX of my temp sensor>` comes through as Celsius, and similarly comes through as Fahrenheit if the display units are set to Fahrenheit.  Maybe domoticz should do that better, perhaps a `TempUnits` element in the JSON or something, but....

There's the "Result/Data" element in the JSON which could probably tell us if the data we're getting is F or C. `"Data" : "72.1 F, 91 %",` is an example I just got.  I **think** the regex `[0-9]+.[0-9]+\s\b([FC])\b,\s[0-9]+.[0-9]?+\s\%` would isolate the C or F.

I'm a bit scared to try to work this into the code and do a PR, but I figured it might be easier for someone more handy ?  The regex only works for something returning both temp and humidity, so I guess it'd have to be more generalized for other types of temperature-reading devices.

I know, us in the states need to get with the rest of the world and switch to Celsius :(

**Comment by GreenTentacle** [comment]
So the answer from gizmocuz is to query /json.htm?type=command&param=getconfig for `TempSign`.  I still think it would be useful for domoticz to send the unit with the actual reading JSON, but I don't think that's going to be changed.  I don't think I'm competent enough as a developer to add this check and global var to edomoticz, but I'll take a look through the code later.

**Comment by GreenTentacle** [comment]
Here's my latest idea.  There's an element in the `settings` json domoticz sends called `tempunit`, which is 0 for C and 1 F (I've found experimentally)

I think eDomoticz's domoticz.js grabs an object called settings with these values.

So if I'm thinking right, a way to do it would be in the `getTemperature` and `getTemperatureAlternative` functions in `domoticz_accessory.js`.

Something like (pseudocode)
  `if domoticz.settings.tempunit=1 (value=helper.convertFtoC(value))`

Assuming I added a quick function to `helper.js` called convertFtoC... something like

```
function convertFtoC(fahrenheit) 
{
  var fTemp = fahrenheit;
  var fToCel = (fTemp - 32) * 5 / 9;
  return fToCel
} 
```

Solid reasoning ?

**Comment by PatchworkBoy** [comment]
As far as I can tell, HomeKit actually expects everything to arrive in celsius and to do the translation in-app on the device.

The Apple-defined specification for temperature devices specifies the incoming temperature should be celsius...

```
Characteristic.CurrentTemperature = function() {
  Characteristic.call(this, 'Current Temperature', '00000011-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    unit: Characteristic.Units.CELSIUS,
    maxValue: 100,
    minValue: 0,
    minStep: 0.1,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.CurrentTemperature, Characteristic);

Characteristic.CurrentTemperature.UUID = '00000011-0000-1000-8000-0026BB765291';
```
(Source: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js - autogenerated from the Apple SDKs)

**Comment by PatchworkBoy** [comment]
Ah righty - sorry - just read over your code and see you’re converting it to C... yes, that should work.

Add: 
`"farenheight":1 `
...to config.json, then change line 449 of edomoticz_accessory.js to:

`value = ((heat) || (therm)) ? Helper.oneDP(Helper.cleanFloat(s.SetPoint)) : (this.platform.config.farenheight ? Helper.oneDP(Helper.cleanFloat(Helper.convertFtoC(s.Temp))) : Helper.oneDP(Helper.cleanFloat(s.Temp)));`

and line 462 to:

`value = this.platform.config.farenheight ? Helper.oneDP(Helper.cleanFloat(Helper.convertFtoC(s.Temp))) : Helper.oneDP(Helper.cleanFloat(s.Temp));`

The knock on effects of this on items such as Thermostat SetPoint devices however is unknown... there may be further places that would need translations, but the above should get you started.
