### ISSUE TITLE
How to configure motion sensors?

### ISSUE THREAD

**Issue by ooii** [PatchworkBoy/homebridge-edomoticz#107]
Hi,

I have Fibaro FGMS-001 devices working great in domoticz. When using this plugin, I have the following behavior:

- If they are configured as on/off switches on domoticz, they work fine in homekit
- If they are configured as Motion sensors on domoticz, they are always off in homekit. homebridge logs show: `Data Received for <device name>`

Since the `readme` file states that motion sensors are supported but also that they are in the todo list, I don't know if I can fix this or not?

Thanks for your help

**Comment by PatchworkBoy** [comment]
Would need Domoticz JSON API output for them when set as Motion sensors in Domoticz to investigate further.

**Comment by ooii** [comment]
Thanks for your response.
Are you referring to that?
```
{
	"ActTime": 1517087560,
	"ServerTime": "2018-01-27 22:12:40",
	"Sunrise": "08:28",
	"Sunset": "17:38",
	"result": [{
		"AddjMulti": 1,
		"AddjMulti2": 1,
		"AddjValue": 0,
		"AddjValue2": 0,
		"BatteryLevel": 100,
		"CustomImage": 0,
		"Data": "Off",
		"Description": "",
		"Favorite": 0,
		"HardwareID": 39,
		"HardwareName": "USB Blanche",
		"HardwareType": "OpenZWave USB",
		"HardwareTypeVal": 21,
		"HaveDimmer": true,
		"HaveGroupCmd": true,
		"HaveTimeout": false,
		"ID": "00001400",
		"Image": "Light",
		"IsSubDevice": false,
		"LastUpdate": "2018-01-27 21:56:19",
		"Level": 0,
		"LevelInt": 0,
		"MaxDimLevel": 100,
		"Name": "PIR Entrée",
		"Notifications": "false",
		"PlanID": "0",
		"PlanIDs": [
			0
		],
		"Protected": false,
		"ShowNotifications": true,
		"SignalLevel": "-",
		"Status": "Off",
		"StrParam1": "",
		"StrParam2": "",
		"SubType": "Switch",
		"SwitchType": "Motion Sensor",
		"SwitchTypeVal": 8,
		"Timers": "false",
		"Type": "Light/Switch",
		"TypeImg": "motion",
		"Unit": 1,
		"Used": 1,
		"UsedByCamera": false,
		"XOffset": "0",
		"YOffset": "0",
		"idx": "760"
	}],
	"status": "OK",
	"title": "Devices"
}
```

**Comment by PatchworkBoy** [comment]
Yup - ta...

**Comment by PatchworkBoy** [comment]
These should be fully supported already (they’re output is the same as mine, which work fine). If they’re not reflecting Domoticz status correctly, have you ensured MQTT is fully functional and configured correctly?
