### ISSUE TITLE
mqtt not used to send messages to domoticz coming from Hue plug-in

### ISSUE THREAD

**Issue by ooii** [PatchworkBoy/homebridge-edomoticz#109]
Hi, a week ago, I added mqtt to my domoticz. Since then, my homekit updates in realtime when something changes on domoticz and, vice versa, when I switch on or off a domoticz switch from my Home app, it reacts instantly. Really appreciated the upgrade brought by mqtt.

However, it seems mqtt is not used when the switch order comes from a Hue Dimmer (via the [Hue Plug-in](https://github.com/ebaauw/homebridge-hue)). In that case, it is still sent the old way, not via mqtt. This leads to slowdowns and sometimes no response at all.

I can't say if this is due to the [Hue Plug-in](https://github.com/ebaauw/homebridge-hue) or the eDomoticz one, I'm then posting this issue on both plug-in repositories.

**Comment by ooii** [comment]
According [to discussion on the hue plug-in issues](https://github.com/ebaauw/homebridge-hue/issues/162), it seems the issue concerns the edomoticz plug-in, since if I set the domoticz switch manually in HomeKit, the plugin **does not** update domoticz over mqtt.

**Comment by ooii** [comment]
Hi @PatchworkBoy, any idea about that?

**Comment by PatchworkBoy** [comment]
Homebridge-eDomoticz was never designed to be (and doesn’t function as) a bridge between other Homebridge plugins and Domoticz itself. Any other plugins need to communicate _directly_ with Domoticz via it’s JSON API, which then triggers relevant MQTT messages to be sent by Domoticz. Homebridge-eDomoticz will then reflect changes when told about them by Domoticz’s own MQTT stream.

**Comment by ooii** [comment]
I did not plan to use it as a bridge between another plug-in and domoticz. I just wanted to use a Hue dimmer to switch on/off, via HomeKit, a Fibaro switch, which is a domoticz device. 
I checked right now and it seems that when the problem does not occur anymore. 
So, you were right to close the issue.
