### ISSUE TITLE
Door and Windows Sensors

### ISSUE THREAD

**Issue by jem101** [PatchworkBoy/homebridge-eDomoticz#11]
I am wondering if it would be at all possible to also include support for Open / Close door and Window sensors. I have two types, one made by LightwaveRF and the other by HomeEasy. The json output results for an example of both is below.

Again many thanks for all your good work.

The Lightwave Version
{
   "ActTime" : 1454859550,
   "ServerTime" : "2016-02-07 15:39:10",
   "Sunrise" : "07:29",
   "Sunset" : "16:57",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "2C25CC",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-02-05 07:09:03",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 32,
         "Name" : "Bathroom Window",
         "Notifications" : "false",
         "PlanID" : "6",
         "PlanIDs" : [ 6, 11 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "LightwaveRF",
         "SwitchType" : "Contact",
         "SwitchTypeVal" : 2,
         "Timers" : "false",
         "Type" : "Lighting 5",
         "TypeImg" : "contact",
         "Unit" : 10,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "41",
         "YOffset" : "638",
         "idx" : "46"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

The HomeEasy version which differs in just the Type and Subtype
{
   "ActTime" : 1454859576,
   "ServerTime" : "2016-02-07 15:39:36",
   "Sunrise" : "07:29",
   "Sunset" : "16:57",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "001488C",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-01-25 08:13:14",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "Ruby's Room Window",
         "Notifications" : "false",
         "PlanID" : "8",
         "PlanIDs" : [ 8, 11 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 5,
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Contact",
         "SwitchTypeVal" : 2,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "contact",
         "Unit" : 10,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "936",
         "YOffset" : "517",
         "idx" : "59"
      }
   ],
   "status" : "OK",
   "title" : "Devices"

**Comment by PatchworkBoy** [comment]
Should be fixed by https://github.com/PatchworkBoy/homebridge-eDomoticz/commit/98f19cebca807dadd726e23fe3edadf5426c5e03 - update, test & confirm!

**Comment by jem101** [comment]
Updated to latest build and although devices appear in 'Home' app in iOS they do not show up properly or contactable in Eve. In Home they are not pulling any status info i.e. Open or Closed from Domoticz and are showing as just blank.

**Comment by PatchworkBoy** [comment]
Parp. I know why now - will resolve tomorrow. I've called a characteristic type that doesn't feature in the version of HAP-NodeJS currently used by HomeBridge.

**Comment by PatchworkBoy** [comment]
OK - think Ive got this sussed - will be pushing an update momentarily.

**Comment by PatchworkBoy** [comment]
Should all be fixed now via v0.1.11 - https://github.com/PatchworkBoy/homebridge-eDomoticz/commit/a782bea1fb38b7e8fd5d5a5085e37366e7f92516

Let me know...!

**Comment by PatchworkBoy** [comment]
Fix confirmed via Domoticz forums
