### ISSUE TITLE
Reset name and room after update

### ISSUE THREAD

**Issue by NewFolk** [PatchworkBoy/homebridge-edomoticz#110]
Hello,
I update Homebridge with
`systemctl stop homebridge && sudo npm update -g homebridge --unsafe-perm && sudo npm update -g homebridge-edomoticz --unsafe-perm && systemctl start homebridge`

After this all my custom names and assign to rooms has been reseted.

Is it ok?
Does this happen only to me?

**Comment by PatchworkBoy** [comment]
Depends entirely on how much has changed between the versions you're going from/to of both homebridge & the plugin.
