### ISSUE TITLE
bme280 problem

### ISSUE THREAD

**Issue by nikki-reprap** [PatchworkBoy/homebridge-edomoticz#111]
I have added my bme280 sensor in domoticz and it is working fine but i am getting this error with homebridge

HAP Warning: Characteristic undefined not in required or optional characteristics for service E863F001-079E-48FF-8F27-9C2605A29F52. Adding anyway.
^ For: Barometer

Its says it is connected to mqtt :  [eDomoticz] Successfully connected to MQTT broker.

In the homekit app I get "Not Supported"

This is my config.json file
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"description": "This is an example configuration file. You can use this as a template for creating your own configuration file.",
	"platforms": [{
		"platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "192.168.2.170",
            "port": "8080",
            "ssl": 0,
            "roomid": 0,
            "mqtt": 1,
            "excludedDevices": []
	}],
	"accessories": [{
		"accessory": "mqtt-switch-tasmota",
		"switchType": "outlet",
		"name": "Desk Lamp",
		"url": "mqtt://192.168.2.170",
		"username": "root",
		"password": "odroid",
		"topics": {
			"statusGet": "stat/Lights/RESULT",
			"statusSet": "cmnd/Lights/POWER",
			"stateGet": "tele/Lights/STATE"
		},
		"onValue": "ON",
		"offValue": "OFF",
		"activityTopic": "tele/Lights/LWT",
		"activityParameter": "Online",
		"startCmd": "cmnd/Lights/TelePeriod",
		"startParameter": "60",
		"manufacturer": "ITEAD",
		"model": "sonoff",
		"serialNumberMAC": "MAC OR SERIAL NUMBER OR EMPTY"
	}]
}

**Comment by PatchworkBoy** [comment]
This is normal behaviour. Barometer isn’t supported natively by HomeKit, so won’t work within Home.app, but regardless of the warning message above, will still work within 3rd party apps such as Elgato Eve.
