### ISSUE TITLE
Blind roller shutter 2 status error

### ISSUE THREAD

**Issue by appellastefano** [PatchworkBoy/homebridge-edomoticz#112]
I need help with blind configuration.
I have domoticz and edomoticz installed on my Raspberry Pi3.

This is my simple config.json

 "bridge": {
 "name": "Homebridge",
 "username": "CC:21:3E:E4:DE:33",
 "port": 51826,
 "pin": "031-45-154"
 },
 "description": "Configuration file for (e)xtended Domoticz platform.",
 "platforms": [
 {
 "platform": "eDomoticz",
 "name": "eDomoticz",
 "server": "192.168.1.20",
 "port": "8080",
 "ssl": 0,
 "roomid": 2,
 "mqtt": 1

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-9-22 22:47:53] Loaded plugin: homebridge-edomoticz
[2017-9-22 22:47:53] Registering platform 'homebridge-edomoticz.eDomoticz'
[2017-9-22 22:47:53] ---
[2017-9-22 22:47:53] Loaded config.json with 0 accessories and 1 platforms.
[2017-9-22 22:47:53] ---
[2017-9-22 22:47:53] Loading 1 platforms...
[2017-9-22 22:47:53] [eDomoticz] Initializing eDomoticz platform...
[2017-9-22 22:47:53] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[2017-9-22 22:47:54] Homebridge is running on port 51826.
[2017-9-22 22:47:54] [eDomoticz] There was an error while getting the MQTT Hardware Device from Domoticz.
Please verify that you have added the MQTT Hardware Device and that the hardware device is enabled.

I have configured 8 swich and 5 rolling shutter and everything
works well  in domoticz and in homekit.

But every time I close and I open homekit app,
open and closed values and percentage dimmer blind are wrong ...

blind closed and homekit signals open 85% ...
blind open and homekit signals closed ...ecc..
without any logic.

It seems that at the opening of homekit
he can not understand the state of the roller shutter.

This only happens if I open and close app homekit
otherwise blind open close and percentage works well.

In addition, this error occurs only for blinds
and not for swiches that are updated correctly at
each opening of homekit app.

This is the api json configuration of the fibaro rolling shutter.

I tried to delete and reinstall hombridge and edomoticz
but always the same mistake.

Hope in your help I'm crazy ...

**Comment by appellastefano** [comment]
This is the api json configuration of the fibaro rolling shutter.

{
   "ActTime" : 1506166488,
   "ServerTime" : "2017-09-23 13:34:48",
   "Sunrise" : "07:20",
   "Sunset" : "19:24",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Set Level: 74 %",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 7,
         "HardwareName" : "Home",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001301",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-09-23 08:03:20",
         "Level" : 74,
         "LevelInt" : 74,
         "MaxDimLevel" : 100,
         "Name" : "Tapparella Soggiorno",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 74 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage Inverted",
         "SwitchTypeVal" : 16,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "73"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by stephvite** [comment]
Same problem for me. I don’t know why

**Comment by appellastefano** [comment]
Help!!!!??

**Comment by fennec622** [comment]
For me FGRM222 fibaro roller shutter
No problem 
% always good value in home APP and domoticz

Just after move blind in Home app result in home app is not immediately i must wait blind arrived at finish position

If blind is close i change to 50%, result blind in home app stay closed until reel position of blind is 50% 
But result is always good 
So perhaps configuration of roller is not good

**Comment by stephvite** [comment]
I dont want to believe that we are so few with this type of problem.

**Comment by Adelysnet** [comment]
Hi, 
Same problem her, I have 8 FGRM222 connected, and in most cases (except when i made changes directly in HomeKit App) the values displayed are wrong. Actually, it says all my blinds are closed but they are all open ( status and position in domoticz are ok).

**Comment by PatchworkBoy** [comment]
Main problem is neither myself or Ramon have any blinds, therefore we're developing blind. Guaranteed fix? Someone loan me a blind, I'll write support for it. That's the only way any progress will be made on this issue, other than a 3rd party writing in support that doesn't break any other types of blinds, and submitting a pull request.

**Comment by stephvite** [comment]
It seems there is a problem with the latest beta domoticz on the management of "blinds percentage" shutters similar to dimmer lights.
when you open or close the percentage stays at the old value

**Comment by PatchworkBoy** [comment]
>  [2017-9-22 22:47:54] [eDomoticz] There was an error while getting the MQTT Hardware Device from Domoticz.
> Please verify that you have added the MQTT Hardware Device and that the hardware device is enabled.

Realtime updates aren’t enabled if you haven’t set MQTT up within Domoticz itself. Please confirm MQTT is enabled both in the plugin AND in domoticz.

**Comment by Freak5M** [comment]
Hi,

I have a similar problem: my 3 Fibaros FGR-222 work perfectly into Domoticz through the web platform. I see them into the Home App and it works fine but they are always showed as "Open" no matter their real position.

@PatchworkBoy What do you mean by enable MQTT in Domoticz, it isn't activated by default ?

Thanks for your advices

**Comment by PatchworkBoy** [comment]
You have to install and configure mosquitto, then add the MQTT client in Domoticz hardware, configured to the 'out' channel, then configure eDomoticz config.json with the broker details. See Domoticz wiki over at Domoticz.com

**Comment by PatchworkBoy** [comment]
Found something that may have been causing an issue to not retrieve the status into the correct characteristic. So, **as well as** ensuring you have MQTT correctly set up and activated so that changes are pushed in realtime from Domoticz to Homebridge, **update to the latest version (2.1.7) via npm**.

`sudo npm update -g homebridge-edomoticz`

Then restart homebridge.

**Comment by stephvite** [comment]
Excellent! It work for me now. But status open/close  still the opposite in domoticz.

**Comment by stephvite** [comment]
Sorry, it’s not work. If i close shutter. Status become closed. But status go to ‘opened’ a few second after

**Comment by Freak5M** [comment]
Thanks a lot,  it works perfectly now ! 👍

**Comment by PatchworkBoy** [comment]
@stephvite post json output for your device and a screenshot of your switch after clicking it's edit button in Domoticz please.

**Comment by PatchworkBoy** [comment]
...and make sure your switch's off delay is set to 0.

**Comment by stephvite** [comment]
Ok this is my json output
[json-shutter.txt](https://github.com/PatchworkBoy/homebridge-edomoticz/files/1692791/json-shutter.txt)

**Comment by stephvite** [comment]
This is my device Screenshot
Option switch's delay not appear.
![shutter maximepng](https://user-images.githubusercontent.com/17260376/35777874-ab7b4d92-09b5-11e8-900a-a3126e5477f9.PNG)

**Comment by bassduh** [comment]
Same problem here, after I closed one of my 3 FGR-222 rollershutters, status on Close is Open and vice versa.

Domoticz's json response shows the following info on Closed:

```
         "Level" : 100,
         "LevelInt" : 100,
         "MaxDimLevel" : 100,
         "Status" : "Closed",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
```

Any idea @PatchworkBoy ?

**Comment by niko44** [comment]
> Same problem here, after I closed one of my 3 FGR-222 rollershutters, status on Close is Open and vice versa.
> 
> Domoticz's json response shows the following info on Closed:
> 
> ```
>          "Level" : 100,
>          "LevelInt" : 100,
>          "MaxDimLevel" : 100,
>          "Status" : "Closed",
>          "SwitchType" : "Blinds Percentage",
>          "SwitchTypeVal" : 13,
> ```
> Any idea @PatchworkBoy ?

Hello

I have the same issue.
When I say "Open shutters" the order is sent and the shutters open. But if I ask for the state, the information is reversed: the shutter is open (as in Domoticz) but the Home app indicates that it is closed and vice versa ...

I already have the latest version of the plugin and I have already tried to reinstall all my Raspberry ...

**Comment by stephvite** [comment]
[https://github.com/OpenZWave/open-zwave/issues/1541](url)
this could be explain our problems with fgrm222.

**Comment by FTBoby** [comment]
Hello,
I have the same problem with roller shutter 2 from Fibaro.

I edit the file ZWCFG _ *. Xml as indicate in another post but this still does not work ... 

https://github.com/OpenZWave/open-zwave/issues/1541

A solution?
Where does the concern come from? Edomoticz? Domoticz? OpenZWave?

Have a good day.

**Comment by niko44** [comment]
I've still have the pb. Nobody can explain it ?

**Comment by jonferreira** [comment]
I've never managed to sort this and for what is worth, similar happens with the new Fibaro Roller Shutter 3 modules!

**Comment by boscorelly** [comment]
@niko44 il faut mettre sur blind inverted et inverser le câblage après.

**Comment by niko44** [comment]
> @niko44 il faut mettre sur blind inverted et inverser le câblage après.

Yeees! Merci beaucoup. Le seul hic (mais bon il en faut toujours un) c'est que si j'appuie sur le volet dans l'application Maison, le volet ne bouge pas et on entend l'ordre d'ouverture et fermeture du relai, il faut que j'appuie 2 fois sur l'icone, bizarre.

en tout cas merci du tuyau :)

**Comment by Electr1fying** [comment]
Hello,

Sorry for reopening this, but are there any updates regarding this problem? 

Domoticz states the correct status and Siri also executes the right commands which i give, but the status is Closed=Open in the Home-App and vice-versa. Not a huge problem, but it would be nice to have the correct statuses. 

Thanks.
