### ISSUE TITLE
Some lights are not working

### ISSUE THREAD

**Issue by marcotini** [PatchworkBoy/homebridge-edomoticz#113]
I don't know why, even restarting Homebridge or Domoticz. Even deleting the folder persist and accesories nothing change (sometimes one light work, sometimes another one not working).

Here some screenshot: https://imgur.com/a/JKihf

**Comment by PatchworkBoy** [comment]
The screenshots tell us nothing. Please post your config.json, and output from json.htm?type=devices

**Comment by marcotini** [comment]
I know that’s sound odd but it’s happen randomly, so if I delete persist folfer and than re-add Homebridge to Home’s app, maybe that light turn avaliable and another are incompatibile.

**Comment by PatchworkBoy** [comment]
> Please post your config.json, and output from json.htm?type=devices

**Comment by marcotini** [comment]
<pre>{
	"bridge": {
        	"name": "Homebridge",
        	"username": "AA:BB:11:22:33:44",
        	"port": 1234,
        	"pin": "123-45-678"
		},

	"description": "This is an example configuration file with one fake accessory and one fake platform.",

	"platforms": [{
		"platform": "eDomoticz",
		"name": "eDomoticz",
		"server": "127.0.0.1",
		"port": "8080",
		"ssl": 0,
            	"roomid": 0,
		"mqtt": {
			"host": "127.0.0.1",
			"port": 1883,
			"topic": "domoticz/out",
			"username": "user",
			"password": "pass"
		}
	}]
}
</pre>

And this is the dummy light that at the moment not work (but it should). The other times was one of the Yeelight and sometimes the Hue white.

<pre>{
   "ActTime" : 1517591502,
   "AstrTwilightEnd" : "19:18",
   "AstrTwilightStart" : "06:07",
   "CivTwilightEnd" : "18:09",
   "CivTwilightStart" : "07:16",
   "DayLength" : "09:51",
   "NautTwilightEnd" : "18:44",
   "NautTwilightStart" : "06:41",
   "ServerTime" : "2018-02-02 18:11:42",
   "SunAtSouth" : "12:42",
   "Sunrise" : "07:47",
   "Sunset" : "17:38",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 20,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00014143",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-12-23 20:02:07",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "TV",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "243"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}
</pre>

**Comment by marcotini** [comment]
And if you want all json.htm?type=devices it's not possible, I have over 140 devices.

**Comment by PatchworkBoy** [comment]
Yes that IS the problem. 100 devices max per instance of homebridge as per documentation.

**Comment by marcotini** [comment]
Ok it's not for the 100 device because now I have 50 and some lights are not working.

**Comment by PatchworkBoy** [comment]
Mosquitto installed & MQTT client hardware added in Domoticz?
