### ISSUE TITLE
MiLight iBox V6

### ISSUE THREAD

**Issue by poudenes** [PatchworkBoy/homebridge-edomoticz#117]
Hi All,

I have sometimes the problem when i use Siri to turn off or on a group/lamp it mess up the MiLight controller in Domoticz. I cannot use the switches to turn them on inside Domoticz, i cannot use Homekit to turn them on/off as well. I need to restart Domoticz to let them work again.

I get a error when this happen:

2017-10-22 22:43:22.119  Error: AppLamp: Error sending command to Bridge!...
2017-10-22 23:29:20.410  Error: AppLamp: Error sending command to Bridge!...
2017-10-22 23:44:08.535  Error: AppLamp: Error sending command to Bridge!...

Only what work when it crash is the MiLilght App on iPhone itself. So its something between Homebridge, MQTT, Domoticz, MiLight Controller.

Does someone have this as well and solve this?

**Comment by poudenes** [comment]
Nobody?

**Comment by PatchworkBoy** [comment]
That isn’t an eDomoticz related/generated error...
