### ISSUE TITLE
add fan charateristic

### ISSUE THREAD

**Issue by lily148** [PatchworkBoy/homebridge-edomoticz#120]
Is it possible to add a fan characteristic into homebridge?
I have a RF fan and I am setting it to a dimmer fan switch. but in homebridge, it show as a switch.
Possible to implement the fan characteristic in homebridge so I can show the problem icon.

**Comment by PatchworkBoy** [comment]
Update to latest version. Set Switch Type dropdown in Domoticz to 'fan'.
