### ISSUE TITLE
No devices are showing in the iOS apps, except homebridge itself

### ISSUE THREAD

**Issue by redomo** [PatchworkBoy/homebridge-edomoticz#124]
Hi there,
I've installed edomoticz' homebridge and adapted the config.json to my situation.
The issue I have is that I do see under the iOS apps (Eve and Woning) the homebridge accessory, but none of my Domoticz devices show up.
I've tried to change to RoomId to all possible values, but whatever I try, no devices are shown.
What am I doing wrong? 
I'm running the latest stable versions of domoticz and edomoticz-homebridge.

**Comment by simonrb2000** [comment]
Room number is the IDX number.. Have you set that? 

Could try removing room number to see it that works

**Comment by redomo** [comment]
![image](https://user-images.githubusercontent.com/34001297/33796641-14e6671a-dcf9-11e7-8e40-5774291ff83f.png).
That's my roomplans. Made a new one just for homebridge.

This is the config.json:
![image](https://user-images.githubusercontent.com/34001297/33796689-f94e7b7c-dcf9-11e7-8d1f-bc5b654a2571.png)

**Comment by redomo** [comment]
Hi there,Tried all the things, but no solution. I've now posted both a printscreen of the Domoticz and a Json.config.Hope you can help further.Thanks.Op 8 december 2017 om 10:06 schreef simonrb2000 <notifications@github.com>:Room number is the IDX number.. Have you set that?Could try removing room number to see it that works—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Lorccan** [comment]
In the screenshots, you have roomid set to 2 in the config file and 3 for Homebridge in the Domoticz plan. These should match.

Have you tried using 0 as the room id in config.json?  All devices that are available should then appear.

**Comment by redomo** [comment]
I've tested with everything from 0 to 3. Nothing worked.... 
All I see in the apps is homebridge itself.

**Comment by Lorccan** [comment]
Do you have any devices in the Homebridge room in Domoticz?  (It's unclear from the picture which room is selected.)

I don't think it will make a difference, but I have my config.json in this order.  I have just noticed that you also have 'Domoticz' instead of 'eDomoticz in the name of the platform.

```{
    "description" : "Configuration file for Domoticz platform",
    "bridge" : {
            "name" : "Homebridge",
            "username" : "CC:22:3D:E3:CE:30",
            "port" : 51826,
            "pin" : "031-45-154"
        },
    "platforms": [
               {
            "platform": "eDomoticz",
            "name":     "eDomoticz",
            "server":   "127.0.0.1",
            "port":     "8080",
            "roomid":   0,
            "ssl":      0,
            "mqtt":     true
        }
],
    "accessories" : [
    ]
}
```

**Comment by redomo** [comment]
I can change that. Maybe it makes a difference.

What you are seeing is the ground level, begane grond in Dutch.

**Comment by simonrb2000** [comment]
Shouldn’t that be 3 and not 2.

On 14 Dec 2017, at 12:04, Lorccan <notifications@github.com<mailto:notifications@github.com>> wrote:


In the screenshots, you have roomid set to 2 in the config file and 3 for Homebridge in the Domoticz plan. These should match.

Have you tried using 0 as the room id in config.json? All devices that are available should then appear.

**Comment by RienduPre** [comment]
Any resolution, because I have the same issue

**Comment by redomo** [comment]
Sorry no. Feedback given didn't result in any improvement.

What helped is, I did a fresh install on an older RP2 for test purposes. That worked! So now I have to reinstall all devices on that RP2 as there's also no good way to get all devices from one to the other. Copying the database isn't working... 
Reinstalling 20+ devices is also not funny...

So for now I'm running without Siri or HomeKit. Bummer!

**Comment by simonrb2000** [comment]
When you say only homebridge is showing, I assume you have added it as a device?!? 

Copying devices/database over will not work. If you reinstall then you need to redo everything. I have to Homebridges running with around 160 devices so I know how you feel when you have to setup from scratch..

**Comment by redomo** [comment]
Yes, I've reinstalled from an image that included homebridge and added some dummy switches for testing. The dummy switches show up in the home kit apps.

On the other system, the one that's not showing any of my devices, all I see is the homebridge itself, no devices.

**Comment by simonrb2000** [comment]
Ok but to confirm. You have selected homebridge in Home app and entered the pin to pair/add it?

On 16 Jan 2018, at 19:41, redomo <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I've reinstalled from an image that included homebridge and added some dummy switches for testing. The dummy switches show up in the home kit apps.

On the other system, the one that's not showing any of my devices, all I see is the homebridge itself, no devices.

**Comment by redomo** [comment]
Yep! 

> Op 16 jan. 2018 om 20:46 heeft simonrb2000 <notifications@github.com> het volgende geschreven:
> 
> Ok but to confirm. You have selected homebridge in Home app and entered the pin to pair/add it? 
>

**Comment by simonrb2000** [comment]
Hmmm, try starting again with it.. delete the persist folder after deleting your home in the home app. Then restart homebridge and start again, oh also change the username in the config file.

On 16 Jan 2018, at 19:56, redomo <notifications@github.com<mailto:notifications@github.com>> wrote:

Yep!

> Op 16 jan. 2018 om 20:46 heeft simonrb2000 <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:
>
> Ok but to confirm. You have selected homebridge in Home app and entered the pin to pair/add it?
>

**Comment by redomo** [comment]
Can you please detail out how to start again. I’m not an expert. The persist folder was already deleted a couple of times after which I did a reboot. 
I suspected a problem with node, as long ago I added a Sonos switch to Domoticz, and reinstalled that. All without succes. 

> Op 16 jan. 2018 om 20:59 heeft simonrb2000 <notifications@github.com> het volgende geschreven:
> 
> Hmmm, try starting again with it.. delete the persist folder after deleting your home in the home app. Then restart homebridge and start again, oh also change the username in the config file. 
>

**Comment by PatchworkBoy** [comment]
https://www.domoticz.com/forum/viewtopic.php?f=36&t=10272
