### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by vespino** [PatchworkBoy/homebridge-edomoticz#125]
I have just install both homebridge-edomoticz and homebridge-synology on my synology diskstation and am now wondering where I should put the config.json. I have the following directories:

/root/.npm/registry.npmjs.org/homebridge-edomoticz
/root/.npm/homebridge-edomoticz
/tmp/npm-31690-497ec46a/registry.npmjs.org/homebridge-edomoticz
/usr/local/lib/node_modules/homebridge-edomoticz

Also: do I need both homebridge-edomoticz and homebridge-synology and how do I start homebridget and using siri now? I have already found the EVE app, but then what?

Sorry, new to this :)

PS I have domoticz running for a few years now.

**Comment by Lorccan** [comment]
Have you installed Homebridge?

**Comment by vespino** [comment]
Like I said, "I have just install both homebridge-edomoticz and homebridge-synology". Do I need to install more?

**Comment by Lorccan** [comment]
Those are just plugins. You need to install Homebridge itself: https://github.com/nfarina/homebridge

**Comment by vespino** [comment]
homebridge installs failes:

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 3.10.102
gyp ERR! command "/volume2/@appstore/Node.js_v8/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/homebridge/node_modules/mdns
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdns@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-15T07_04_53_846Z-debug.log

So I try npm install make -g

npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN checkPermissions Missing write access to /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules
npm ERR! path /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/volume2/@appstore/Node.js_v8/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/volume2/@appstore/Node.js_v8/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/volume2/@appstore/Node.js_v8/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/volume2/@appstore/Node.js_v8/usr/local/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/services/homes/admin/.npm/_logs/2017-12-15T07_06_30_278Z-debug.log

I'm basically following this: https://www.domoticz.com/wiki/Homekit_Siri

**Comment by PatchworkBoy** [comment]
Old / incorrect instructions. See the 1st post in the main eDomoticz thread in the forums at domoticz.com

**Comment by PatchworkBoy** [comment]
Or follow instructions in https://github.com/PatchworkBoy/homebridge-edomoticz/blob/master/InstallGuide

**Comment by PatchworkBoy** [comment]
Also, seeing as a lot of those are permission denied errors, you probably want to run things with sudo.

Installation on synology is unsupported / untested as none of the devs own one. You're reliant entirely on the help of forum members on domoticz.com or at the main homebridge repo when it comes to getting things running on anything beyond raspbian / macOS.

**Comment by vespino** [comment]
Think I’ll stick with Ubuntu and do some trial and error on synology later. 

Another thing: I have set loadscenes:1 in the domoticz part of the config.json but only regular switches are shown in HomeKit. Does this go under platforms or under bridge? I now have it under platforms. Read something about having to create a virtual switch to be able to do this, but I guess the loadscenes setting is there for a reason, right?

Is it also possible to push updates made in domoticz to homebridge/HomeKit?

**Comment by PatchworkBoy** [comment]
Loadscenes has never been supported by this plugin - it's from the original domoticz plugin which has no relation to this one. Hence creating a virtual switch.

And yes. Enable MQTT as per the eDomoticz forum thread.

**Comment by rjblake** [comment]
Depending on your Synology model, you can run Homebridge using Docker. I am using the version from here: [https://github.com/marcoraddatz/homebridge-docker](url). Alternatively, a possibility is tom install the Debian Chroot package on Synology and run it that way
