### ISSUE TITLE
MQTT error

### ISSUE THREAD

**Issue by astrapowerrr** [PatchworkBoy/homebridge-edomoticz#128]
Hi all,

I am doing something wrong but I can’t figure out what it is. 
Trying to setup MQTT between domoticz and HomeKit 
Installed MQTT I believe in the right way. 
Status says it’s running!
Changed config.json restart homebridge and then the error arrives. 
Could not connect to MQTT broker (local host:1833)

And domoticz says in the log:
Failed to start return code 14

**Comment by PatchworkBoy** [comment]
What do you believe to be the right way? We're not telepathic...

**Comment by astrapowerrr** [comment]
hi sorry...
here is some extra info of the steps i did.

cd /home/pi
wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
sudo apt-key add mosquitto-repo.gpg.key

cd /etc/apt/sources.list.d/
sudo wget http://repo.mosquitto.org/debian/mosquitto-jessie.list

sudo apt-get update

sudo apt-get install mosquitto

sudo nano /home/pi/.homebridge/config.json

{
 "bridge": {
 "name": "Homebridge",
 "username": "CC:21:3E:E4:DE:33",
 "port": 51826,
 "pin": "031-45-154"
 },
 "description": "Configuration file for (e)xtended Domoticz platform.",
 "platforms": [
 {
 "platform": "eDomoticz",
 "name": "eDomoticz",
 "server": "192.168.1.100",
 "port": "8080",
 "ssl": 0,
 "roomid": 8,
 "mqtt": 1, 
 "mqttenable":1,
 "mqttserver": "127.0.0.1",
 "mqttport": "1883",
 "mqttauth": 0,
 "mqttuser": "",
 "mqttpass": ""
 }
 ],
 "accessories": []
}

systemctl restart homebridge

systemctl status homebridge

it says:
homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since vr 2017-12-22 16:01:37 CET; 2 days ago
 Main PID: 1517 (homebridge)
   CGroup: /system.slice/homebridge.service
           1517 homebridge

Do you need more info? please ask..

**Comment by PatchworkBoy** [comment]
Have you then enabled MQTT in Domoticz...?

See https://www.sigmdel.ca/michel/ha/domo/domo_03_en.html#MQTTinDomoticz

**Comment by astrapowerrr** [comment]
Hi

I just started again with installing from step 2 and got stuck on this line

Systemctl status mosquitto

It gave me this error

pi@raspberrypi:~ $ systemctl status mosquitto
? mosquitto.service - Mosquitto MQTT Broker
   Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled)
   Active: failed (Result: start-limit) since vr 2017-12-29 14:57:07 CET; 54s ago
     Docs: man:mosquitto(8)
           https://mosquitto.org/
  Process: 712 ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf (code=exited, status=3)
 Main PID: 712 (code=exited, status=3)


Greets

Marco

Op 28 dec. 2017 om 15:54 heeft Marci <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Have you then enabled MQTT in Domoticz...?

See https://www.sigmdel.ca/michel/ha/domo/domo_03_en.html#MQTTinDomoticz<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.sigmdel.ca%2Fmichel%2Fha%2Fdomo%2Fdomo_03_en.html%23MQTTinDomoticz&data=02%7C01%7C%7C2cf65dcc9c244cd9069308d54e02eade%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636500696784034267&sdata=KiabV81zk2H%2FQrflrACq%2BhA4UdxPGegxSdbvcTxX1TQ%3D&reserved=0>

**Comment by astrapowerrr** [comment]
Hi.

I tested today again and now the service is loaded?? Don’t know how but it is running.

So proceeded with step 3.
But there nothing happens in the publish terminal.

Tried with ip of the rpi and with local host.
But both gave me no result.

So I believe it is not working correctly.

Any ideas were to start?

Greets

Marco

Op 29 dec. 2017 om 15:01 heeft Marco Soet <astrapowerrr@hotmail.com<mailto:astrapowerrr@hotmail.com>> het volgende geschreven:

Hi

I just started again with installing from step 2 and got stuck on this line

Systemctl status mosquitto

It gave me this error

pi@raspberrypi:~ $ systemctl status mosquitto
? mosquitto.service - Mosquitto MQTT Broker
   Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled)
   Active: failed (Result: start-limit) since vr 2017-12-29 14:57:07 CET; 54s ago
     Docs: man:mosquitto(8)
           https://mosquitto.org/
  Process: 712 ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf (code=exited, status=3)
 Main PID: 712 (code=exited, status=3)


Greets

Marco

Op 28 dec. 2017 om 15:54 heeft Marci <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Have you then enabled MQTT in Domoticz...?

See https://www.sigmdel.ca/michel/ha/domo/domo_03_en.html#MQTTinDomoticz<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.sigmdel.ca%2Fmichel%2Fha%2Fdomo%2Fdomo_03_en.html%23MQTTinDomoticz&data=02%7C01%7C%7C2cf65dcc9c244cd9069308d54e02eade%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636500696784034267&sdata=KiabV81zk2H%2FQrflrACq%2BhA4UdxPGegxSdbvcTxX1TQ%3D&reserved=0>

**Comment by PatchworkBoy** [comment]
See https://mosquitto.org/support/ for support installing mosquitto. We only provide support for the homebridge-edomoticz plugin itself, not the dependant components.
