### ISSUE TITLE
Error causing Homebridge to keep restarting

### ISSUE THREAD

**Issue by rjblake** [PatchworkBoy/homebridge-edomoticz#129]
All I have from the logs is:

`SyntaxError: Unexpected token C in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/usr/lib/node_modules/homebridge-edomoticz/lib/mqtt.js:57:24)
    at emitThree (events.js:136:13)
    at MqttClient.emit (events.js:217:7)
    at MqttClient._handlePublish (/usr/lib/node_modules/homebridge-edomoticz/node_modules/mqtt/lib/client.js:934:12)
    at MqttClient._handlePacket (/usr/lib/node_modules/homebridge-edomoticz/node_modules/mqtt/lib/client.js:305:12)
    at work (/usr/lib/node_modules/homebridge-edomoticz/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/lib/node_modules/homebridge-edomoticz/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/usr/lib/node_modules/homebridge-edomoticz/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/usr/lib/node_modules/homebridge-edomoticz/node_modules/readable-stream/lib/_stream_writable.js:395:5)`

This is running on Ubuntu and NodeJS 8.9.3. I have checked my config.json on JSONLint and it is correct. If I change the "mqtt": 1 to a 0 it runs without issue.

**Comment by Lorccan** [comment]
Do you have more than one room defined in config.json? I had a similar problem that I fixed by defining a single room in Domoticz for all devices that I wanted to expose to Homebridge (and then using that index). The alternative - and a way of testing without modifying the Domoticz config - is to define a single room with index 0 (which will expose all Domoticz devices).

**Comment by rjblake** [comment]
No - I have a single room (IDX9) with the devices. I also deleted all devices and added back a single one to see if that was the issue, but problem still is there

**Comment by PatchworkBoy** [comment]
You need to manually subscribe to domoticz’s mqtt stream using an mqtt reader and find the specific mqtt message causing the error, and the device sending that message. Your Domoticz installation is sending a piece of data in an unexpected format...

**Comment by jannnfe** [comment]
@PatchworkBoy Can you please describe how to fix this issue in detail. I am about 5 hours of trying to fix it! :(

**Comment by PatchworkBoy** [comment]
Already told you... run homebridge with the debug command. Wait for it to crash. Copy and paste the tail end of the output. 

A json object via MQTT begins and ends with { and }. Something is sending a message beginning with C instead of {. Only way to find out what is by seeing the MQTT messages.

**Comment by PatchworkBoy** [comment]
Which MQTT Broker are you using...? I’ve never seen one configured to send "connected" when it’s connected...

**Comment by jannnfe** [comment]
I'am using mosquitto.
I think it's just so weird, because yesterday everything was fine and today I suddenly get this mistake. I'm really baffled and hope that you can somehow help me further.
Sorry I bother you so much with my mistake.

**Comment by PatchworkBoy** [comment]
Therein lies your problem. Your broker can’t connect to Domoticz.

Have you definitely enabled the MQTT Client Hardware in Domoticz, and configured it as per the attached?

![mqtt](https://user-images.githubusercontent.com/3514253/36171750-bbadafb4-10fb-11e8-94ac-7fbf544ad149.jpeg)

**Comment by jannnfe** [comment]
Yes I have MQTT Client Gateway enabled in Domoticz and I think its working because when i toggle a light i get a MQTT message:
```
# mosquitto_sub -v -t '#'
ThermostatSensor/status Connected
tele/Aquariumlicht/LWT Online
tele/Garagentor/LWT Online
tele/Plattenspieler/LWT Online
tele/Doppellampe/LWT Online
tele/Thermostat/LWT Online
tele/Türöffner/LWT Online
tele/Aquariumtemperatur/LWT Online
domoticz/out Connection Lost
domoticz/out {
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "",
   "dtype" : "Lighting Limitless/Applamp",
   "id" : "00001BCE",
   "idx" : 11,
   "name" : "Schreibtisch",
   "nvalue" : 0,
   "stype" : "RGBW",
   "svalue1" : "100",
   "switchType" : "Dimmer",
   "unit" : 1
}
```

**Comment by PatchworkBoy** [comment]
It’s working intermittently. Occasionally it’s losing the connection - this shouldn’t be happening. 

You need to open a post over on the Domoticz forum to work out why Mosquitto is losing it’s connection... 

In the meantime we can add a handler for it to stop homebridge dying and just write an error to the error log.

Replace homebridge-edomoticz/lib/mqtt.js with this: https://gist.github.com/PatchworkBoy/530b9e5128904d9edac3c028fd261cab

...and restart homebridge. That should hopefully stop it from hard-crashing on you and let it recover whenever it comes back up.

**Comment by jannnfe** [comment]
I have now also found the reason why "Connected" or "Connection Lost" was found in the MQTT topic "domoticz / out".
If you switch on the Domoticz Controller with the ESPEasy firmware, it sends exactly one of the two status messages when it is connected and when the connection is interrupted.
Just a pity, because I would like to use this feature in combination with eDomoticz. Do you have an idea how to get this to work?

**Comment by PatchworkBoy** [comment]
The gist above should disregard _any_ malformed MQTT messages and log them as an error without halting homebridge.

**Comment by jannnfe** [comment]
Problem with ESPEasy fixed in newest Version:
https://github.com/letscontrolit/ESPEasy/issues/869
