### ISSUE TITLE
Support for Leviton Decora Smart Switches

### ISSUE THREAD

**Issue by Buckeyes1995** [PatchworkBoy/homebridge-edomoticz#130]
Hi,

 I have two Leviton DZ15S-1BZ Smart Switches. They are correctly recognized and controlled in Domoticz.  

 They are NOT showing up in Homekit on my IOS device.  I performed the API query and it doesn't appear they are supported yet, but it says they should still show up as ON/OFF?  Anyways, here is the API query output.. would greatly appreciate adding support.  The one shown is the "Lanai Fan Switch'

> {
   "ActTime" : 1515166334,
   "AstrTwilightEnd" : "19:07",
   "AstrTwilightStart" : "05:55",
   "CivTwilightEnd" : "18:09",
   "CivTwilightStart" : "06:53",
   "DayLength" : "10:25",
   "NautTwilightEnd" : "18:38",
   "NautTwilightStart" : "06:24",
   "ServerTime" : "2018-01-05 10:32:14",
   "SunAtSouth" : "12:30",
   "Sunrise" : "07:18",
   "Sunset" : "17:43",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "Z-Stick Gen5",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000801",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-01-05 09:51:34",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Lanai Fan Switch",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "48"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by PatchworkBoy** [comment]
These should be fully supported. They comply with standard switch characteristics - SwitchTypeVal 0. No reason for them not to be detected.

Are you using excludedDevices in config.json at all? Wondering if this device shares ID with one you’ve excluded... which would be fixed in latest update by switching excludedDevices array to idx instead of id.
