### ISSUE TITLE
No devices discovered, please help

### ISSUE THREAD

**Issue by RienduPre** [PatchworkBoy/homebridge-edomoticz#131]
Hi,

I installed domoticz on a RPi, which was allready running HomeBridge successfully and added the edomoticz homebridge plugin.
Everything seems to be working (no errors), but no device is discovered from the Domoticz system
This is the startup log
```
ge[1982]: [1/16/2018, 8:16:25 PM] Loaded plugin: homebridge-config-ui
Jan 16 20:16:25 homebridge homebridge[1982]: [1/16/2018, 8:16:25 PM] Registering platform 'homebridge-config-ui.config'
Jan 16 20:16:25 homebridge homebridge[1982]: [1/16/2018, 8:16:25 PM] ---
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Loaded plugin: homebridge-edomoticz
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] ---
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Loaded plugin: homebridge-klikaanklikuit
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Registering platform 'homebridge-klikaanklikuit.KlikAanKlikUit'
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] ---
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Loaded config.json with 0 accessories and 2 platforms.
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] ---
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Loading 2 platforms...
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] [Config] Initializing config platform...
Jan 16 20:16:31 homebridge homebridge[1982]: [1/16/2018, 8:16:31 PM] [eDomoticz] Initializing eDomoticz platform...
Jan 16 20:16:31 homebridge homebridge[1982]: [1/16/2018, 8:16:31 PM] Loading 0 accessories...
Jan 16 20:16:31 homebridge homebridge[1982]: Setup Payload:
Jan 16 20:16:31 homebridge homebridge[1982]: X-HM://0023ISYX012GP
```

And the config.json
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-156",
        "model": "Homebridge",
        "serialNumber": "1.0"
    },
    "description": "This is an homebridge configuration file.",
    "accessories": [],
    "platforms": [
        {
            "platform": "config",
            "port": 8080,
            "log": "/var/log/daemon.log",
            "restart": "sudo systemctl restart homebridge.service",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "name": "Config"
        },
        {
            "platform": "eDomoticz",
            "server": "127.0.0.1",
            "port": "8081",
            "ssl": 0,
            "roomid": 0,
            "mqtt": 0,
            "excludedDevices": [],
            "name": "eDomoticz"
        }
    ]
}

```

**Comment by simonrb2000** [comment]
Are you using MQTT?

On 16 Jan 2018, at 19:22, RdP <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I installed domoticz on a RPi, which was allready running HomeBridge successfully and added the edomoticz homebridge plugin.
Everything seems to be working (no errors), but no device is discovered from the Domoticz system
This is the startup log
ge[1982]: [1/16/2018, 8:16:25 PM] Loaded plugin: homebridge-config-ui
Jan 16 20:16:25 homebridge homebridge[1982]: [1/16/2018, 8:16:25 PM] Registering platform 'homebridge-config-ui.config'
Jan 16 20:16:25 homebridge homebridge[1982]: [1/16/2018, 8:16:25 PM] ---
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Loaded plugin: homebridge-edomoticz
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] ---
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Loaded plugin: homebridge-klikaanklikuit
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Registering platform 'homebridge-klikaanklikuit.KlikAanKlikUit'
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] ---
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Loaded config.json with 0 accessories and 2 platforms.
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] ---
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] Loading 2 platforms...
Jan 16 20:16:28 homebridge homebridge[1982]: [1/16/2018, 8:16:28 PM] [Config] Initializing config platform...
Jan 16 20:16:31 homebridge homebridge[1982]: [1/16/2018, 8:16:31 PM] [eDomoticz] Initializing eDomoticz platform...
Jan 16 20:16:31 homebridge homebridge[1982]: [1/16/2018, 8:16:31 PM] Loading 0 accessories...
Jan 16 20:16:31 homebridge homebridge[1982]: Setup Payload:
Jan 16 20:16:31 homebridge homebridge[1982]: X-HM://0023ISYX012GP

And the config.json
{
"bridge": {
"name": "Homebridge",
"username": "CC:22:3D:E3:CE:30",
"port": 51826,
"pin": "031-45-156",
"model": "Homebridge",
"serialNumber": "1.0"
},
"description": "This is an homebridge configuration file.",
"accessories": [],
"platforms": [
{
"platform": "config",
"port": 8080,
"log": "/var/log/daemon.log",
"restart": "sudo systemctl restart homebridge.service",
"temp": "/sys/class/thermal/thermal_zone0/temp",
"name": "Config"
},
{
"platform": "eDomoticz",
"server": "127.0.0.1",
"port": "8081",
"ssl": 0,
"roomid": 0,
"mqtt": 0,
"excludedDevices": [],
"name": "eDomoticz"
}
]
}

**Comment by RienduPre** [comment]
No, but I tried that too, with the same result

**Comment by simonrb2000** [comment]
Is 8081 the port of your Domoticz setup?

On 16 Jan 2018, at 20:03, RdP <notifications@github.com<mailto:notifications@github.com>> wrote:


No, but I tried that too, with the same result

**Comment by RienduPre** [comment]
Yes it is

**Comment by RienduPre** [comment]
<img width="979" alt="2018-01-16_2107" src="https://user-images.githubusercontent.com/9009949/35009880-580dd458-fb01-11e7-90b0-ed579d115f31.png">

**Comment by simonrb2000** [comment]
Local networks and passwords setup correctly. IE. 127.0.0.1 is exempt..

On 16 Jan 2018, at 20:08, RdP <notifications@github.com<mailto:notifications@github.com>> wrote:


[2018-01-16_2107]<https://user-images.githubusercontent.com/9009949/35009880-580dd458-fb01-11e7-90b0-ed579d115f31.png>

**Comment by RienduPre** [comment]
What do you mean?
Both Domoticz and the Homebridge are running on the same RPi. I have no userid's and password set

**Comment by PatchworkBoy** [comment]
Discovery (was) done by looking at 127.0.0.1:8081/json.htm 

Copy and paste what is displayed when you visit this URL...

**Comment by RienduPre** [comment]
{
   "status" : "ERR"
}

**Comment by simonrb2000** [comment]
That would be why your not getting any devices. What address do you use to access domoticz in your web browser? Try that address and port..

On 21 Jan 2018, at 09:08, RdP <notifications@github.com<mailto:notifications@github.com>> wrote:


{
"status" : "ERR"
}

**Comment by simonrb2000** [comment]
Ignore the above comment.. I have just woken up.. sorry

**Comment by RienduPre** [comment]
Can json be disabled in Domoticz, I have done this integration before several times, but never had this issue

**Comment by RienduPre** [comment]
Hi,

Any other clues why this is not working ?

**Comment by PatchworkBoy** [comment]
If json output produces an error, the issue is at the Domoticz end of things, not the Homebridge end of things. Only thing I can suggest is start afresh following the instructions in https://github.com/PatchworkBoy/homebridge-edomoticz/blob/master/InstallGuide

**Comment by PatchworkBoy** [comment]
NB: startup log no longer shows discovered devices due to dynamic platform method... add bridge to your home and step through hitting next in your HomeKit app and each accessory should then be added.
