### ISSUE TITLE
push button

### ISSUE THREAD

**Issue by theo-69** [PatchworkBoy/homebridge-edomoticz#133]
How can I add my push button to homekit. How do i have to config them in domoticz.

what does "Push Switches - Domoticz SwitchTypeVal: 9" mean

**Comment by PatchworkBoy** [comment]
See https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Retrieve_status_of_specific_device 
SwitchTypeVal is given in the JSON output for that device.

In Domoticz, edit the switch and set it’s type to Push On

**Comment by theo-69** [comment]
ok it shows 18 how do I change to 9??? I am a newbie

**Comment by theo-69** [comment]
Got it however its not a button just a switch, are there any plans to include button with single and double click (function like the pop button)?

**Comment by PatchworkBoy** [comment]
Not that I’m aware of unless an existing homebridge plugin that covers that particular button can be found so I can see how it’s own characteristics map across to the Apple HomeKit spec.

**Comment by theo-69** [comment]
The Button does work in Domoticz, but shows at not compatible in HomeKit.
This homebridge plugin (https://github.com/YinHangCode/homebridge-mi-aqara) does integrate button mit double and single click (even the one i have). Its integrated like a Logitech Pop Button or Hue Dimmer

**Comment by PatchworkBoy** [comment]
Ditto your socket post - I need Domoticz JSON API output for the button in each of it’s states (ie: JSON output for single click, JSON output for double etc) - see q/a section at https://www.domoticz.com/forum/viewtopic.php?f=36&t=10272

**Comment by theo-69** [comment]
The json output would be:

`{
   "ActTime" : 1516742124,
   "ServerTime" : "2018-01-23 17:15:24",
   "Sunrise" : "06:35",
   "Sunset" : "18:02",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 1.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 12,
         "HardwareName" : "Aqara",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01A66841",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-01-23 13:52:38",
         "Level" : 0,
         "LevelActions" : "||",
         "LevelInt" : 0,
         "LevelNames" : "Off|Click|Double Click",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Aquara Button",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "357"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

its configured like this in Dashboard:

<img width="1164" alt="screenshot_79" src="https://user-images.githubusercontent.com/28484958/35301143-2d903f76-0061-11e8-8bf0-32aff0302ad4.png">

**Comment by PatchworkBoy** [comment]
I need to see the different Status: messages for the switch in each of it’s states.

**Comment by theo-69** [comment]
okay that Click

{
   "ActTime" : 1516742464,
   "ServerTime" : "2018-01-23 17:21:04",
   "Sunrise" : "06:35",
   "Sunset" : "18:02",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 12,
         "HardwareName" : "Aqara",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01A66841",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-01-23 17:20:53",
         "Level" : 10,
         "LevelActions" : "||",
         "LevelInt" : 10,
         "LevelNames" : "Off|Click|Double Click",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Aquara Button",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "357"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

and thats double click

{
   "ActTime" : 1516742545,
   "ServerTime" : "2018-01-23 17:22:25",
   "Sunrise" : "06:35",
   "Sunset" : "18:02",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 9,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 12,
         "HardwareName" : "Aqara",
         "HardwareType" : "Xiaomi Gateway",
         "HardwareTypeVal" : 95,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "01A66841",
         "Image" : "Generic",
         "IsSubDevice" : false,
         "LastUpdate" : "2018-01-23 17:22:13",
         "Level" : 20,
         "LevelActions" : "||",
         "LevelInt" : 20,
         "LevelNames" : "Off|Click|Double Click",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "Aquara Button",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "357"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by PatchworkBoy** [comment]
Leave it with me... but it won’t be anytime in the near future as I’m flat out with other things at the moment. Will attempt to add support in the next update, whenever that may be.

**Comment by theo-69** [comment]
Cool Thanks great!!!

**Comment by PatchworkBoy** [comment]
For my reference purposes: https://github.com/YinHangCode/homebridge-mi-aqara/blob/master/parser/ButtonParser.js

**Comment by PatchworkBoy** [comment]
See https://www.domoticz.com/forum/viewtopic.php?f=36&t=22015&p=169677#p169677

**Comment by PatchworkBoy** [comment]
Done - https://github.com/PatchworkBoy/homebridge-edomoticz/commit/7fd4dbf0206a0c2324a9d5264fef541862776643

```
pi@domoticz ~/ $ sudo npm update -g homebridge-edomoticz
/usr/local/lib
└── homebridge-edomoticz@2.1.6 
```

**Comment by theo-69** [comment]
Thanks for your work, however I have a strange behaving. I does not matter how i click (single, double, long) it always triggered first long press and then single click in HomeKit (within 1 second) So it always only triggers single click.
<img width="1176" alt="screenshot_83" src="https://user-images.githubusercontent.com/28484958/35769485-01c7326c-08e2-11e8-8bda-d8324a562013.png">

**Comment by PatchworkBoy** [comment]
Should be fixed by https://github.com/PatchworkBoy/homebridge-edomoticz/commit/ed2e7a707e6feae35105e185887e9ed93bf8b1db

```
pi@domoticz ~/ $ sudo npm update -g homebridge-edomoticz
/usr/local/lib
└── homebridge-edomoticz@2.1.9
```

Test & confirm...

**Comment by theo-69** [comment]
did that still same also with another button with only click and double click

**Comment by PatchworkBoy** [comment]
Righty - one last attempt - https://github.com/PatchworkBoy/homebridge-edomoticz/commit/8266f82762c431a3e1c74eb1aacfe0aac490f32a

```
pi@domoticz ~/ $ sudo npm update -g homebridge-edomoticz
/usr/local/lib
└── homebridge-edomoticz@2.1.10
```

**Comment by theo-69** [comment]
Working now with 2.1.10, thanks @PatchworkBoy
