### ISSUE TITLE
socket symbol HomeKit

### ISSUE THREAD

**Issue by theo-69** [PatchworkBoy/homebridge-edomoticz#134]
I know i asked this before, however there was a small misunderstanding (i apologize for this but english is not my nativ language), so this time i try to explain it better.

It would be great it a socket in Domoticz shows as a socket in the Home App from Apple as well.

I do know I can change it in the EVE App but in Home it still shows as Switch and you can not change this in the home App.

![img_1611](https://user-images.githubusercontent.com/28484958/35292149-025a8dae-0046-11e8-8ca7-fabebb75a7c2.PNG)

The socket icon in Home looks like:

![phone-kit-1](https://user-images.githubusercontent.com/28484958/35292213-32003522-0046-11e8-8c5e-1599a7087a65.jpg)

**Comment by PatchworkBoy** [comment]
Unless Domoticz differentiates it’s output for a socket from a switch, nothing can be done. As far as I’m aware, Domoticz doesn’t. This is done by comparing the JSON output of a switch vs a socket in domoticz, for which I’d need a sample. See first item in q/a at https://www.domoticz.com/forum/viewtopic.php?f=36&t=10272 for getting the JSON output for your socket.

**Comment by PatchworkBoy** [comment]
Right - after inspecting JSON api output, this is still as it was when I first wrote this plugin. Homebridge-edomoticz uses switchtypeval, type and subtype in the json output to differentiate between the devices. These values do not differentiate between a switch and a socket. The JSON output is the same regardless. Therefore, homebridge-edomoticz cannot natively set the device type to a socket. The MQTT output contains even less with which to identify and categorise a device. 
So unfortunately, no, this isn’t going to change in the plugin at this time.

**Comment by theo-69** [comment]
Okay, understand. Just an Idee, if we would use the same like with the Occupancy Sensors and use any SwitchTypeVal: 0 with "Socket" in it's title, would this work?

**Comment by PatchworkBoy** [comment]
Support via this method has already been written in fennec’s fork of homebridge-edomoticz at https://github.com/fennec622/homebridge-edomoticz (apparently - see https://www.domoticz.com/forum/viewtopic.php?f=36&t=10272&start=1400#p152374)

**Comment by theo-69** [comment]
okay thanks, maybe it would be cool if you integrate it in the official plugin, yours is more reliable and more up to date...

**Comment by PatchworkBoy** [comment]
npm update to latest version (2.1.0)... issue already resolved in git repo - just needed publishing to npm (now done).
