### ISSUE TITLE
Device name in the logfile has been replaced by the device type

### ISSUE THREAD

**Issue by ooii** [PatchworkBoy/homebridge-edomoticz#135]
Hi,

Since `v2.1.2`, some of the devices appear as `Light`, `Switch`, `WallSocket`, and `Water` while they have their name before. It makes it difficult to distinguish them.

**Comment by PatchworkBoy** [comment]
It's actually logging the image type. Comment out the following lines or change them to whatever you want to see logged in lib/domoticz_accessory.js lines 30 & 31 (ie: change this.image to this.name)
```

	this.platform.log(this.idx);
	this.platform.log(this.image);


```
Technically it should be logging _nothing_ other than error messages unless you're running DEBUG=* homebridge -D 

This particular issue is lingering from someone else's commit to the source code. Once I've resolved it it will go back to logging nothing unless it's an error.

**Comment by ooii** [comment]
OK, thanks. I'm running it **without** the debug flag.
