### ISSUE TITLE
How to gain acces to Domoticz when username and password are set in Domoticz

### ISSUE THREAD

**Issue by Skottelbraai** [PatchworkBoy/homebridge-edomoticz#139]
Hello there,
I am very new with domotica and eDomoticz.
I have an issue with eDomotics when a Username and Password are set in Domoticz.
Homekit will not connect to Domoticz.
How can i change the json snippet so i can gain acces?
eg.
    "platform": "eDomoticz",
    "name": "eDomoticz",
    "_username": "my domotica username",
    "password": "my pswrd",_
    "server": "ip of my server",
    "port": "8080",
    "ssl": 0,
    "romid": 0,
    "mqtt": 1,

Any Clue?
Thanks.

**Comment by PatchworkBoy** [comment]
See 'authentication' section in https://github.com/PatchworkBoy/homebridge-edomoticz/blob/master/README.md
