### ISSUE TITLE
3 different question

### ISSUE THREAD

**Issue by adrianmihalko** [PatchworkBoy/homebridge-edomoticz#141]
1, I suggest you to update readme:

It seem to be temperature sensors are working in the default Homekit app. Maybe only the single temperature sensor is supported, because I have other BME280 sensor Baro+Temp+Hum, which is not supported, only in EVE.

2, Yeelight RGBW bulb recognized as RGBW(W) / Lighting Limitless/Applamp, correct. 

 Everything is working fine, unless that I can't set a nice soft-warm color. I can set all RGB color on the scale, but something around 3500K not.

From LUA script I set like this:

2018-02-28 20:59:27.519 LUA: sudo echo -ne '{"id":1, "method":"set_scene","params":["ct",3572, 75]}\r\n' | nc -w1 192.168.1.82 55443
2018-02-28 20:59:27.519 LUA: Color Temp= 3572

This setting in the reality is ice blue, if I move a little bit higher it's immediately set lamp to orangeish-red color:

![img_1271-2](https://user-images.githubusercontent.com/733361/36869880-89b83bb0-1d9d-11e8-8ff2-e0256d9d27a1.jpg)

I already tried to play with colour/temperature setting, without success. 
 
3. My thermostat in Homekit is showing 24C, but it's set to 23.5. Homekit doesn't support decimal places?

```
{
   "ActTime" : 1519932924,
   "AstrTwilightEnd" : "19:12",
   "AstrTwilightStart" : "04:43",
   "CivTwilightEnd" : "18:00",
   "CivTwilightStart" : "05:55",
   "DayLength" : "11:03",
   "NautTwilightEnd" : "18:36",
   "NautTwilightStart" : "05:19",
   "ServerTime" : "2018-03-01 20:35:24",
   "SunAtSouth" : "11:57",
   "Sunrise" : "06:26",
   "Sunset" : "17:29",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "23.5",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : true,
         "ID" : "001405B",
         "LastUpdate" : "2018-02-27 18:21:47",
         "Name" : "Thermostat",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2, 4 ],
         "Protected" : false,
         "SetPoint" : "23.5",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "SetPoint",
         "Timers" : "false",
         "Type" : "Thermostat",
         "TypeImg" : "override_mini",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "12"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}
```

Thank you,
Adrian

**Comment by PatchworkBoy** [comment]
3) Depends on your app. Apple Home.app rounds to nearest degree, always. Eve rounds to nearest 0.5 iirc. Matthias’ Original Home.app works to 1 decimal place (so 0.1 deg resolution). This is down to the choice of app, not homebridge or the plugin.

2) Nothing further will be done on RGBWW support etc until changes are complete with Domoticz core, pushed to Domoticz release branch, and then hopefully will provide decent feedback via JSON api once that work is done - ref: https://github.com/domoticz/domoticz/issues/2078#issuecomment-369398222

1) Yes, temperature characteristic of sensors is supported in Home.app.

**Comment by emontnemery** [comment]
@adrianmihalko Which app is that color picker from?

**Comment by adrianmihalko** [comment]
It's the built in color picker in Homekit app.
