### ISSUE TITLE
AirQuality States

### ISSUE THREAD

**Issue by avgays** [PatchworkBoy/homebridge-edomoticz#142]
Hi,

Latest Domoticz bettas (e.g. 3.8968)  return  AirQuality States as
"Excellent","Good","Fair","Mediocre","Bad"
in domoticz_accessory.js first 3 are correctly mapped to "Excellent","Good","Fair", 
but not last 2, they both are mapped as default to "Fair"

can you, please, add this 2 states:
```
                case "Mediocre":
                    {
                        value = Characteristic.AirQuality.INFERIOR;
                        break;
                    }
                case "Bad":
                    {
                        value = Characteristic.AirQuality.POOR;
                        break;
                    }
```

**Comment by xTheRamon** [comment]
Thank you for your clear request. Have just added the 'new' states in commit 391d3f0.

**Comment by xTheRamon** [comment]
On that note, I have also pushed the new version to NPM! ;)

```+ homebridge-edomoticz@2.1.11```
