### ISSUE TITLE
Support for the new WW / RGB / RGBW / RGBWW dimmer

### ISSUE THREAD

**Issue by adrianmihalko** [PatchworkBoy/homebridge-edomoticz#147]
Hi,

There is a new dimmer plugin [in development for Domoticz](https://github.com/domoticz/domoticz/issues/2078).

It's compatible with current version of edomoticz, but there are small glitches which needs to be fixed.

_There is a little glitch in the white mode (color temperature)._
This seems to be limitation in Homebridge/eDomoticz (it sends RGB hex through API `setcolbrightnessvalue` instead of color temperature through API `setkelvinlevel`) together with the issue below (unsaturated colors are translated to white, and Yeelight driver does not handle that).

_If I set #fefefe, color is not changing (example from red):_
This is due to special behavior of Domoticz when setting RGB hex string: Almost white is translated to exactly white, and the yeelight driver is not handling the request to be exactly white correctly. I don't dare to change this behavor for the sake of backwards compatibility. I'll modify the yeelight driver to try to handle it better though, if you don't mind testing again.

---

If you have a little time, can you please cooperate with @emontnemery to fix this issue?

**Comment by xTheRamon** [comment]
Hi @adrianmihalko,

Domoticz RGB dimmers/lamps has always been kind of an issue. I just looked through our code, we're already sending HEX values to the Domoticz API.

```Domoticz.updateDeviceStatus(this, "setcolbrightnessvalue", {
                "hex": Helper.HSVtoRGB([this.hueValue, this.saturationValue, 100])
            },```

I have also opened an issue on this a while ago (but was closed 🙈):
https://github.com/domoticz/domoticz/issues/909

**Comment by emontnemery** [comment]
@xTheRamon What is being worked on domoticz/domoticz#2078 is to:
- Allow setting any color, not just fully saturated ones, like you asked for in domoticz/domoticz#909
- Better support for color temperature
- Set color will be reported by Domoticz over MQTT and in web API status

**Comment by xTheRamon** [comment]
Oh wow, great work. I'll definitely have a look. Thank you for your effort.

**Comment by Yardco** [comment]
Any progress on this?

**Comment by morilm** [comment]
Hi. The color RGB/W/WW support if finished on domotic Color values are provided now on Json query.

like  "Color" : "{\"b\":255,\"cw\":0,\"g\":3,\"m\":3,\"r\":176,\"t\":0,\"ww\":0}"

information is here: 
[https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Set_a_light_to_a_certain_color_or_color_temperature]

So the only missing part is to implement the new subtypes into homebridgde.  I have already open a request to include it.

Regards,
Miguel

**Comment by NewFolk** [comment]
Hi,
I have just bought IKEA WW zigbee bulb and i could not change temperature through edomoticz.
While everything OK through domoticz itself. 

This issue is Open? No decision or workaround?

**Comment by PatchworkBoy** [comment]
Fixed.

**Comment by PatchworkBoy** [comment]
Above fixed in https://github.com/PatchworkBoy/homebridge-edomoticz/commit/59cf9ee5ebea0067be78bb101bf0b5d330042f94
