### ISSUE TITLE
Support for kWh devices

### ISSUE THREAD

**Issue by tazounet** [PatchworkBoy/homebridge-edomoticz#150]
Hello,

I have the following warning in homebridge log:

Apr 01 17:26:32 raspberrypi homebridge[11728]: ^ For: Linky
Apr 01 17:26:54 raspberrypi homebridge[11728]: HAP Warning: Characteristic undefined not in required or optional characteristics for service 24a8d81a-3d7b-4965-9086-7edc3ef4fab3. Adding anyway.
Apr 01 17:26:54 raspberrypi homebridge[11728]: ^ For: kWh Meter lampe Galle
Apr 01 17:26:54 raspberrypi homebridge[11728]: HAP Warning: Characteristic undefined not in required or optional characteristics for service 24a8d81a-3d7b-4965-9086-7edc3ef4fab3. Adding anyway.

The "problem" is in homebridge or homebridge-edomoticz ?

Thanks

**Comment by PatchworkBoy** [comment]
Neither. Choice of app. kWh meters are unsupported in apple's home app, so homebridge issues the above warning. The meters will show and function fine in other apps (eg: elegato eve)

**Comment by tazounet** [comment]
Ok, thanks :)
