### ISSUE TITLE
Cannot install edomoticz

### ISSUE THREAD

**Issue by RienduPre** [PatchworkBoy/homebridge-edomoticz#160]
I've done this many times, but today I get errors during the install off eDomoticz.

Any idea where to look for a solution?

See logging below

pi@homebridge:~ $ sudo npm install -g homebridge-edomoticz
npm ERR! file /root/.npm/once/1.4.0/package/package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token '"' at 1:99
npm ERR! &0","descriqtion":"Run a function eXactly one |ime","main":"gnce.js"."dy2ectori
npm ERR!                                                                      ^
npm ERR! File: /root/.npm/once/1.4.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-16T16_10_13_858Z-debug.log

Best regards,
Rien

**Comment by PatchworkBoy** [comment]
It’s the 'Once' package’s package.json that has/had the error... a dependency of homebridge-edomoticz. Don’t know _why_ you’re getting that error, or a different package.json than I get when I install via npm - all goes through without error here.
