### ISSUE TITLE
RGB subtype for SwitchTypeVal 7

### ISSUE THREAD

**Issue by morilm** [PatchworkBoy/homebridge-edomoticz#161]
Hi there...

After the implementation of the RBG switch in domozticz, should it be possible to add the RGB subtype(s) into homebrigde?

See bellow example of Json query with the "color" information on a RGB switch.  Device is seem at homebrigde as a "dimmer" only device (no color).  On/off and %bright works ok.

So it seems Homekit have different switch type(s) for dimmers&on/off vs the one to pickup colors.

Thanks
Miguel

`{
   "result" : [
      {
         "Color" : "{\"b\":255,\"cw\":0,\"g\":3,\"m\":3,\"r\":176,\"t\":0,\"ww\":0}",
         "SubType" : "RGB",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Color Switch",
         "TypeImg" : "dimmer",
         "idx" : "2476"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

**Comment by morilm** [comment]
PatchworkBoy...  the issue can be seen with virtual devices too.

If you create a RGB/RGBW/RGBWW switch on domoticz (updated version) it's been seen as dimmer only (no color choice) device on homekit.

regards
Miguel

**Comment by morilm** [comment]
Sorry.. last minute correction.  Issue is only happening with RGB subtype.. RGBW/WW seems to be fine,,

**Comment by jacha05** [comment]
+1 on this it would be nice

**Comment by EdddieN** [comment]
What about RGBWWZ, I see them only as dimmers, no colour

**Comment by jacha05** [comment]
Any updates on this :)?

**Comment by jacha05** [comment]
Fixed it 

Line 1446 in lib/domoticz_accessory.js
add this: if (this.subType == "RGBW" || this.subType == "RGBWW" || this.subType == "RGBWWZ"

**Comment by PatchworkBoy** [comment]
Fixed in https://github.com/PatchworkBoy/homebridge-edomoticz/commit/42ff35a09e5ffe95432f604ca9e1a543c2b00454
