### ISSUE TITLE
change device type in home app

### ISSUE THREAD

**Issue by shootelicious** [PatchworkBoy/homebridge-edomoticz#169]
I am very happy with the edomoticz plugin and use it often, there is only one thing I don't understand. For some reason some switches are represented as switches in Home (or EVE) and can be changed to a Fan or a Lamp but with other switches that is not possible. 
I want for example to change the dimmer I use for controlling my ventilation to a Fan in Home (or EVE) but that option is not available. I guess this has something to do with a config file somewhere but I don't know where to look.

**Comment by Bizzarrini** [comment]
Agreed, I would like the same functionality 👍

**Comment by boscorelly** [comment]
You can’t change the type for all, it depends of some conditions inside HomeKit. 
Btw, I have the same problem : my xiaomi zigbee plug is recognized as a switch and not as a plug. So, I loose power consumption and will be confusion when I will enhance my home with more devices.

**Comment by PatchworkBoy** [comment]
Set switch icon in Domoticz to wall socket for a wall socket. To fan for fan etc. Delete cachedAccessories from ~/.homebridge and restart to pick up changes.
