### ISSUE TITLE
IOS 12: States are not always synchronized

### ISSUE THREAD

**Issue by couchadonis** [PatchworkBoy/homebridge-edomoticz#170]
Since I use IOS 12, the states of some devices are not always synchronized correctly between Domoticz and HomeKit.

If I turn on a virtual switch in HomeKit, Domoticz takes over the switching state correctly. Conversely, it doesn't work. If I turn the same virtual switch off in Domoticz, the switching state is not taken over in HomeKit. And a second problem: The opening states of my door sensors are not longer updated in Homekit.

**Comment by PatchworkBoy** [comment]
Ensure you have MQTT setup and communicating correctly on your system between the plugin and Domoticz.

**Comment by couchadonis** [comment]
Thanx for the prompt reply! In fact, the mqqt settings caused the problems... Problem solved.
