### ISSUE TITLE
Temp+Hum+Baro Not Supported

### ISSUE THREAD

**Issue by jannnfe** [PatchworkBoy/homebridge-edomoticz#177]
Hey,
I created a virtual device in Domoticz (Temp+Hum+Baro).
In HomeKit this device is Not supported. Normally it should Display only as a temperature sensor Right?
Thanks! :)

**Comment by RienduPre** [comment]
+1

**Comment by PatchworkBoy** [comment]
They currently get mapped as Eve Weather devices to function fully in Eve app. Need to write in support for a config flag to map as plain temp sensor.

**Comment by PatchworkBoy** [comment]
Remove .homebridge/accessories/cachedAccessories, update to v2.1.23, restart.
