### ISSUE TITLE
Motion Sensor Battery

### ISSUE THREAD

**Issue by MattVador** [PatchworkBoy/homebridge-eDomoticz#18]
Hi,

When I tried this plugin with a Fibaro Motion Sensor, I've got this error :
`/usr/lib/node_modules/homebridge-edomoticz/index.js:1107motionService.getCharacteristic(new Characteristic.StatusLowBattery()).on('get',
                                                                    ^
TypeError: Cannot read property 'on' of undefined`

Looking a the code for smoke sensor, I saw that the method used is `addCharacteristic` instead of `getCharacteristic`.

I tried to change the method with `addCharacteristic` for the motion sensor and it works.

**Comment by PatchworkBoy** [comment]
Ah. I probably copied & pasted it from an accessory that had low-battery predefined in it's service... whereas the service for this doesn't. Will amend and update this evening!

**Comment by PatchworkBoy** [comment]
Fixed - https://github.com/PatchworkBoy/homebridge-eDomoticz/blob/master/index.js#L1109

Ta!
