### ISSUE TITLE
Error: connect EMFILE 127.0.0.1:8080 - Local (undefined:undefined)

### ISSUE THREAD

**Issue by fennec622** [PatchworkBoy/homebridge-edomoticz#183]
Hi 

I have sometimes this error

i restart homebridge and it's ok 

do you know why 

thanks

`Oct  7 20:15:23 Serveur_Ubuntu homebridge[13983]: [2019-10-7 8:15:23 PM] [eDomoticzs] There was a problem connecting to Domoticz.
Oct  7 20:15:23 Serveur_Ubuntu homebridge[13983]: - Error: connect EMFILE 127.0.0.1:8080 - Local (undefined:undefined)`

**Comment by PatchworkBoy** [comment]
You’ve hit max open files limit in your OS. Not an issue with homebridge-edomoticz.

**Comment by fennec622** [comment]
> You’ve hit max open files limit in your OS. Not an issue with homebridge-edomoticz.

Do you know how can I increase value ?
Thanks
