### ISSUE TITLE
No possibility to change thermostats by 0.5C steps in HomeKit

### ISSUE THREAD

**Issue by Kratax** [PatchworkBoy/homebridge-edomoticz#186]
Hi,
is there any setup possibility so as it would be possible to adjust thermostat temperature by 0.5C not 1.0C steps in HomeKit app?
Thanks a lot.
Lubos

**Comment by PatchworkBoy** [comment]
This isn’t a limitation of the plugin - it’s a limit of Apple’s native Home app. Some HomeKit apps support 0.5 steps via the UI, some don’t. Siri will set to 1 decimal place if asked (as will Alexa). Eve and Home+ allow it via their UI.
