### ISSUE TITLE
Sunscreen state reversed

### ISSUE THREAD

**Issue by goedh452** [PatchworkBoy/homebridge-edomoticz#188]
According to the little animated icon for sunscreens in the home app, a sunscreen is considered to be up when the status is closed and down when it is opened. The edomoticz plugin translates it exactly the other way around (which is understandable). I changed the WindowCovering code in such a way that when it s a percentage blind and isn't an inverted blind "level = 100 - level". This works for me.

Maybe it is possible to have edomoticz detect if it is a sunscreen (icon-based like the push buttons) and reserve the state translation.

I would be happy to share the altered code. It only partially works for now.

**Comment by PatchworkBoy** [comment]
Think this is all wrapped up now with Domoticz blind API updates and reflected changes here.
