### ISSUE TITLE
Fibaro roller shutter appear as switches

### ISSUE THREAD

**Issue by JonyBCN** [PatchworkBoy/homebridge-eDomoticz#19]
I have 6 Fibaro devices to control the blinds and appear as normal switches, not as blinds. In addition, I see normal blinds have a switchtypeVal different depending on whether you are normal blinds (SwitchTypeVal 3) or percentage (SwitchTypeVal 13).

{
   "ActTime" : 1463310917,
   "ServerTime" : "2016-05-15 13:15:17",
   "Sunrise" : "06:34",
   "Sunset" : "21:02",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Set Level: 48 %",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 1,
         "HardwareName" : "StickUSB",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00001B01",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-05-15 13:09:26",
         "Level" : 48,
         "LevelInt" : 48,
         "MaxDimLevel" : 100,
         "Name" : "Persiana dormitorio",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Set Level: 48 %",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds Percentage",
         "SwitchTypeVal" : 13,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "136"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by JonyBCN** [comment]
I also configured as a switch dummy shutter (switchtype 3) I also appears on Eve as a normal shutter switch instead.

{
   "ActTime" : 1463310954,
   "ServerTime" : "2016-05-15 13:15:54",
   "Sunrise" : "06:34",
   "Sunset" : "21:02",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Open",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 9,
         "HardwareName" : "Persiana terraza",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140E3",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-05-15 09:52:38",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Persiana terraza",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Open",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "blinds",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "148"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by PatchworkBoy** [comment]
Might have chance to look into this tomorrow... Stay tuned...!

**Comment by PatchworkBoy** [comment]
Replace the current index.js file for the plugin with the one from this repo... that should enable SwitchTypeVal 3 blinds - let me know if they operate as expected.

**Comment by JonyBCN** [comment]
Ready. Same result, the modules of the blind remain as "Light / switch".

**Comment by JonyBCN** [comment]
Hello again. after restarting and check I saw that the file had been saved as index.js.1 I deleted the index.js and I've replaced by raw, and got the following error:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[6/20/2016, 7:33:06 PM] ====================
[6/20/2016, 7:33:06 PM] ERROR LOADING PLUGIN homebridge-edomoticz:
[6/20/2016, 7:33:06 PM] SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:112:14)
    at Array.forEach (native)
[6/20/2016, 7:33:06 PM] ====================
[6/20/2016, 7:33:06 PM] No plugins found. See the README for information on installing plugins.
[6/20/2016, 7:33:06 PM] Loaded config.json with 0 accessories and 1 platforms.
[6/20/2016, 7:33:06 PM] ---
[6/20/2016, 7:33:06 PM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:106
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'eDomoticz' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:106:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:263:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:71:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)

**Comment by PatchworkBoy** [comment]
Sorry... wget the file again - have just fixed some ridiculously basic coding errors on my behalf!

**Comment by JonyBCN** [comment]
Well, there is progress. Fibaro controlled blinds still identified as lights, but a virtual blind previously appeared as light now appears as blind!

**Comment by PatchworkBoy** [comment]
OK - wget again - have just enabled SWTypeVal 13 which should sort the Fibaro ones - let me know what functionality does / doesn’t work as nothing to test with here so I’ve guessed a bit...!

**Comment by JonyBCN** [comment]
Wow. Just, WOW. It works perfectly. Thanks a lot, for a few days proves that such Siri behaves and will communicate any incident.

**Comment by PatchworkBoy** [comment]
If you wget the file one last time, any Total Consumption or Current Consumption Electric meters should now comply to the Elgato Eve sensortypes so that they are id’d correctly within Eve, along with support for Location sensors and Occupancy sensors. See: https://github.com/PatchworkBoy/homebridge-eDomoticz/commit/69ff8eb577b52c75a62986181524d15d7cba358f
