### ISSUE TITLE
Suggestion : make temp device unreachable when in red in domoticz 

### ISSUE THREAD

**Issue by macjl** [PatchworkBoy/homebridge-edomoticz#190]
Hello,
I think it would be nice to have a way to see in Home when a temp device is not updated anymore in Domoticz (red state). 
What about setting device as unreachable ? Or setting temperature to null (don’t know if this is allowed in HomeKit)
Regards

**Comment by PatchworkBoy** [comment]
Unreachable not a supported characteristic for the TemperatureSensor service (https://github.com/KhaosT/HAP-NodeJS/blob/52abfb360f8d65a7ec73ded685db5b8a58d0c2b7/src/lib/gen/HomeKit.ts#L4391). 

Will have a look at implementing StatusActive (https://github.com/KhaosT/HAP-NodeJS/blob/52abfb360f8d65a7ec73ded685db5b8a58d0c2b7/src/lib/gen/HomeKit.ts#L2281) or StatusFault (https://github.com/KhaosT/HAP-NodeJS/blob/52abfb360f8d65a7ec73ded685db5b8a58d0c2b7/src/lib/gen/HomeKit.ts#L2301)

**Comment by PatchworkBoy** [comment]
Remove .homebridge/accessories/cachedAccessories, update to v2.1.23, restart.

**Comment by macjl** [comment]
Thank you. I’ve updated to 2.1.28. I have these warning in log :
`[2/8/2020, 5:23:46 PM] [eDomoticz] Device: Température véranda (10)
HAP Warning: Characteristic 00000010-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000008A-0000-1000-8000-0026BB765291. Adding anyway. `

**Comment by PatchworkBoy** [comment]
Shouldn’t be an issue...
