### ISSUE TITLE
Device on/off state out of sync

### ISSUE THREAD

**Issue by sander1988** [PatchworkBoy/homebridge-edomoticz#193]
I'm currently working on the TV support (https://github.com/PatchworkBoy/homebridge-edomoticz/pull/189), so I'm using the master version.

The device on/off state get out of sync in this version.

Steps:
1. Turn on a device using HomeKit.
2. Disconnect phone from WiFi.
3. Turn off device using Domoticz.
4. Reconnect phone to WiFi.
5. Open the HomeKit app: the device is still shown as on (but it's real state is off).
6. It get's back into sync (the correct state) after re-launching (no need to kill the app) the Homekit app.

Anyone else experiencing this issue?

**Comment by PatchworkBoy** [comment]
Do you have an iPad or AppleTV set up on the network to act as a gateway for when you’re not on the same LAN?

**Comment by sander1988** [comment]
> Do you have an iPad or AppleTV set up on the network to act as a gateway for when you’re not on the same LAN?

No, just a PI 4 running HomeBridge in the same network as my iPhone.

**Comment by PatchworkBoy** [comment]
iPad or AppleTV 4th gen are required on local network to push changes to device on remote network. Part of HomeKit spec - nothing homebridge or plugin can do anything about.

Behaviour works as expected in accordance with HomeKit specs when these devices are present.
