### ISSUE TITLE
After add TV accessories delete 

### ISSUE THREAD

**Issue by fennec622** [PatchworkBoy/homebridge-edomoticz#194]
Hi

If i had a TV accessories it's work for 1 mins and after 1 mins TV accessories is deleted and a lot of accessories too

Tv accesories from another plugin or media player in domoticz 

It's the same

Do you know why ?

Thanks

**Comment by fennec622** [comment]
I make a homebridge with just TV

all is ok and after 1 mins TV delete and no log after

`  EventedHTTPServer Server listening on port 51830 +127ms
[27/01/2020 à 21:31:29] Homebridge is running on port 51830.
[27/01/2020 à 21:31:29] [eDomoticz] Device: Télévision (1507)
[27/01/2020 à 21:31:29] [eDomoticz] Successfully connected to MQTT broker.
  EventedHTTPServer [::ffff:10.0.0.65] New connection from client +11m
  EventedHTTPServer [::ffff:10.0.0.65] HTTP server listening on port 40885 +2ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /pair-setup +28ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-setup +2ms
  HAPServer [CD:12:3E:E5:DE:55] Pair step 1/5 +7ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +618ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /pair-setup +5s
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-setup +1ms
  HAPServer [CD:12:3E:E5:DE:55] Pair step 2/5 +3ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +545ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /pair-setup +116ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-setup +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair step 3/5 +1ms
  HAPServer [CD:12:3E:E5:DE:55] Pair step 4/5 +14ms
  HAPServer [CD:12:3E:E5:DE:55] Pair step 5/5 +59ms
  Accessory [Navez Television] Paired with client C168A3B8-0800-43C1-8E13-7EAAB7F2C970 +38ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:10.0.0.65] Client connection closed +212ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP connection was closed +5ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP server was closed +2ms
  EventedHTTPServer [::ffff:10.0.0.65] New connection from client +2ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP server listening on port 43373 +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /pair-verify +3ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 1/2 +2ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +49ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /pair-verify +129ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 2/2 +2ms
  HAPServer [CD:12:3E:E5:DE:55] Client C168A3B8-0800-43C1-8E13-7EAAB7F2C970 verification complete +45ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /accessories +118ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +7ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics +634ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +0ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":10,"ev":true},{"aid":2,"iid":11,"ev":true},{"aid":2,"iid":12,"ev":true},{"aid":2,"iid":13,"ev":true},{"aid":2,"iid":17,"ev":true},{"aid":2,"iid":18,"ev":true}] +4ms
  Accessory [Navez Television] Registering Characteristic "Active" for events +4ms
  Accessory [Navez Television] Registering Characteristic "Active Identifier" for events +2ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +0ms
  Accessory [Navez Television] Registering Characteristic "Sleep Discovery Mode" for events +1ms
  Accessory [Navez Television] Registering Characteristic "Mute" for events +1ms
  Accessory [Navez Television] Registering Characteristic "Volume Control Type" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics +143ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +1ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":10,"ev":true},{"aid":2,"iid":11,"ev":true},{"aid":2,"iid":12,"ev":true},{"aid":2,"iid":13,"ev":true},{"aid":2,"iid":17,"ev":true},{"aid":2,"iid":18,"ev":true}] +5ms
  Accessory [Navez Television] Registering Characteristic "Active" for events +1ms
  Accessory [Navez Television] Registering Characteristic "Active Identifier" for events +0ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +1ms
  Accessory [Navez Television] Registering Characteristic "Sleep Discovery Mode" for events +0ms
  Accessory [Navez Television] Registering Characteristic "Mute" for events +0ms
  Accessory [Navez Television] Registering Characteristic "Volume Control Type" for events +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /pairings +8ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pairings +1ms
  HAPServer [CD:12:3E:E5:DE:55] Adding pairing info for client +3ms
  Accessory [Navez Television] Paired with client AF8A6259-224C-4D8D-A5E6-02CE413D4969 +0ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +8ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics?id=2.10,2.11 +143ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /characteristics?id=2.10,2.11 +1ms
  Accessory [Navez Television] Getting value for Characteristic "Active" +6ms
  Accessory [Navez Television] Getting value for Characteristic "Active Identifier" +6ms
[27/01/2020 à 21:42:27] [eDomoticz] Data received for Télévision.
  Accessory [Navez Television] Got Characteristic "Active" value: 1 +22ms
  EventedHTTPServer [::ffff:10.0.0.65] Muting event '2.10' notification for this connection since it originated here. +4ms
[27/01/2020 à 21:42:27] [eDomoticz] Data received for Télévision.
  Accessory [Navez Television] Got Characteristic "Active Identifier" value: 0 +5ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /pairings +133ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pairings +0ms
  HAPServer [CD:12:3E:E5:DE:55] Adding pairing info for client +1ms
  Accessory [Navez Television] Paired with client 6048638B-339B-4EC3-8114-20BEB1DD46E0 +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +7ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics?id=2.10,2.11 +2s
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /characteristics?id=2.10,2.11 +0ms
  Accessory [Navez Television] Getting value for Characteristic "Active" +2ms
  Accessory [Navez Television] Got Characteristic "Active" value: 1 +1ms
  Accessory [Navez Television] Getting value for Characteristic "Active Identifier" +2ms
[27/01/2020 à 21:42:29] [eDomoticz] Data received for Télévision.
[27/01/2020 à 21:42:29] [eDomoticz] Data received for Télévision.
  Accessory [Navez Television] Got Characteristic "Active Identifier" value: 0 +19ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics +457ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +0ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":2,"value":true}] +1ms
  Accessory [Navez Television] Setting Characteristic "Identify" to value true +1ms
  Accessory [Télévision] Identification request +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:10.0.0.90] New connection from client +2s
  EventedHTTPServer [::ffff:10.0.0.90] HTTP server listening on port 45023 +1ms
  EventedHTTPServer [::ffff:10.0.0.90] HTTP request: /pair-verify +5ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 1/2 +2ms
  EventedHTTPServer [::ffff:10.0.0.90] HTTP Response is finished +117ms
  EventedHTTPServer [::ffff:10.0.0.41] New connection from client +1ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP server listening on port 46857 +1ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP request: /pair-verify +2ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP Response is finished +43ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP request: /pair-verify +16ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +1ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 2/2 +0ms
  HAPServer [CD:12:3E:E5:DE:55] Client C168A3B8-0800-43C1-8E13-7EAAB7F2C970 verification complete +37ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.94] New connection from client +8ms
  EventedHTTPServer [::ffff:10.0.0.94] HTTP server listening on port 43919 +0ms
  EventedHTTPServer [::ffff:10.0.0.94] HTTP request: /pair-verify +2ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:10.0.0.94] HTTP Response is finished +42ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP request: /accessories +2ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.94] HTTP request: /pair-verify +5ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 2/2 +1ms
  HAPServer [CD:12:3E:E5:DE:55] Client C168A3B8-0800-43C1-8E13-7EAAB7F2C970 verification complete +45ms
  EventedHTTPServer [::ffff:10.0.0.94] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.94] HTTP request: /accessories +2ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.0.94] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP request: /characteristics +22ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +0ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":12,"ev":true}] +1ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.94] HTTP request: /characteristics +41ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +0ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":12,"ev":true}] +1ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.94] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.90] HTTP request: /pair-verify +20ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 2/2 +1ms
  HAPServer [CD:12:3E:E5:DE:55] Client C168A3B8-0800-43C1-8E13-7EAAB7F2C970 verification complete +48ms
  EventedHTTPServer [::ffff:10.0.0.90] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.90] HTTP request: /accessories +6ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.0.90] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.90] HTTP request: /characteristics +47ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +1ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":12,"ev":true}] +0ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +1ms
  EventedHTTPServer [::ffff:10.0.0.90] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.86] New connection from client +2s
  EventedHTTPServer [::ffff:10.0.0.86] HTTP server listening on port 44305 +0ms
  EventedHTTPServer [::ffff:10.0.0.86] HTTP request: /pair-verify +4ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +1ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:10.0.0.86] HTTP Response is finished +81ms
  EventedHTTPServer [::ffff:10.0.0.86] HTTP request: /pair-verify +120ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 2/2 +1ms
  HAPServer [CD:12:3E:E5:DE:55] Client C168A3B8-0800-43C1-8E13-7EAAB7F2C970 verification complete +48ms
  EventedHTTPServer [::ffff:10.0.0.86] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.86] HTTP request: /accessories +6ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:10.0.0.86] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.86] HTTP request: /characteristics +261ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +0ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":12,"ev":true}] +0ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +1ms
  EventedHTTPServer [::ffff:10.0.0.86] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP request: /characteristics +11s
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +0ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":12,"ev":true}] +1ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +1ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP request: /characteristics +483ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +0ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":12,"ev":true}] +1ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.41] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.95] New connection from client +5s
  EventedHTTPServer [::ffff:10.0.0.95] HTTP server listening on port 42315 +1ms
  EventedHTTPServer [::ffff:10.0.0.95] HTTP request: /pair-verify +4ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 1/2 +2ms
  EventedHTTPServer [::ffff:10.0.0.95] HTTP Response is finished +72ms
  EventedHTTPServer [::ffff:10.0.0.95] HTTP request: /pair-verify +24ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 2/2 +1ms
  HAPServer [CD:12:3E:E5:DE:55] Client C168A3B8-0800-43C1-8E13-7EAAB7F2C970 verification complete +43ms
  EventedHTTPServer [::ffff:10.0.0.95] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.95] HTTP request: /accessories +5ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:10.0.0.95] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics?id=2.10,2.11 +7s
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /characteristics?id=2.10,2.11 +1ms
  Accessory [Navez Television] Getting value for Characteristic "Active" +1ms
  Accessory [Navez Television] Got Characteristic "Active" value: 1 +0ms
  Accessory [Navez Television] Getting value for Characteristic "Active Identifier" +2ms
[27/01/2020 à 21:42:59] [eDomoticz] Data received for Télévision.
[27/01/2020 à 21:42:59] [eDomoticz] Data received for Télévision.
  Accessory [Navez Television] Got Characteristic "Active Identifier" value: 0 +19ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics?id=2.10,2.11 +4s
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /characteristics?id=2.10,2.11 +1ms
  Accessory [Navez Television] Getting value for Characteristic "Active" +1ms
  Accessory [Navez Television] Got Characteristic "Active" value: 1 +1ms
  Accessory [Navez Television] Getting value for Characteristic "Active Identifier" +2ms
[27/01/2020 à 21:43:03] [eDomoticz] Data received for Télévision.
[27/01/2020 à 21:43:03] [eDomoticz] Data received for Télévision.
  Accessory [Navez Television] Got Characteristic "Active Identifier" value: 0 +18ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics +2s
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +1ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":2,"value":true}] +1ms
  Accessory [Navez Television] Setting Characteristic "Identify" to value true +0ms
  Accessory [Télévision] Identification request +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.98] New connection from client +5s
  EventedHTTPServer [::ffff:10.0.0.98] HTTP server listening on port 35413 +1ms
  EventedHTTPServer [::ffff:10.0.0.98] HTTP request: /pair-verify +4ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:10.0.0.98] HTTP Response is finished +72ms
  EventedHTTPServer [::ffff:10.0.0.98] HTTP request: /pair-verify +13ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 2/2 +1ms
  HAPServer [CD:12:3E:E5:DE:55] Client 6048638B-339B-4EC3-8114-20BEB1DD46E0 verification complete +44ms
  EventedHTTPServer [::ffff:10.0.0.98] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.98] HTTP request: /accessories +6ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.0.98] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.98] HTTP request: /characteristics +721ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +0ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":12,"ev":true}] +2ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.98] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics?id=2.10 +264ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /characteristics?id=2.10 +1ms
  Accessory [Navez Television] Getting value for Characteristic "Active" +1ms
  Accessory [Navez Television] Got Characteristic "Active" value: 1 +1ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +3ms
[27/01/2020 à 21:43:11] [eDomoticz] Data received for Télévision.
  EventedHTTPServer [::ffff:10.0.0.99] New connection from client +6s
  EventedHTTPServer [::ffff:10.0.0.99] HTTP server listening on port 38997 +1ms
  EventedHTTPServer [::ffff:10.0.0.99] HTTP request: /pair-verify +4ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 1/2 +2ms
  EventedHTTPServer [::ffff:10.0.0.99] HTTP Response is finished +91ms
  EventedHTTPServer [::ffff:10.0.0.99] HTTP request: /pair-verify +10ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +1ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 2/2 +1ms
  HAPServer [CD:12:3E:E5:DE:55] Client AF8A6259-224C-4D8D-A5E6-02CE413D4969 verification complete +43ms
  EventedHTTPServer [::ffff:10.0.0.99] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:10.0.0.99] HTTP request: /accessories +6ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.0.99] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.99] HTTP request: /characteristics +719ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +1ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":12,"ev":true}] +1ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.99] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP request: /characteristics?id=2.11 +4s
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /characteristics?id=2.11 +1ms
  Accessory [Navez Television] Getting value for Characteristic "Active Identifier" +1ms
[27/01/2020 à 21:43:22] [eDomoticz] Data received for Télévision.
  Accessory [Navez Television] Got Characteristic "Active Identifier" value: 0 +13ms
  EventedHTTPServer [::ffff:10.0.0.65] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.82] New connection from client +9s
  EventedHTTPServer [::ffff:10.0.0.82] HTTP server listening on port 43401 +0ms
  EventedHTTPServer [::ffff:10.0.0.82] HTTP request: /pair-verify +5ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +0ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:10.0.0.82] HTTP Response is finished +83ms
  EventedHTTPServer [::ffff:10.0.0.82] HTTP request: /pair-verify +14ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: POST /pair-verify +1ms
  HAPServer [CD:12:3E:E5:DE:55] Pair verify step 2/2 +1ms
  HAPServer [CD:12:3E:E5:DE:55] Client AF8A6259-224C-4D8D-A5E6-02CE413D4969 verification complete +51ms
  EventedHTTPServer [::ffff:10.0.0.82] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.82] HTTP request: /accessories +6ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.0.82] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.82] HTTP request: /characteristics +362ms
  HAPServer [CD:12:3E:E5:DE:55] HAP Request: PUT /characteristics +1ms
  Accessory [Navez Television] Processing characteristic set: [{"aid":2,"iid":12,"ev":true}] +0ms
  Accessory [Navez Television] Registering Characteristic "Configured Name" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.82] HTTP Response is finished +1ms`

**Comment by PatchworkBoy** [comment]
Author of the TV Accessory modification is investigating... see https://github.com/sander1988/homebridge-edomoticz/commit/eae34a1331f016ea48a7edabe454302aedc52434

Once he’s gotten it sorted I’ll merge in his pull request.

**Comment by sander1988** [comment]
I'm currently experiencing only one issue with the TV accessory (which I'm still looking into). I think we are talking about the same issue. @fennec622 - Please see screenshot below. Are you having the same issue? 

Please note that the option "PathC)" is an app I just installed on my TV. Now it shows correctly as a TV source, but it will break into a separate switch (the bug) within a couple of days.

![homebridge-tv-bug](https://user-images.githubusercontent.com/6334319/79150078-7189aa00-7dc8-11ea-8052-14d1f27e0d58.png)

**Comment by sander1988** [comment]
Additional note in case you have added the TV as favorite in HomeKit: You have to restart your device (in my case an iPhone) after this plugin has been updated in HomeBridge to get this bug resolved.
