### ISSUE TITLE
Update failing on RasPi - (Error 429 Too many Requests:is-windows@^1.0.1)

### ISSUE THREAD

**Issue by rjblake** [PatchworkBoy/homebridge-edomoticz#198]
When trying to update using sudo -E -n npm install homebridge-edomoticz@latest
, I keep getting the following error:

215 verbose stack Error: 429 Too Many Requests: is-windows@^1.0.1
215 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
215 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
215 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
215 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
215 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
215 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
215 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
215 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
215 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
215 verbose stack     at processImmediate (timers.js:632:19)
216 verbose cwd /home/pi
217 verbose Linux 4.19.66-v7+
218 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "homebridge-edomoticz@latest"
219 verbose node v11.3.0
220 verbose npm  v6.4.1
221 error code E429
222 error 429 Too Many Requests: is-windows@^1.0.1
223 verbose exit [ 1, true ]

**Comment by PatchworkBoy** [comment]
That looks like a problem with your installation of node / npm, not homebridge-eDomoticz

**Comment by PatchworkBoy** [comment]
Reading up, this would appear to be NPMJS rate-limiting your IP address for some reason. I’m afraid it’s nothing to do with this plugin, and nothing I have any influence over. You’ll probably find you get the same error when trying to update ANY npm package on your machine.

No such issues here updating with the usual `npm update -g homebridge-edomoticz` on MacOS, Raspbian, or Windows.

**Comment by PatchworkBoy** [comment]
Confirmed an issue with npmjs registry today. See: https://github.com/npm/cli/issues/837

**Comment by PatchworkBoy** [comment]
Twittersphere is gradually reporting that NPMJS is working again as Cloudflare push fixes out across the CDN network... see https://twitter.com/search?q=%40npmjs

**Comment by rjblake** [comment]
@PatchworkBoy - many thanks for the awesome follow up. My bad should have checked npm. See this has been a recurring problem. Will try again
