### ISSUE TITLE
PiMonitor

### ISSUE THREAD

**Issue by Salvora** [PatchworkBoy/homebridge-edomoticz#199]
Hello,
I've added PiMonitor to my domoticz server but it appears that it is not supported when ported to homebridge. 
https://github.com/Xorfor/Domoticz-PiMonitor-Plugin

Is there a way to support this at least CPU and GPU temps?

**Comment by PatchworkBoy** [comment]
Correct. No suitable HomeKit service types to map to. The Domoticz built-in MotherboardSensors hardware works fine for getting CPU load / temps etc, but the custom HomeKit accessories are only supported in third party HomeKit apps, not Apple’s own (ie: Eve, Home+ etc).
