### ISSUE TITLE
Counters, created as "General.Counter Incremental" in Domoticz, shown up as Contact

### ISSUE THREAD

**Issue by MPaul60** [PatchworkBoy/homebridge-eDomoticz#20]
I created virtual counters of type General, subtype Counter Incremental in Domoticz.
Those counters used as water counters and got updated by ESP Easy (software for ESP8266 controller). They shows up total and current values in Domoticz in correct way (at Utility) tab.
But in Eve I see them as of Contact type - so no value, just 'NO' status.
JSON output shown below:
{
   "ActTime" : 1464235958,
   "ServerTime" : "2016-05-26 07:12:38",
   "Sunrise" : "04:02",
   "Sunset" : "20:52",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "0.410 m3",
         "CounterToday" : "0.020 m3",
         "CustomImage" : 0,
         "Data" : "0.410 m3",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Cold water instant",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "82007",
         "LastUpdate" : "2016-05-26 07:12:38",
         "Name" : "Cold Incremental",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Counter Incremental",
         "SwitchTypeVal" : 2,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Used" : 1,
         "ValueQuantity" : "",
         "ValueUnits" : "",
         "XOffset" : "608",
         "YOffset" : "592",
         "idx" : "8"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "0.110 m3",
         "CounterToday" : "0.000 m3",
         "CustomImage" : 0,
         "Data" : "0.110 m3",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "Hot water instant",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "82008",
         "LastUpdate" : "2016-05-26 07:12:37",
         "Name" : "Hot Incremental",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Counter Incremental",
         "SwitchTypeVal" : 2,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Used" : 1,
         "ValueQuantity" : "",
         "ValueUnits" : "",
         "XOffset" : "664",
         "YOffset" : "592",
         "idx" : "9"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by PatchworkBoy** [comment]
Navigate to your home-edomoticz folder (usually /usr/local/lib/node_modules/homebridge-edomoticz) and wget the latest index.js from the github repo... restart, test and report back!

wget https://raw.githubusercontent.com/PatchworkBoy/homebridge-eDomoticz/master/index.js

**Comment by PatchworkBoy** [comment]
Closing as no response.
