### ISSUE TITLE
Domoticz/Homebridge on rgbw color change sets brightness to 99%

### ISSUE THREAD

**Issue by Geoffreyvliet** [PatchworkBoy/homebridge-edomoticz#200]
Currently I am using a Domoticz / Homebridge setup to switch lights, read sensors, etc. Unfortunately it was broken after Domoticz's 2020.1 update. Because of this I (unfortunately) had to install everything again. After resetting everything, I started a new ESP32-WS2813 LED project, controlling the WS2313 by ESP32 with MQTT. When I change the brightness with Homebridge (or another service using Homebridge), an MQTT message is sent in "Domoticz / in" which works. When I change a color I receive the correct color, but it always sets the brightness to 99% unintentionally. Anyone have any idea what this problem could be? I use a clean and up-to-date installation from Domoticz and Homebridge. Problem is with multiple Domoticz devices RGB / RGBW / RGBWW.

**Comment by Geoffreyvliet** [comment]
The problem is solved when changing mqtt to 0 in config.json. But when switching this value, EDomoticz devices on homebridge stop synchronize when changing devices on Domoticz (e.a. web interface). When I change the brightness with homebridge, the following line is being logged by Domoticz:
`MQTT: Topic: domoticz/in, Message: {"command":"switchlight","idx":13,"level":18,"switchcmd":"Set Level"}`

But when changing the color in Homebridge, the following is being logged: (see “bri” value)
`Status: setcolbrightnessvalue: ID: d, **bri: 99**, color: '{m: 1, RGB: ffffff, CWWW: 0000, CT: 0}'`

I think it’s using http(s) json when changing brightness using EDomoticz? Maybe a wrong value or parameter?

**Comment by PatchworkBoy** [comment]
Should be resolved by https://github.com/PatchworkBoy/homebridge-edomoticz/commit/a3f4493cfa26b33afb457c739f446d68f4e93082 once published to NPMjs (pending confirmation at https://github.com/PatchworkBoy/homebridge-edomoticz/issues/253)
