### ISSUE TITLE
remove accessories domoticz

### ISSUE THREAD

**Issue by remko2000** [PatchworkBoy/homebridge-edomoticz#201]
It has happened to me a few times now that when I remove domoticzdevices from homebridge suddenly all devices disappear from homebridge. In my case quite a lot and it takes a lot of effort to restore it again. I don't get it easily fixed anymore either. Simply remove the plugin and install again does not work. I also ask myself what is the best way to remove a device from a domoticzroom which sync with homebridge? I use a separate room (idx 2) in domoticz which I synchronize with homebridge so not all devices from domoticz are visible in homebridge.
Adding extra accessories to room 2 is fine but removing is a problem. Is there a ' how to'  with a good order to delete devices?

What i do: i remove an accessory from room 2 (in room plan) in domoticz and restart domoticz. Then I restart homebridge.

**Comment by PatchworkBoy** [comment]
Remove accessory, wait 10mins, plugin should automatically remove accessory from homebridge.
