### ISSUE TITLE
switch type are not light

### ISSUE THREAD

**Issue by KILL3R77** [PatchworkBoy/homebridge-edomoticz#208]
hi i need your help i use homebridge with domoticz plugin for controle 2 device in my room, "Lumiere" it's light and "Chauffage" it's radiator but in homebridge the device Model are Light/Switch
https://i.imgur.com/7prAbuF.png

this is not so bad but when i use homebridge gsh plugin for controle the device with my voice in google home
if i say "turn on light" google turn on the light but it turn on the radiator too i don't know where are my mistake can you help me

**Comment by PatchworkBoy** [comment]
This plugin has nothing to do with Google Home. It is for use with iOS and HomeKit. Talk to whoever writes homebridge-gsh
