### ISSUE TITLE
Thermostats showing set point value for current temperature

### ISSUE THREAD

**Issue by sbarriba** [PatchworkBoy/homebridge-edomoticz#21]
The Domoticz web interface is correctly reporting that the temperature in the rooms (from Honeywell evoHome). For example the Games Room is currently 22.2 with a Set Point of 5.

The relevant JSON block returned from "http://[domoticz-host]:8080/json.htm?type=devices&filter=all&used=true&order=Name" is shown below:

{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "22.2 C, (5.0 C), HeatingOff",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "EvoHome HGI80",
         "HardwareType" : "Evohome USB (for HGI/S80)",
         "HardwareTypeVal" : 39,
         "HaveTimeout" : false,
         "ID" : "",
         "LastUpdate" : "2016-06-16 15:10:00",
         "Name" : "Games Room Heating",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         **"SetPoint" : 5.0,**
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "HeatingOff",
         "SubType" : "Zone",
         **"Temp" : 22.20,**
         "Timers" : "false",
         "Type" : "Heating",
         "TypeImg" : "override_mini",
         "Unit" : 9,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "13"
      },

When fetching the thermostats via HomeKit apps HomeBridge reports in the log:
"[6/16/2016, 2:43:06 PM] [Domoticz] Data Received for Games Room Heating: 5"

So the plugin is retrieving the SetPoint value and not the Temp value.

I'm using:
"npm -v homebridge-edomoticz" reports "2.14.2"
Domoticz v3.5169

All running on a Raspberry Pi.

**Comment by PatchworkBoy** [comment]
Hmm - fixing this would break a lot of things for those running other thermostats or using the EvoHome-via-Script method in Domoticz (see https://github.com/PatchworkBoy/homebridge-eDomoticz/issues/13)

I’ll need to write in specific support for the EvoHome HGI80. Leave it with me.

**Comment by sbarriba** [comment]
Thanks for following up on this. I'm happy to test scenarios for you. I also have some Nest thermostat data I can pull into Domoticz if that helps.

**Comment by sbarriba** [comment]
If it helps I have a local branch working with Domoticz which has ensures we're using "s.Temp" within the getTemperature function (plus a fix for another issue I found which I'll log shortly). It sounds like that is a HGI80 specific fix though. I can push this to remote branch if that would help.

**Comment by PatchworkBoy** [comment]
Closing this as it’s a know issue (https://github.com/PatchworkBoy/homebridge-edomoticz/issues/63) between using prefab’d thermostats, and those creating there own thermostats from individual devices within domoticz. Too many different cases to have to code for which would make it far too clumsy for the end-user to have to set up.

Best case is simply to github-gist your particular code and reapply it whenever you update the main plugin.
