### ISSUE TITLE
2nd television device shows channels of 1st device 

### ISSUE THREAD

**Issue by sander1988** [PatchworkBoy/homebridge-edomoticz#214]
Today I added a 2nd television to my setup. I noticed an issue: The channels of the 2nd television device show the channels of the 1st television (on the iOS device) instead of it's own.

Please give me some time to create a fix. I will create a pull request when it's ready.

**Comment by sander1988** [comment]
Cause found: I assumed the hwType field contained an unique value (id) for each hardware device. But it seems to have always value 94 (https://github.com/domoticz/domoticz/blob/master/main/RFXNames.h#L191). I will look if it's possible to add the hwId field to the eDomoticzAccessory class and use that one.

**Comment by sander1988** [comment]
Issue resolved. A merge request has been created.

I also saw another issue where the TV source can get out of sync with Domoticz. It was cached by a cache bug. This is issue has also been resolved in this merge request.

**Comment by PatchworkBoy** [comment]
I believe all issues relating to TVs etc are now resolved and merged in... closing.
