### ISSUE TITLE
Move Television services to external accessory

### ISSUE THREAD

**Issue by sander1988** [PatchworkBoy/homebridge-edomoticz#217]
Due to HomeKit limitations you only have one television for each platform. Otherwise the (Apple TV) remote won't work with the 2nd TV. So by creating a special platform accessory for each TV we can get around this problem/limitation.

Please give me some time to make this change. I will create a pull request when it's ready.

**Comment by ProBatou** [comment]
It works great thanks @sander1988, I got my icon in the app. @PatchworkBoy is it possible to add to future releases

**Comment by PatchworkBoy** [comment]
In progress... using the built in `this.api.publishExternalAccessory` method rather than having to spool up a 2nd platform.
Also adds Category.TELEVISION as appropriate.  Just testing at the mo.

**Comment by PatchworkBoy** [comment]
Think I need to make some changes @sander1988… for both my TVs, the input selector is on a different hwId to the rest of the controls (ir blaster controlling a 4x4 hdmi matrix switch for the inputs, and a custom implementation of Kodi Media Server protocol for the rest). Fudged round it by pulling device.description and passing thru as this.descript, then adding same string to the Domoticz devices that should be combined into one accessory.

**Comment by PatchworkBoy** [comment]
Think all these are resolved now. Open new issue if not after installing 2.1.40 from NPM...
