### ISSUE TITLE
No accessories showing up in HMCatalog or Eve.app

### ISSUE THREAD

**Issue by tanuva** [PatchworkBoy/homebridge-eDomoticz#22]
Hello,

I'm just taking my first steps with homebridge as well as homebridge-edomoticz. I have Domoticz 3.4834 running on a Raspberry Pi B 512MB. It has the zwave.me daughter board attached and happily controls a Fibaro RGBW controller. So far, so good.

Now I have pulled homebridge from git, built it and installed homebridge-edomoticz via npm. Configuration:
````
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:21:3E:E4:DE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Configuration file for Domoticz platform.",
    "platforms": [
        {
            "platform": "Domoticz",
            "name": "Domoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "ssl": 0,
            "roomid": 2
        }
    ],
    "accessories": []
}
````

````
➜  homebridge git:(master) ✗ ./bin/homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[Thu Jun 16 2016 19:40:10 GMT+0200 (CEST)] Loaded plugin: homebridge-edomoticz
[Thu Jun 16 2016 19:40:10 GMT+0200 (CEST)] Registering accessory 'homebridge-edomoticz.eDomoticz'
[Thu Jun 16 2016 19:40:10 GMT+0200 (CEST)] Registering platform 'homebridge-edomoticz.eDomoticz'
[Thu Jun 16 2016 19:40:10 GMT+0200 (CEST)] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[Thu Jun 16 2016 19:40:10 GMT+0200 (CEST)] Homebridge is running on port 51826.
````

This looks as expected to me. I also paired successfully using Eve.app on one device, the "home" shows up in HMCatalog.app on another device. Its just... no RGBW controller (components) showing up anywhere.
Running homebridge with `DEBUG=*` revealed some HTTP queries being processed but I could spot no errors. I can paste the output of Eve.app querying something of course if that helps.

Do you have any idea where I could get more information from or what I might have missed?

**Comment by PatchworkBoy** [comment]
There's no RGBW support in the plugin at this time. This should be added within the next 6 weeks.

**Comment by tanuva** [comment]
Woah, that was quick! :)
I almost suspected that this might be the cause after reading the issue and forum threads about RGB. But one thing I don't understand yet: in Domoticz, the Fibaro controller appears as surprisingly many separate devices, the dimmer I mainly use having the type `SwitchTypeVal: 7`. That id is marked as being supported by homebridge. So I guess an RGB device is still different from an ordinary dimmer?

Anyway, I'll watch out for updates then. Thanks!

**Comment by xTheRamon** [comment]
I think this issue can be closed now since the plugin now fully supports RGBW for lamps with `SwitchTypeVal: 7`!

**Comment by PatchworkBoy** [comment]
Righty - cheers Ramon!
