### ISSUE TITLE
Contact sensor doesn't update in Homebridge or Homekit

### ISSUE THREAD

**Issue by jameschiffey** [PatchworkBoy/homebridge-edomoticz#222]
I've just added a Z-Wave contact sensor to my setup. 

When the sensor opens/closes, it updates correctly in Domoticz.

However, it doesn't update in Homekit (I use the iOS Home app) unless I re-open the app. It also doesn't update in the Homebridge UI unless I hit F5 on the accessories screen.

When I hit F5 on the accessories screen it will also update in the iOS Home app.

All of this makes me think that the contact sensor update is not being pushed to Homebridge correctly. Only when Homebridge is forced to pull the current status of all devices (with F5 or an app re-open) does it update.

This _could_ be an issue with Homebridge itself, but the plugin seems like a better place to start.

I don't use MQTT, in case that's relevant.

**Comment by PatchworkBoy** [comment]
Sounds like you haven’t configured the plugin for MQTT... which enables real-time updates instead of pull-only updates.

**Comment by jameschiffey** [comment]
You're quite right, I haven't.

I just tried turning a light on/off in Domoticz, and it also doesn't update live in the Home app. Somehow I never noticed that before!

How do pull updates work then? Does it always require a "trigger" like opening/restarting the Home app?

**Comment by PatchworkBoy** [comment]
Pull down to refresh usually. If you want real-time updates install and setup MQTT as per README.md and you’ll get instant updates in both directions.

**Comment by PatchworkBoy** [comment]
See ‘installing Mosquitto’ in Domoticz wiki, get it all setup in Domoticz, then enable in plugin.

https://www.domoticz.com/wiki/MQTT

**Comment by jameschiffey** [comment]
Thank you, I'll try that!

Also, thanks for all your hard work on this plugin - it's very much appreciated.
