### ISSUE TITLE
Blinds Percentage, 1. without MQTT ➡️ inverted status 2. others problems with MQTT

### ISSUE THREAD

**Issue by jyjourdain** [PatchworkBoy/homebridge-edomoticz#223]
Hi,

I have problems with a « Blinds Percentage » roller shutter. All is fine if I set it as « Blinds » only.

Without MQTT installed from Domoticz side, status appears inverted in Apple Home (« open » if the shutter is closed for exemple).

I made a quick test with MQTT activated: no more inversion but the roller shutter value seems out of sync ...

I had a look in code (and was not able to understand everything 😉). But, if I look domoticz_accessory.js / Line 1303 :
this.cachedValues[Characteristic.Brightness.UUID] = position;

Shouldn't we replace Brightness with Position?

I know you don't have a roller shutter available, if I can help with testing ...

Thank you!

**Comment by PatchworkBoy** [comment]
On the characteristic: Brightness is essentially a generic handler for _anything_ that uses a % slider iirc. 

Will take a look...

**Comment by jyjourdain** [comment]
Hi,

I made my comment because I saw that, line 264 : 
   var cachedValue = (this.isPercentageBlind || this.isInvertedBlind) ? this.cachedValues[Characteristic.CurrentPosition.UUID] : this.cachedValues[Characteristic.Brightness.UUID];

Thanks for your help!

**Comment by PatchworkBoy** [comment]
I believe resolved in 2.1.40

**Comment by jyjourdain** [comment]
Thanks! I’ll test next week.

**Comment by jyjourdain** [comment]
Hi @PatchworkBoy , that worked! Thanks again. I wish you an happy new year.
