### ISSUE TITLE
Support for the Selector switch type

### ISSUE THREAD

**Issue by etampes** [PatchworkBoy/homebridge-edomoticz#224]
Hello,

I've been experimenting with this plugin and wonder if the 'Selector' switch type will be supported soon. That would be super handy for my Domoticz Virtual Smart Thermostat installation

**Comment by Seidel76** [comment]
Yes please !!

**Comment by TheZeroBeast** [comment]
I would also much appreciate this.

**Comment by PatchworkBoy** [comment]
Not possible. SelectorSwitch maps thru to Apple's push button service for single / dbl / triple click states. It's also used as part of the TV device type for input selection. IE: Apple won't allow it to work how you'd want / expect it to work.

"Correct" method would be to install homebridge-web-thermostat, and knock up a node-red flow to hook that up to whatever virtual set points and switches and temp sensors you have in Domoticz.
