### ISSUE TITLE
Exact same device types get interpreted as different device types

### ISSUE THREAD

**Issue by jotheman0303** [PatchworkBoy/homebridge-edomoticz#229]
I have a lot of Klik aan Klik uit switches at home. They sometimes get interpreted by HomeBridge as actual Lights, whereas sometimes they get interpreted as Switches. I am currently running into the fact that, because they are sometimes synced as Lights, I automatically turn on something that's not an actual light, along with all the lights in a room. It would be really great if this can be resolved.
I looked at the JSON from Domoticz in which the type is noted but do not a difference at all, they look exactly alike (other than the name and IDX of course). Would be great to have the ability to choose the type in HomeBridge, but I am not sure whether that is difficult to achieve...

**Comment by goedh452** [comment]
In my experience this can be due to the icon you have set in Domoticz. When the icon is set to "Generic" (Red push button) it is interpreted as a switch in homebridge. When the default icon is used (a light bulb), homebridge interprets it as a light.
