### ISSUE TITLE
Somfy RFY Domoticz blinds

### ISSUE THREAD

**Issue by Bob2345de** [PatchworkBoy/homebridge-edomoticz#23]
Hi there! got edomoticz/Homebridge working. Many thanks for your great work!

One issue that I have is that all of my Somfy RFY domoitcz blinds (shutters) are being loading into eve as power switches.

Are you  able to change this?

By the way in the eve accessory info they are listed as Manufacturer: edomoitcz, Model:RFY

If I can be of any assitance with please let me know.

Thanks in advance!

**Comment by PatchworkBoy** [comment]
Overwrite the index.js file installed via npm (presuming that’s how you installed it) with the one from the GitHub repo, and this should enable blind support.

**Comment by Bob2345de** [comment]
Thank you!

I did an update via NPM (sudo npm update homebridge-edomoticz -g) yesterdy, not being familiar with NPM, I'm wondering if that should have pulled the updated file?
Thanks again

**Comment by PatchworkBoy** [comment]
Nope... I haven’t published the change to NPM, only GitHub, as it’s still experimental.

Should be a case of (assuming edomoticz is at /usr/local/lib/node_modules/homebridge-edomoticz): 

cd /usr/local/lib/node_modules/homebridge-edomoticz 
sudo wget https://raw.githubusercontent.com/PatchworkBoy/homebridge-eDomoticz/master/index.js

**Comment by Bob2345de** [comment]
great. will do that and give you you feedback.
Thanks you.

**Comment by Bob2345de** [comment]
Tried the suggestion which unfortunately failed details below.

My install from the most recent domoticz SD image, had the node_modules directory is under use/lib so I made that change. Also the wget did.NTSC overwrite the index.J's file but rather added a new index.js .1. Which I renamed and did a chown pi:pi index.js to reflect ownership of the original file. Despite that, there seems to be an issue with the file and my install:
pi@raspberrypi:~$ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=no
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=no
[6/21/2016, 7:52:24 PM] ====================
[6/21/2016, 7:52:24 PM] ERROR LOADING PLUGIN homebridge-edomoticz:
[6/21/2016, 7:52:24 PM] SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:112:14)
    at Array.forEach (native)
[6/21/2016, 7:52:24 PM] ====================
[6/21/2016, 7:52:24 PM] No plugins found. See the README for information on installing plu
[6/21/2016, 7:52:24 PM] Loaded config.json with 0 accessories and 1 platforms.

Revering to the old index.js does work.

Do I need to replace other files to newer versions?

Thanks for your help!

**Comment by PatchworkBoy** [comment]
Nope, it'll just be a mistake in code somewhere. Will have a look shortly...

M

**Comment by PatchworkBoy** [comment]
K - wget the file again... have just fixed the coding errors I’d made...!

**Comment by Bob2345de** [comment]
Thanks for the changes. The blinds do now appear in eve as window coverings.

One issue, and perhaps this is an eve app limitation, is that the blinds are listed as % open devices while they are only open close stop devices and to open or close via app one needs to tap the % open or closed button 100 times to reduce or increase to 0% (100%) to initiate the open or close. 

Also with the old index file, a custom cistern water level device which I've put together using mysensors, which is listed in domoticz as a general distance device, and which previously correctly showed a value in cm in eve, is now seen as a power usage device.

Thanks for your support!

**Comment by Bob2345de** [comment]
Additional info, domoticz presents these somfy blinds as follows:
{
         "IsDimmer" : false,
         "Name" : "Kids Blinds",
         "SubType" : "RFY",
         "Type" : "RFY",
         "idx" : "244"
      },

**Comment by xTheRamon** [comment]
HomeKit only supports blinds as a percentage value. There is simply no 'fully close' or 'fully open' functionality.
The Eve app itself has to create a custom button that sets the blind on 100% directly, instead of adding one percent at a time. Unfortunately the Eve app does not incorporate such a button. HomeKit in iOS 10 does this perfectly though.
Upon tapping a blind icon, it switches from 100% to 0% and back. Dragging will set a percentage.

I'm afraid we cannot do anything.

**Comment by PatchworkBoy** [comment]
Aye - only 'solution' would be to revert them back to a power switch... but to implement adds a level of complexity to config.json that needs some planning & documentation, and would be part of a larger rewrite.

@xTheRamon - eg: ability to arrays of IDX values to override from one switchtypeval to another, and ability to 'merge' two IDX outputs into one HomeKit device (merge a domoticz setpoint and a domoticz temp sensor to make a complete HomeKit thermostat).
