### ISSUE TITLE
Way to suppress "excluded via config array" messages in log?

### ISSUE THREAD

**Issue by mvzut** [PatchworkBoy/homebridge-edomoticz#231]
Hi,

I have a relatively large Domoticz installation (more than 150 used devices). Many of them cannot be used (yet) in Apple Homekit or GoogleSmart Home, so I excluded around 50 devices in the eDomoticz plugin. This also helps me stay under the 150 device limit.

In the Homebridge log, the exclusion is nicely confirmed. However, I noticed that this is repeated every 10 minutes. Why is this? It is making it much more difficult to spot important messages in the log, since it is mostly filled with these exclusions confirmations. Is there a way to avoid these repeats? Perhaps it could be made into a configuration option?

**Comment by Reinvented0** [comment]
That certainly would be nice, have the same problem. Any progress?

**Comment by Reinvented0** [comment]
You can edit the index.js and remove or cancel the section below.

if (!(excludedDevices.indexOf(device.idx) <= -1)) {
                    exclude = !0;
                    this.forceLog(device.Name + ' (idx:' + device.idx + ') excluded via config array');
                    //continue;
                }
