### ISSUE TITLE
Status sync issue

### ISSUE THREAD

**Issue by Chema-ES** [PatchworkBoy/homebridge-edomoticz#233]
- State changes via homekit app/homepod updates (and near without lag)  state in Domoticz 
- State changes in Domoticz with open homekit/homebridge  are not updated. Reopen homekit or reload homebridge will resolve issue.

Any suggestion?

**Comment by PatchworkBoy** [comment]
Check your MQTT setup, monitor out channel with a client. Verify updates are being sent in real-time.

**Comment by EddyGitH** [comment]
Hi, I have the same issue, in config.json i have set MQTT set to 1 (was true but no change).
Domoticz is working properly, but homebridge is lagging multiple seconds.

**Comment by EddyGitH** [comment]
Just found out I have an error in the homebridge log: 
Starting to advertise 'Homebridge 4264 E03C' using bonjour-hap backend!
[3/7/2021, 10:18:38 PM] Homebridge v1.3.2 (Homebridge 4264) is running on port 52766.
[3/7/2021, 10:18:38 PM] [Domoticz] There was an error while getting the MQTT Hardware Device from Domoticz.
Please verify that you have added the MQTT Hardware Device and that the hardware device is enabled.

So it is not connecting over MQTT, then I read it gets the MQTT data from Domoticz were I had 127.0.0.1 as for the MQTT server, but changing that to the real IP didn't help.  UserID / PW issues i do not see, anyone know how to debug this?

**Comment by PatchworkBoy** [comment]
Have you actually added the MQTT Hardware device in Domoticz Hardware Settings?

**Comment by EddyGitH** [comment]
Yes i have a zigbee2mqtt hardware in there, and that is working properly since domoticz has quick status updates.
i tried the advanced MQTT settings, but no luck there :(   :
   {
            "name": "Domoticz",
            "server": "192.168.2.39",
            "port": 8081,
            "roomid": 0,
            "mqtt": {
                "host": "192.168.2.39",
                "port": 1883,
                "topic": "zigbee2mqtt",
                "username": "XXXXXX",
                "password": "XXXXXXX"
            },

**Comment by EddyGitH** [comment]
Or do i need to add my Mosquitto server in there?

**Comment by PatchworkBoy** [comment]
Never heard of it. Expects the Domoticz native  mqtt client & topic structure. Anything else you’ll have to decide the mqtt libs in edomoticz source to work with whatever your specific mqtt setup is.

**Comment by EddyGitH** [comment]
Your message urged me to add the specific MQTT type in Domoticz. 
Set MQTT config back to the simple 'true' option and it is connected now and homebridge is running fast!

Thanks!
