### ISSUE TITLE
Consumption warning in homebridge

### ISSUE THREAD

**Issue by sylvainbizeau** [PatchworkBoy/homebridge-edomoticz#235]
Hello,

I have this warning in homebridge log every 15 minutes (approximatively)
> [homebridge-edomoticz] This plugin generated a warning from the characteristic 'Consumption': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

Otherwise the plugin works fine.
I created a virtual sensor named Consumption but it didn't change anything. 

Did i miss an option somewhere?

I take this opportunity to thank you for your plugin which is really very good.

**Comment by PatchworkBoy** [comment]
Whatever your power meter is, it isn't providing a current consumption value as expected/required. Would need to see the full Domoticz JSON API output for the device.
