### ISSUE TITLE
MQTT Blinds status inverted (open/closed) 

### ISSUE THREAD

**Issue by Olivier6767** [PatchworkBoy/homebridge-edomoticz#240]
Domoticz Release: 2021.1.13842
Platform: Linux x64

I have several Domoticz switches controlling my blinds. They are set as Blinds - Percentage Inverted
I use Homebirdge with the eDomoticz plugin using MQTT so I can control my blinds from the Apple Home App on iOS devices.

Everything was working fine until I upgraded to release 13842 (I was previously running 13666).
Since the upgrade the status of the blinds appear inverted on the Apple Home app.
When they are closed in Domoticz, they are open in Home, and vice versa.
If they are partially open (50% for example), this shows up correctly in the Home App.
This has work ed since several years. Some update between release 13666 and 13842 has changed this behaviour.

For testing, I tried changing the switch type to Blinds - Percentage (not inverted), but the problem is the same. The status in the Home App is inverted compared to the status in Domoticz.

More details in this thread (Domoticz support): [https://github.com/domoticz/domoticz/issues/5017](https://github.com/domoticz/domoticz/issues/5017)

This is linked to a change in the way Domoticz handles dimmers (sliders). 

Previously the slider values in Domoticz were:
```
Open: 100
Closed: 0
```
This has now changed to :
```
Open: 0
Closed: 100
```

screenshots: [https://github.com/domoticz/domoticz/issues/5017#issuecomment-964367600](https://github.com/domoticz/domoticz/issues/5017#issuecomment-964367600)

I have tried to find how to adjust the code in domoticz_accessory.js but I can't seem to find where to make a change.

Is there a way to adjust the code so that the blinds work correctly again with the current (and future releases of Domoticz)?

**Comment by gizmocuz** [comment]
This was a bug in Domoticz that has been there for a long time and recently has been solved/corrected.

**Comment by Olivier6767** [comment]
Here is a recap of the issue with the Blinds status in the iOS Home App following the change in Domoticz. 
It looks like the fix affected only the type: Blinds Percentage Inverted. 

Using Blinds Percentage Inverted was the only combination that was showing the correct status of the blinds in the Home App prior to to the change.

![Blinds-Status](https://user-images.githubusercontent.com/28684355/141164435-efc5aae8-f3e1-49cf-a193-59720454cf41.png)

We will need a change to the Homebridge-eDomoticz plugin to get this working again.

**Comment by gizmocuz** [comment]
There are also two new types: Blind Percentage with Stop and inverted
