### ISSUE TITLE
synchronizeAccessories on demand

### ISSUE THREAD

**Issue by vespino** [PatchworkBoy/homebridge-eDomoticz#245]
I have been running homebridge for quite some time now, works great for me. Using my Unifi network I have set up presence detection to allow lights etc. to automatically switch based on presence. If I leave the house for a short amount of time (less than 10 min) the "synchronizeAccessories" hasn't run yet, so homebridge is not able to switch since it's in the old state. I have found homebridge has an API and I was wondering if it's possible to force synchronizeAccessories using an API endpoint so I can include this in my presence detection to always have homebridge up-to-date.

**Comment by PatchworkBoy** [comment]
SyncAccessories pulls in / removes new / removed devices from Domoticz.

If you have MQTT successfully configured, everything should update in real-time.

**Comment by vespino** [comment]
Thanks. Then I think the problem might be Google Assistant doesn't update fast enough. I will look into that.
