### ISSUE TITLE
No switch status update in homekit. Siri does not know the switch status (state) in Domoticz

### ISSUE THREAD

**Issue by huongminh** [PatchworkBoy/homebridge-eDomoticz#25]
Hi,

I have a couple of virtual switches in domoticz which can be turned on and off by Siri thanks to homebridge-domoticz plugin. Thank you for your great job!

However, Siri cannot tell the state of the switches when I want to check by asking her: what is the status of my Ceiling Fan (name of my domoticz switch)?

The same question gets correct answer by Siri for other devices over homebridge such as my Lifx bulbs (namely Lamp). Siri would say: your Lamp is on (or off).

The same question also works for my blinds in domoticz, as I just updated the index.js as per instruction in this forum (And all my blinds turned from Switches to Positions in my Eve homekit app). Siri would say: your Living-room Curtain (name of my blind) is set at 100% (or 0%). Previously, when the blinds were treated by homekit as switches, Siri did not understand the question.

If I try to refresh (pull down) the Eve homekit application I can see the state of my domoticz virtual switches still get updated in the terminal command line running homebridge. It seem the switch state is updated in homebridge like my Lifx bulbs , and Blinds, but just Siri does not recognize it. Please help!

**Comment by huongminh** [comment]
Just to clarify the issue more. My Lifx bulbs are not linked to homebridge with domoticz-hombridge plugin but I connect them to homekit via the Lifx-Lan-homebridge plugin. I mean It seems to me that the homebridge is working well with Siri homekit on the status check and the domoticz-homebridge plugin also works well with Siri homekit on the status check, at least with the Blinds. It might be only something wrong with the domoticz-plugin part with switches.

**Comment by PatchworkBoy** [comment]
Domoticz doesn’t distinguish fans from switches (i.e.: there is no fan Type / SubType within Domoticz) therefore it doesn’t use the correct HomeKit Service Type, as HomeKit has a specific service type for Fans. As soon as you mention the word Fan to Siri, it automatically looks for Service.fan devices, of which there are none as Domoticz is only identifying the Fan as a Switch.

Replace your current index.js with https://raw.githubusercontent.com/PatchworkBoy/homebridge-eDomoticz/master/index.js (which I’ve just updated), and any Domoticz devices detected as a switch with the word “Fan” in the title will now be initialised within HomeKit using Service.Fan, and then querying the status should work.

**Comment by huongminh** [comment]
Thank you for your very quick feedback and update! Just tried your instructions but it didn't work. Siri still says: "Sorry! I wasn't able to find any devices this time" to answer my question: what is the status of the Ceiling Fan. Could it be a different situation than you said? since I have other virtual switches which control lights/lamps in Domoticz as well. I name them Spotlight, Hanging Light (no "Fan" word and they are actually Wemo-like sockets connected to the light) but Siri also gives the same answer for status like the Ceiling Fan.

**Comment by PatchworkBoy** [comment]
*shrug* Out of ideas on that one... it works on all of my devices, so I can’t replicate the issue to fix it.

**Comment by huongminh** [comment]
Thank you for your update. It might be an issue with Homekit rather than the plugin I guess. Now suddently all my switch devices in Domoticz work as you wrote when I try them but ridiculously my Temp+Hum Sensors now have a similar issue with Siri. Previously Siri would answer when I ask: "What is the temperature in my Living Room?" or "What is the humidity in my Living Room?" but now Siri gives answer only to the temp question, not the humidity question anymore. She would say: "That is not supported". During the last week, I had a power failure that shutdown my Domoticz/Homebridge server (Pi3). I also add support to Milight bulbs in the Homebridge config.json. Not sure if any of these things were the cause that enable Siri to read my switch status but also diable her to give answer to my humidity question. I use serveral DHT22 Temp and Hum sensors on ESP8266 and they all work well in Domoticz and Homekit previously. Now everything is still correct in the EVE homekit app, just Siri refuses to read the humidity level. Do you have any ideas what I should do? Thank you in advance!

**Comment by PatchworkBoy** [comment]
Nope. Nothing has changed in the plugin. Not an issue with the plugin. Closing.
