### ISSUE TITLE
Domoticz Version 2022.1.14552 2022-10-10

### ISSUE THREAD

**Issue by inext-gr** [PatchworkBoy/homebridge-edomoticz#250]
Hi, unfortunately in this version of domoticz the inverted blinds with percentage have been removed.
Kindly we can solve the problem somehow. Thank you

**Comment by daliquidalien** [comment]
It seem that the parameters sent to DZvents have changes as well from on/off to open/close. Not clear if 0/100 for percentage are still supported. On the Domoticz forum, they say the new logic should be implemented in the plugins. My $0.02.

**Comment by vespino** [comment]
I solved my issue this way: https://github.com/domoticz/domoticz/issues/5371#issuecomment-1282290529

**Comment by ksacca** [comment]
I posted a comment on the domoticz forum with a possible solution (currently for testing purposes). Feel free to check https://domoticz.com/forum/viewtopic.php?p=293567#p293567 and test for issues. As long as it’s simple, I might be able to fix remaining issues.

**Comment by odelma** [comment]
Can you make a pull request for this change? I think it works well 👍

**Comment by niko44** [comment]
thanks a lot ! It works well now.
Yes make a pull request and pray for the next version XD

**Comment by Git-Bruno** [comment]
Thanks a lot. My blinds are now moving the correct way with you change installed on top of homebridge-edomoticz v2.1.38.

**Comment by ksacca** [comment]
> thanks a lot ! It works well now. Yes make a pull request and pray for the next version XD

I created a pull request. Let's hope it will be merged.

**Comment by PatchworkBoy** [comment]
Merged, version incremented, and pushed to NPM. Thanks!
