### ISSUE TITLE
Add support for RGBWZ

### ISSUE THREAD

**Issue by Olivier6767** [PatchworkBoy/homebridge-edomoticz#254]
Hello,
Could you please add support for device type RGBWZ ?

I tested by editing the domoticz_accessory.js file and adding this test to the line 1788:
`  || this.subType == "RGBWZ" `

The device then works fine in Homekit.

**Comment by PatchworkBoy** [comment]
Done - https://github.com/PatchworkBoy/homebridge-edomoticz/commit/b64c52f0992606cb66a690da572570e23731e99a
