### ISSUE TITLE
Domoticz 2023.1 - Problem with the plugin

### ISSUE THREAD

**Issue by harrykausl** [PatchworkBoy/homebridge-edomoticz#258]
I switched to Domoticz 2023.1 and got the following problem:
homebridge-edomoticz] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' didn't respond at all! See https://git.io/JtMGR for more info.
Homebridge doesn't work in this constellation.

When going back to 2022.2 (another SD-Card) all works.

**Comment by harrykausl** [comment]
Solved!. I had to insert 127.0.0.* to the list of secure networks.

**Comment by baseship** [comment]
For me it's not solved.

[Domoticz] There was a problem connecting to Domoticz. (HTTP Status code 401)

@harrykausl can you tell me your domoticz & homebridge setup?

**Comment by PatchworkBoy** [comment]
See https://github.com/PatchworkBoy/homebridge-edomoticz/issues/257

**Comment by baseship** [comment]
Thanks! That's it
