### ISSUE TITLE
Devices not showing in home bridge

### ISSUE THREAD

**Issue by Kydix** [PatchworkBoy/homebridge-edomoticz#259]
Hello, 

I've successfully add my RFXcom into Domotics and I can control my blinds. I have set up Edomotics on homebridge but I have no accessories showing up. 

 [Domoticz] Loaded homebridge-edomoticz v2.1.46 child bridge successfully
[08/05/2023, 18:12:38] Loaded 0 cached accessories from cachedAccessories.0E9F61AA464E.

I've set room ID to 0 (I have only 1 accessories in domoticz) 

Any idea ?

**Comment by PatchworkBoy** [comment]
You look to be running it as a child bridge? Turn that off, restart.
