### ISSUE TITLE
[WebServer] Deprecated RType

### ISSUE THREAD

**Issue by pierrotori** [PatchworkBoy/homebridge-edomoticz#269]
Since the last version 2023.2 from domoticz 
i detected  and i supposed when i start only the docker hombridge i have this error in my log
`2023-09-05 12:59:43.596 [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command! (192.168.0.6)`

could you check if you use the syntax /json.htm?type=devices&rid=IDX in the plugin Homebridge Edomoticz ?
see the explication in the wiki : https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Retrieve_status_of_specific_device

**Comment by DewGew** [comment]
same as #265

**Comment by PatchworkBoy** [comment]
Merges now published up to NPM.
