### ISSUE TITLE
Error update 2.1.47

### ISSUE THREAD

**Issue by cyberfilou** [PatchworkBoy/homebridge-edomoticz#271]
i have problem et edomiticz not start
i have this error
`10/14/2023, 4:59:39 PM] [Domoticz] There was an error while getting the MQTT Hardware Device from Domoticz.
Please verify that you have added the MQTT Hardware Device and that the hardware device is enabled.`

With the version 2.1.46, no problem.

i'm return to the version 2.1.46

**Comment by PatchworkBoy** [comment]
MQTT working fine here with 2.1.47…

**Comment by cyberfilou** [comment]
Hello

i use domoticz version 
<img width="375" alt="image" src="https://github.com/PatchworkBoy/homebridge-edomoticz/assets/11319401/d2241c1e-2d4c-4dea-87cc-7cfb9504675d">
And with 2.1.46 e domoticz i have no problem

**Comment by cyberfilou** [comment]
Ok i have found the problem
Domoticz are not update.
I have update Domoticz and Edomoticz, and the are ok
I close the Issues
