### ISSUE TITLE
Domoticz Motion Sensor not working in Homebridge

### ISSUE THREAD

**Issue by vgr28** [PatchworkBoy/homebridge-edomoticz#272]
Domoticz 2023.2,

Sensor will be found, but the switch status will not be changend in Homebridge according to the domoticz status.

Maybe someone can support......

**Comment by PatchworkBoy** [comment]
Make sure you’ve got MQTT configured and running correctly…

**Comment by PatchworkBoy** [comment]
Are you seeing… 
![IMG_4223](https://github.com/PatchworkBoy/homebridge-edomoticz/assets/3514253/250d6fce-7cc5-4924-8bb0-cde86dd9fd9d)
…in Homebridge output / log?

**Comment by vgr28** [comment]
Now it's running. Problem, I did not do the configuration based with the config. page, only with the config. example. 

"mqttenable": 1,
            "mqttserver": "127.0.0.1",
            "mqttport": "1883",
            "mqttauth": 0,
            "mqttuser": "",
            "mqttpass": ""

only with this it's not running. If I do the config by the config. page than "mqtt": true will be added and it's running.

Maybe the config example should be updated.

**Comment by PatchworkBoy** [comment]
Which config example are you looking at where…?

**Comment by PatchworkBoy** [comment]
🤷🏼 - nothing to do with me. That site isn’t pulling latest README.md 

The only official instructions are the front page of this repo.
