### ISSUE TITLE
Thermostat are not visible any more with Domoticz 2024.x

### ISSUE THREAD

**Issue by MadPatrick** [PatchworkBoy/homebridge-edomoticz#279]
Hi,
I'm trying out Homebridge with edomoticz, but hte themrostats are not visible in Accesoiries.
When i try on a VM to use it with Domotivz 2023.2 they are visible

**Comment by MadPatrick** [comment]
I've tried your suggestion, but did not fix the problem

**Comment by DewGew** [comment]
Checkout this issue #274 maybe you find somthing there to fix this

**Comment by MadPatrick** [comment]
That worked.  Thanks !!

Probably wants
|| this.Type == "Setpoint" 
adding at line 2226…

[homebridge-edomoticz/lib/domoticz_accessory.js](https://github.com/PatchworkBoy/homebridge-edomoticz/blob/c3bb69422b7288d5a5a829ab49d029ebfc6992f0/lib/domoticz_accessory.js#L2226)

Line 2226 in [c3bb694](https://github.com/PatchworkBoy/homebridge-edomoticz/commit/c3bb69422b7288d5a5a829ab49d029ebfc6992f0)

 case this.Type == "Heating" || this.Type == "Thermostat":
