### ISSUE TITLE
Support for Domoticz V2023.2 and newer

### ISSUE THREAD

**Issue by RaymondBuil** [PatchworkBoy/homebridge-edomoticz#281]
Hi,

When do you expect to have support for the new API calls within Domoticz?

See  https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Warning_Stable_2023.2_(and_newer)

Thanks

**Comment by PatchworkBoy** [comment]
Already does... (?)

**Comment by RaymondBuil** [comment]
Apologies. Looks like I'm running 2023.1 instead of 2023.2

Yes indeed, it is supported.
Thanks
