### ISSUE TITLE
thermostat full compliance homekit

### ISSUE THREAD

**Issue by gibbo520** [PatchworkBoy/homebridge-edomoticz#284]
Hi, is there a way to have a thermostat setpoint in Domoticz that reflects all functions in HomeKit?

![IMG_1017](https://github.com/user-attachments/assets/fc5b977c-d9b1-404e-af6f-8cc32adddd65)

Now the actual temp (26,8 c°) on dummy thermostat ins equal to the setpoint and there is no function for heating, cooler auto , off.

is there a working integration in edomoticz ? if yes what type and subtype? 
i like to integrate with openwebnet TCP i can write the code for domoticz  

Thanks

**Comment by PatchworkBoy** [comment]
I use homebridge-web-thermostat to node-red to Domoticz json api… Sent from my iPhoneOn 1 Sep 2024, at 23:42, Fabio ***@***.***> wrote:﻿
Hi, is there a way to have a thermostat setpoint in Domoticz that reflects all functions in HomeKit?
IMG_1017.PNG (view on web)
Now the actual temp (26,8 c°) on dummy thermostat ins equal to the setpoint and there is no function for heating, cooler auto , off.
is there a working integration in edomoticz ? if yes what type and subtype?
i like to integrate with openwebnet TCP i can write the code for domoticz
Thanks
