### ISSUE TITLE
TV marked as light

### ISSUE THREAD

**Issue by vespino** [PatchworkBoy/homebridge-edomoticz#286]
I have 4 lights in my living room and 1 TV. When I tell Google to turn on the lights, 5 devices are turned on instead of 4. The 4 lights show as lights and the TV (a switch) is shown as an on/off switch.

I have posted this here too, but homebridge-gsh doesn’t think it’s related to that plugin: https://github.com/homebridge-plugins/homebridge-gsh/issues/8

**Comment by PatchworkBoy** [comment]
Nothing's changed in eDomoticz around the TV type in *ages* I'm afraid. It's exposed as the types necessary to be seen by HomeKit as a TV, as defined by the HomeKit TV device specification. Which also hasn't changed in ages.

**Comment by PatchworkBoy** [comment]
Change icon in Domoticz to something other than TV to have it not be cast as HomeKit TV device, and it should then turn up as a plain switch/outlet.

But then iOS devices won't be able to control via native HomeKit remote / TV features.

**Comment by vespino** [comment]
Changed it to “generic on/off switch” and will wait for an update. A dummy switch with the name “computer” and on/off switch does the same btw. Could this also be cast as a TV device?

**Comment by vespino** [comment]
Oh and so is my Christmas tree.

**Comment by vespino** [comment]
When selecting generic nothing changes, but selecting wall socket the devices changed in the Google Home app. Too bad I won’t be able to use the categories I was used to, I had TV, computer, alarm in use, but all showed up as light switch. Strange? Any change that can be made?

**Comment by PatchworkBoy** [comment]
See Domoticz_accessory.js - all the detection rules for how devices are cast and what services they get assigned are in there if you want to override the proper type casts for HomeKit compliance.Sent from my iPhoneOn 12 Dec 2024, at 21:53, vespino ***@***.***> wrote:﻿
When selecting generic nothing changes, but selecting wall socket the devices changed in the Google Home app. Too bad I won’t be able to use the categories I was used to, I had TV, computer, alarm in use, but all showed up as light switch. Strange? Any change that can be made?

**Comment by vespino** [comment]
I’m using Google Home instead of Apple Home. Could this be the issue?

**Comment by PatchworkBoy** [comment]
Homebridge is specifically for making things compatible with Apple HomeKit... so, yes.

**Comment by PatchworkBoy** [comment]
How is it handled if set as...

![image](https://github.com/user-attachments/assets/5db43b8d-7f97-452f-b592-ef2afa40d30e)

That's how my TVs are set and work fine with Apple and NorthernMan's Alexa plugin.

**Comment by NorthernMan54** [comment]
I think this is the issue 

![image](https://github.com/user-attachments/assets/a060bb4c-a31a-4285-a02b-5f5a9ab347fe)

Wrong Type selected

**Comment by vespino** [comment]
Oh shoot, I think I didn’t read that correctly. I have changed my dummy device and after updating it appeared as media device showing volume and casting etc, but… my switch is only named TV, but it’s not really a TV, it’s an on/off switch/wall socket that I marked with the TV icon so I can distinguish it without Domoticz as TV. Sorry if I was unclear.

**Comment by vespino** [comment]
Although not exactly how I’d invisioned it, I changed all devices concerning my issue to “media player” and selected the icon I associate with its action. The devices are shown in Homebridge as TV and have an extra icon added to them, fine, the idea is not to use the Homebridge interface. I did hide the extra icons to please my ocd. In Google Home the devices are also shown as a TV, but since I mainly use Google Assistant to control the devices by speaking, this is also something I can deal with. When now asking Google to turn on/off the lights in my living room, only the lights are controlled and not the TV. Cheers.
