### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by m0rph13** [PatchworkBoy/homebridge-eDomoticz#3]
Being able to assign types of modules through tags (such as with the z-way plugin for homebridge) would make it far easier to get siri to properly manage devices.
Any plan in this area?

**Comment by PatchworkBoy** [comment]
Have just had a wander thru the ZWay plugin - interesting... will see what I can do.

Need to make the decision now whether to spend time applying this concept to the currently supported sensors before going any further... as it'll be too big of a job to retrofit it afterwards. Will give it some thought.

**Comment by PatchworkBoy** [comment]
I’m getting the impression this might be coming natively to homebridge anyways or a variant thereof, looking at https://github.com/nfarina/homebridge/pull/497

I’m pausing for a few days to look into implementing the new plugin-2 api and sorting out UUID generation...

**Comment by m0rph13** [comment]
Hi!
Any plan for how this feature?

**Comment by PatchworkBoy** [comment]
Not as yet. Waiting for developments at homeBridge HQ as per above.
