### ISSUE TITLE
MQTT-integration branch - loses accessories.

### ISSUE THREAD

**Issue by PatchworkBoy** [PatchworkBoy/homebridge-eDomoticz#33]
Something occurs within the MQTT-integration branch which causes the loss of a large number of accessories (54 in my case), and requires a restart of homeBridge to resolve. Don't know the trigger / cause as of yet.

**Comment by xTheRamon** [comment]
Did you find anything of use?  👍🏼 As of now I have not encountered this issue.

**Comment by PatchworkBoy** [comment]
Nope!!  I can see am going to have to go thru and sanitize all the value inputs to ensure types match up with characteristics... something is marking devices for removal, and that's usually only cause by invalid characteristics / values.

**Comment by PatchworkBoy** [comment]
OK - I think it’s memory usage. Have scaled node-red back to purge at 96Mb instead of the default 128Mb for Pi to free up some, and thus far it’s kept all sensors for 3 hours, which is something of a record. I’ll see what state things are in when i get up in the morning and will report back.

For reference this is on RaspPi Model B+ (original footprint) and standard Domoticz image - I tend to develop on the lowest spec in my possession. Haven’t actually tried it on a Pi2 or 3 yet...

If everything’s still standing in the morning, I’ll spin up a Pi2 & 3 tomorrow evening and test the same Domoticz instance & sensors on those to confirm.

I’ve still got some value sanitising to do, which sods law Domoticz doesn’t make straight forward as it’s output is inconsistent depending on the physical sensor... i.e.: Go through the custom services, change the types away from string, apply correct units wherever possible rather than appending to the value, and change a few Characteristic UUIDs (e.g.: Barometer) to match Elgato UUIDs, and I’m chatting to Brutella re: his home app not picking up a few characteristics.

Then I’ll be throwing in a few regex replaces on the HTTP get’s to ensure everything falls into line, and relevant type checks into the MQTT functions.

**Comment by xTheRamon** [comment]
Great! What a find! My lowest RPI is a Model 2. Have not had any issues on that one. Sure hope everything is still working on your end!
Yep, totally agree with you. Superb job! 👍🏼

**Comment by PatchworkBoy** [comment]
Nope - not a find. Woke up this morning to find everything had vanished again.

**Comment by xTheRamon** [comment]
Nice! Great job. We should probably remove the logging of MQTT messages too. This increases unnecessary load on the devices, and I can imagine that having to keep up the log with messages is somewhat of a burden for it, too. What do you think?

**Comment by PatchworkBoy** [comment]
Add an extra in config.json, logging 1 / 0? Just so it’s easy to turn back on for the end user for diagnostic purposes...?

**Comment by xTheRamon** [comment]
Perfect! Let me put up something.

**Comment by xTheRamon** [comment]
What do you think about the following?

> *index.js*
```javascript
this.log = function() {
  if (typeof process.env.DEBUG !== 'undefined') {
    log(util.format.apply(this, arguments));
  }
};
```
Normal output:

```
[8/19/2016, 12:04:18 PM] Loading 1 platforms...
[8/19/2016, 12:04:18 PM] [eDomoticz] Initializing eDomoticz platform...
[8/19/2016, 12:04:18 PM] Loading 0 accessories...
[8/19/2016, 12:04:18 PM] [eDomoticz] Initializing platform accessory 'Dimmer'...
[8/19/2016, 12:04:18 PM] [eDomoticz] Initializing platform accessory 'SimpleOn/Off'...
[8/19/2016, 12:04:18 PM] [eDomoticz] Initializing platform accessory 'thermos'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/19/2016, 12:04:18 PM] Homebridge is running on port 51826.
```

When running in debug mode:

`DEBUG=* ./bin/homebridge -D`

```
[8/19/2016, 12:08:16 PM] Loading 1 platforms...
[8/19/2016, 12:08:16 PM] [eDomoticz] Initializing eDomoticz platform...
[8/19/2016, 12:08:16 PM] [eDomoticz] Fetching Domoticz lights and switches...
[8/19/2016, 12:08:16 PM] Loading 0 accessories...
[8/19/2016, 12:08:16 PM] [eDomoticz] Initializing platform accessory 'Dimmer'...
[8/19/2016, 12:08:16 PM] [eDomoticz] Initializing platform accessory 'SimpleOn/Off'...
[8/19/2016, 12:08:16 PM] [eDomoticz] Initializing platform accessory 'thermos'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[8/19/2016, 12:08:16 PM] Homebridge is running on port 51826.
  EventedHTTPServer Server listening on port 51826 +0ms
[8/19/2016, 12:08:16 PM] [eDomoticz] Data Received for Dimmer: 31.25
  EventedHTTPServer [::ffff:10.105.1.76] HTTP request: /characteristics +52s
  HAPServer [CC:21:3E:E4:DE:33] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":6,"iid":9,"value":1}] +0ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +0ms
[8/19/2016, 12:09:10 PM] [eDomoticz] SimpleOn/Off sent on command succesfully
  EventedHTTPServer [::ffff:10.105.1.76] Muting event '6.9' notification for this connection since it originated here. +11ms
  EventedHTTPServer [::ffff:10.105.1.76] HTTP Response is finished +0ms
[8/19/2016, 12:09:10 PM] [eDomoticz] MQTT Message received for SimpleOn/Off (Type: Lighting 1, SubType: X10, swType: 0)
```

Looks a bit prettier in production, stuff's coloured.

**Comment by PatchworkBoy** [comment]
Aye - that’ll do fer me!

**Comment by xTheRamon** [comment]
Righto, pushed!

**Comment by PatchworkBoy** [comment]
Yay! Have pushed all my changes also. I THINK we’re back to Release Candidate stage - just need to get folks to nudge themselves up to this version, test for a few days and report back, just in case the incoming value sanitisation doesn’t accommodate everyone’s devices happily (i.e.: Deejc and his YouLess meter for instance)
