### ISSUE TITLE
youless electricity meter not working

### ISSUE THREAD

**Issue by deejc-uk** [PatchworkBoy/homebridge-eDomoticz#4]
the youless kwh meter does not show values, the json is below as requested.

{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "Counter" : "17263.158",
         "CounterToday" : "6.651 kWh",
         "CustomImage" : 0,
         "Data" : "17263.158 kWh 370 Watt",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "Youless",
         "HardwareType" : "YouLess Meter with LAN interface",
         "HardwareTypeVal" : 6,
         "HaveTimeout" : false,
         "ID" : "80",
         "LastUpdate" : "2016-02-02 22:27:12",
         "Name" : "Youless",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "YouLess counter",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "YouLess Meter",
         "TypeImg" : "counter",
         "Unit" : 1,
         "Usage" : "370 Watt",
         "Used" : 1,
         "XOffset" : "385",
         "YOffset" : "366",
         "idx" : "5"
      },

**Comment by PatchworkBoy** [comment]
I'll have a look at sorting that tomorrow evening (UK time) for you...

**Comment by PatchworkBoy** [comment]
Done... update, test and let me know!

**Comment by PatchworkBoy** [comment]
Confirmed working...!
