### ISSUE TITLE
ssl does not work

### ISSUE THREAD

**Issue by derekhardwick** [PatchworkBoy/homebridge-edomoticz#41]
Domoticz is running properly on 8080 and 443.  User auth is not yet turned on (I thought that may be the issue so it's disabled).

```
pi@pi:~ $ wget --no-check-certificate -q -O - "$@" https://127.0.0.1/ | head
<!DOCTYPE html>
<html manifest="html5.appcache">
<head>
       		<meta charset="utf-8">
       		<title>Domoticz</title>
```

The important part of the config.json is:

```
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "ssl": 1,
            "port": "443",
            "roomid": 0
        }
    ],
    "accessories": []
 }
```

After starting homebridge I get this in the logs:

```
[Sun Sep 04 2016 19:50:10 GMT+0200 (CEST)] [eDomoticz] Initializing eDomoticz platform...
[Sun Sep 04 2016 19:50:10 GMT+0200 (CEST)] [eDomoticz] Fetching Domoticz lights and switches...
[Sun Sep 04 2016 19:50:10 GMT+0200 (CEST)] Loading 0 accessories...
[Sun Sep 04 2016 19:50:10 GMT+0200 (CEST)] [eDomoticz] There was a problem connecting to Domoticz.
```

Changing ssl to 0 and port to 8080 fixes the issue, homebridge will start fine.

Possible issue: certificate is issued to the FQDN and not 127.0.0.1?

**Comment by PatchworkBoy** [comment]
Head to your homebridge-edomoticz folder and...

```
sudo mv index.js index.bak
sudo wget https://raw.githubusercontent.com/PatchworkBoy/homebridge-edomoticz/SSL-rejectUnauthorized/index.js
```

Test n’ let me know!

**Comment by derekhardwick** [comment]
Thanks for the quick help.  So replacing the file half-worked, homebridge now starts up properly and tries to load the domoticz platform / accessories (further than it got before)

```
[Wed Sep 07 2016 15:06:12 GMT+0200 (CEST)] Loading 1 platforms...
[Wed Sep 07 2016 15:06:12 GMT+0200 (CEST)] [eDomoticz] Initializing eDomoticz platform...
[Wed Sep 07 2016 15:06:12 GMT+0200 (CEST)] [eDomoticz] Fetching Domoticz lights and switches...
[Wed Sep 07 2016 15:06:12 GMT+0200 (CEST)] Loading 0 accessories...
[Wed Sep 07 2016 15:06:12 GMT+0200 (CEST)] [eDomoticz] Initializing platform accessory 'Dining Room'...
[Wed Sep 07 2016 15:06:12 GMT+0200 (CEST)] [eDomoticz] Initializing platform accessory 'Front Door'...
[Wed Sep 07 2016 15:06:12 GMT+0200 (CEST)] [eDomoticz] Initializing platform accessory 'Hall Switch upstairs'...
[Wed Sep 07 2016 15:06:12 GMT+0200 (CEST)] [eDomoticz] Initializing platform accessory 'Living Room'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
```

But when I try to use a client app like Eve I get this in the logs:

` [Wed Sep 07 2016 15:04:44 GMT+0200 (CEST)] [eDomoticz] There was a problem connecting to Domoticz.

**Comment by PatchworkBoy** [comment]
Yep... s'what I expected to happen, but confirms the headers are correct now, so I just need to make those headers the default for all queries and that'll be it sorted. 

M

**Comment by derekhardwick** [comment]
Awesome.  Even without SSL I also had difficulty with user auth, but I didn't fight with that one too much.  I'll screw with that later and post a separate bug if I didn't miss something obvious.

Thanks!

**Comment by PatchworkBoy** [comment]
Righty - repeat instructions from my previous post above, restart homebridge, give it another try n’ let me know!

**Comment by derekhardwick** [comment]
Worked like a charm.
