### ISSUE TITLE
Opentherm Interface setpoint room temperature.

### ISSUE THREAD

**Issue by rwijbenga** [PatchworkBoy/homebridge-edomoticz#46]
The Opentherm interface uses 2 different devices for the room setpoint and room temperature...

I there a way to combine them in homekit? So that just 1 switch / device is needed? 
Now I have 2 devices, 1 for the setpoint and 1 displaying the temperature. And the setpoint device displays as room temperature the setpoint temperature... :(

The JSON output for the room setpoint:

`{
   "ActTime" : 1475018144,
   "ServerTime" : "2016-09-28 01:15:44",
   "Sunrise" : "07:34",
   "Sunset" : "19:19",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "14.0",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 7,
         "HardwareName" : "Verwarming",
         "HardwareType" : "OpenTherm Gateway with LAN interface",
         "HardwareTypeVal" : 20,
         "HaveTimeout" : false,
         "ID" : "0000005",
         "LastUpdate" : "2016-09-28 01:15:08",
         "Name" : "Kamer Temperatuur",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : [ 5, 6 ],
         "Protected" : false,
         "SetPoint" : "14.0",
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "SetPoint",
         "Timers" : "false",
         "Type" : "Thermostat",
         "TypeImg" : "override_mini",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "222"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

The room temperature JSON: 

`{
   "ActTime" : 1475018187,
   "ServerTime" : "2016-09-28 01:16:27",
   "Sunrise" : "07:34",
   "Sunset" : "19:19",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "22.1 C",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 7,
         "HardwareName" : "Verwarming",
         "HardwareType" : "OpenTherm Gateway with LAN interface",
         "HardwareTypeVal" : 20,
         "HaveTimeout" : false,
         "ID" : "0008",
         "LastUpdate" : "2016-09-28 01:15:08",
         "Name" : "Woonkamer",
         "Notifications" : "false",
         "PlanID" : "5",
         "PlanIDs" : [ 5, 6 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 22.10,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 8,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "224"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`
 
Let me know if I can help / test anything more...

**Comment by PatchworkBoy** [comment]
Nope. No way to combine them. Sorry.
