### ISSUE TITLE
geting this while plugin install

### ISSUE THREAD

**Issue by nashlib** [PatchworkBoy/homebridge-edomoticz#48]
`npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130`

The plugin loads fine. But it Homebridge does not find the added devices. What am I doing wrong ?

**Comment by PatchworkBoy** [comment]
That's a warning, perfectly normal, unrelated to your issue.

Please share the contents of your  ~/.homebridge/config.json file.

**Comment by nashlib** [comment]
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": *****,
        "pin": "***-**-***"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template$

    "accessories": [],

    "platforms": [
        {
            "platform": "LifxLan",
            "name": "LiFx"
        },
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform",
            "expected_accessories" : "0",
            "timeout" : "25",
            "no_motion_timer": "60",
            "homekit_safe" : "1"
         },
         {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "**.*.*.***",
            "port": "8080",
            "ssl": 0,
            "roomid": 0
         }
    ]
}`

hI there mate - thanks for taking time to answer - I have all else working - just the z-wave devices are not coming through

**Comment by nashlib** [comment]
Just as an added comment - I have the Domoticz server installed on a separate Raspberry pi which is in the same network as my homebridge pi

**Comment by PatchworkBoy** [comment]
Now need output from domoticzURL:8080/json.htm?type=devices

**Comment by nashlib** [comment]
AGAIN a huge thanks for taking the time buddy. Here is the output as you asked it. installing the plugin breaks my Homebridge build completely. I need to uninstall the plugin completely to get other plugins to work

`{
   "ActTime" : 1475783946,
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000201",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-10-07 05:16:25",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Second bedroom Switch",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "00000265",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-10-07 00:15:56",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "RGBW",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 0,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "2"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Monday 00:00",
         "DayTime" : "0;0;0",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : true,
         "ID" : "00000201",
         "LastUpdate" : "2016-10-07 00:16:07",
         "Name" : "Unknown",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Thermostat Clock",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "clock",
         "Unit" : 1,
         "Used" : 0,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "3"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "00000401",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-10-06 19:23:22",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Level",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 0,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "4"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "00000465",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-10-06 19:40:54",
         "Level" : 99,
         "LevelInt" : 99,
         "MaxDimLevel" : 100,
         "Name" : "Bedroom floor lamp",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "5"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "31.7 C",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : true,
         "ID" : "0301",
         "LastUpdate" : "2016-10-06 23:28:03",
         "Name" : "Temperature",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 31.70,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 0,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "6"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CounterToday" : "3.037 kWh",
         "CustomImage" : 0,
         "Data" : "3.040 kWh",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "00000201",
         "LastUpdate" : "2016-10-07 05:25:56",
         "Name" : "kWh Meter",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "kWh",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "current",
         "Unit" : 1,
         "Usage" : "0.0 Watt",
         "Used" : 0,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "7"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0.0 Watt",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : false,
         "ID" : "0000201",
         "LastUpdate" : "2016-10-07 05:25:56",
         "Name" : "Unknown",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Electric",
         "Timers" : "false",
         "Type" : "Usage",
         "TypeImg" : "current",
         "Unit" : 2,
         "Used" : 0,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "8"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0.000 V",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : true,
         "ID" : "00000201",
         "LastUpdate" : "2016-10-07 00:15:57",
         "Name" : "Voltage",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "Voltage",
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "current",
         "Unit" : 1,
         "Used" : 0,
         "Voltage" : 0.0,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "9"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "0.0 A",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "Z Stick",
         "HardwareType" : "OpenZWave USB",
         "HardwareTypeVal" : 21,
         "HaveTimeout" : true,
         "ID" : "0201",
         "LastUpdate" : "2016-10-07 00:15:57",
         "Name" : "Unknown",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "CM113, Electrisave",
         "Timers" : "false",
         "Type" : "Current",
         "TypeImg" : "current",
         "Unit" : 0,
         "Used" : 0,
         "XOffset" : "0",
         "YOffset" : "0",
         "displaytype" : 0,
         "idx" : "10"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}
`

**Comment by PatchworkBoy** [comment]
Ok - nothing abnormal there - everything should be supported.

Can you get the output from

DEBUG=* homebridge -d

**Comment by nashlib** [comment]
`*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[10/7/2016, 8:27:53 PM] Loaded plugin: homebridge-edomoticz
[10/7/2016, 8:27:53 PM] Registering accessory 'homebridge-edomoticz.eDomoticz'
[10/7/2016, 8:27:53 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
[10/7/2016, 8:27:53 PM] ---
[10/7/2016, 8:27:53 PM] Loaded plugin: homebridge-lifx-lan
[10/7/2016, 8:27:53 PM] Registering platform 'homebridge-lifx-lan.LifxLan'
[10/7/2016, 8:27:53 PM] ---
[10/7/2016, 8:27:53 PM] Loaded plugin: homebridge-platform-wemo
[10/7/2016, 8:27:53 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[10/7/2016, 8:27:53 PM] ---
[10/7/2016, 8:27:53 PM] Loaded config.json with 0 accessories and 2 platforms.
[10/7/2016, 8:27:53 PM] ---
[10/7/2016, 8:27:53 PM] Loading 2 platforms...
[10/7/2016, 8:27:53 PM] [LiFx] Initializing LifxLan platform...
[10/7/2016, 8:27:53 PM] [WeMo Platform] Initializing BelkinWeMo platform...
[10/7/2016, 8:27:53 PM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ ***-**-*** │     
    └────────────┘     
                       
  Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +10ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51926
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/hap-nodejs/lib/util/eventedhttp.js:59:19)
    at HAPServer.listen (/usr/lib/node_modules/hap-nodejs/lib/HAPServer.js:157:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:111:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:88:10)`

**Comment by nashlib** [comment]
This is what i get mate.

**Comment by nashlib** [comment]
I have tried to change the port number to something different after i install the plugin - i have also tried to change the MAC id as well. No matter what I do - until the plugin is uninstalled - HomeBridge does not work.

**Comment by PatchworkBoy** [comment]
Just to confirm - non of your Belkin or LiFX devices exist in your Domoticz setup... correct?

**Comment by PatchworkBoy** [comment]
And, when you run the above and let it crash, what is the output of

ps -aux | grep homebridge 

...immediately afterwards?

**Comment by PatchworkBoy** [comment]
(For EADDR to be in use, that indicates homebridge is already running and you're trying to start a second instance. Sudo Kill -9 all instances of homebridge, then launch with

DEBUG=* homebridge -d

...again. See if error is the same.)

**Comment by nashlib** [comment]
Bro,

Wow - i did a clean Jessie install and a clean Homebridge install with D plugin as the first plugin and now it work - will use it a bit and get back to you with regards to stability issues.

incidentally will a Aeotec Multisensor work ?

**Comment by PatchworkBoy** [comment]
Without seeing that specific devices json output from domoticz... no idea! 

Technically, if you can get it working in Domoticz it can be made to work via the plugin.
