### ISSUE TITLE
Logitech Media Server 

### ISSUE THREAD

**Issue by simonrb2000** [PatchworkBoy/homebridge-edomoticz#49]
As promised mate, Cheers (and no its not my dishwasher this time haha)

{
   "ActTime" : 1475962220,
   "ServerTime" : "2016-10-08 22:30:20",
   "Sunrise" : "07:16",
   "Sunset" : "18:21",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 6,
         "HardwareName" : "Raspberry Pi",
         "HardwareType" : "Logitech Media Server",
         "HardwareTypeVal" : 60,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000001B",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-10-08 00:13:48",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 15,
         "Name" : "Conservatory Radio",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "AC",
         "SwitchType" : "Media Player",
         "SwitchTypeVal" : 17,
         "Timers" : "false",
         "Type" : "Lighting 2",
         "TypeImg" : "LogitechMediaServer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "260"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by PatchworkBoy** [comment]
Heh - take it clearing persist worked??

**Comment by simonrb2000** [comment]
No, I have reopened as I was 99% sure clearing the persist would work as it made sense. 

I deleted both Accessories and Persist folders, restarted homebridge. Deleted my Home from HomeKit and re added everything. The LMS players still show unsupported. They don't even show up in EVE.

**Comment by PatchworkBoy** [comment]
Rightyho...! 

It does look as tho an earlier addition has been removed by a more recent commit in the code. Shall get it put back again when I'm near a laptop... quite possibly mapped as a dimmer ;)

**Comment by simonrb2000** [comment]
> quite possibly mapped as a dimmer ;)

I like your thinking!

**Comment by PatchworkBoy** [comment]
Can control power too if you look at it's description on npmjs...

> this plugin ignores power state commands (on/off) by default, this is to avoid having your receiver turn off if you tell Siri to "turn off all the lights". **If you want to control the power state of the receiver rather than ignoring it, set the "controlPower":true property in the configuration.**

**Comment by simonrb2000** [comment]
Oh yeah, I leave it to be power controlled via domoticz. It polls the receiver every so often so it knows if it's on etc.. I have a separate amp which powers 2 subs. So when the denon amp is on then domoticz knows to turn on the other amp etc..


On 10 Oct 2016, at 11:58, Marci <notifications@github.com<mailto:notifications@github.com>> wrote:


Can control power too if you look at it's description on npmjs...

this plugin ignores power state commands (on/off) by default, this is to avoid having your receiver turn off if you tell Siri to "turn off all the lights". If you want to control the power state of the receiver rather than ignoring it, set the "controlPower":true property in the configuration.

-

**Comment by simonrb2000** [comment]
Any luck with this Marci? 
Cheers

**Comment by PatchworkBoy** [comment]
Not yet - soz - mental week of server outtages & maintenance updates in readiness for an app launch taking all my time up.

**Comment by simonrb2000** [comment]
No worries mate 😀

**Comment by PatchworkBoy** [comment]
Possibly sorted via https://github.com/PatchworkBoy/homebridge-edomoticz/commit/50d3a421e684b8b3888bd1a0a59b350f9721bae8 & https://github.com/PatchworkBoy/homebridge-edomoticz/commit/020dcb7b7e93c0ebcf29e9dc53d50fea84e46d3c

Give it a try n’ let me know...

**Comment by simonrb2000** [comment]
Brilliant Marci they are working however the dimmer has no effect. It's not tied into the volume of the radios. I'm not sure how it was implemented in the other plugins.

At least I can turn them on and off now.

Cheers


On 17 Oct 2016, at 17:44, Marci <notifications@github.com<mailto:notifications@github.com>> wrote:


Possibly sorted via 50d3a42<https://github.com/PatchworkBoy/homebridge-edomoticz/commit/50d3a421e684b8b3888bd1a0a59b350f9721bae8> & 020dcb7<https://github.com/PatchworkBoy/homebridge-edomoticz/commit/020dcb7b7e93c0ebcf29e9dc53d50fea84e46d3c>

Give it a try n' let me know...

-

**Comment by PatchworkBoy** [comment]
OK - you’re gonna have to play with some URLs to work out which has any impact on the volume then....

http://server:8080/json.htm?type=command&param=switchlight&idx=260&switchcmd=Set%20Level&level=10

http://server:8080/json.htm?type=command&param=udevice&idx=260&nvalue=0&svalue=79

Try the above two links, varying the level value between 0 & 15 in the first, and experiment with changing value between 0 & 100, and if the has no impact set value back to 0 and try same changing svalue.

Just copy and paste them into a web browser and hit enter to send the command to your domoticz install (obvs changing server:8080 for your domoticz ip & port.

Once we know which format of URL and values make a difference I can add a custom handler for it (seeing as it won’t directly map to the lighting dimmer characteristic).

**Comment by simonrb2000** [comment]
Marci, no luck trying to get the volume state, maybe if I can get the command to change with LMS directly could that be used instead? Also when the players are off they still show as on within HomeKit but as 0%.

**Comment by simonrb2000** [comment]
http://tutoriels.domotique-store.fr/content/54/95/fr/api-logitech-squeezebox-server-_-player-http.html

**Comment by simonrb2000** [comment]
Right, this command changes the volume within HomeKit but has no effect on the players. I guess thats what you mean by custom handler.

type=command&param=switchlight&idx=260&switchcmd=Set%20Level&level=10

Cheers mate

**Comment by simonrb2000** [comment]
This also increase the volume each time it is sent by 2
http://server:8080/json.htm?type=command&param=lmsmediacommand&idx=260&action=VolumeUp

**Comment by simonrb2000** [comment]
Implemented this another way using dummy dimmers and some scripting. Can now turn on/off and control volume with one dimmer per radio. Works in Home App and with Siri. If this is wanted by anyone I can post the scripts. Cheers
