### ISSUE TITLE
Possibility to add support for a Temp+Hum sensor

### ISSUE THREAD

**Issue by odelma** [PatchworkBoy/homebridge-eDomoticz#5]
Hi,

as requested (http://www.domoticz.com/forum/viewtopic.php?f=36&t=10272&start=20#p73066), here's the json-output of temp+hum sensor:

   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "22.3 C, 35 %",
         "Description" : "",
         "DewPoint" : "6.10",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "TelldusLive",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "Humidity" : 35,
         "HumidityStatus" : "Normal",
         "ID" : "14069",
         "LastUpdate" : "2016-02-03 09:38:17",
         "Name" : "Olohuone",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "THGN122/123, THGN132, THGR122/228/238/268",
         "Temp" : 22.30,
         "Timers" : "false",
         "Type" : "Temp + Humidity",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "1100",
         "YOffset" : "1034",
         "idx" : "26"
      }
   ],

Thanks a lot for the work on the plugin! :)

**Comment by PatchworkBoy** [comment]
Done, please update, test and let me know!

**Comment by PatchworkBoy** [comment]
Confirmed working - closing!

**Comment by odelma** [comment]
Great, thanks!
