### ISSUE TITLE
Lux sensor

### ISSUE THREAD

**Issue by naixra** [PatchworkBoy/homebridge-edomoticz#50]
Hello,

I noticed when the brightness of the room where I placed a light sensor is 0 lux with edomoticz in Home app, the switch loses signal. The Home app shows me that the switch is unavailable. And whenever there is a bit of brightness (1 lux for example), I get the switch in the system HomeKit.

is it normal?

Thanks.

**Comment by PatchworkBoy** [comment]
Should be fixed in MQTT-integration branch via https://github.com/PatchworkBoy/homebridge-edomoticz/commit/c3a7f326359050639fee5e54b2759133c594e584
