### ISSUE TITLE
Push On button wrong status

### ISSUE THREAD

**Issue by jonferreira** [PatchworkBoy/homebridge-edomoticz#53]
Hi,

There appears to be a small bug handling Push On devices. Basically whenever a homekit App is opened, say slider up to get the favourite devices on iOs10, it will show the device as On regardless of its real state - it's off I know.

Basically Homebridge shows this:

[10/17/2016, 9:38:41 AM] [eDomoticz] Data Received for Roller Shutters 40: 1

While Domoticz have:

{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 1.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 15,
         "HardwareName" : "Dummy",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "000140BA",
         "Image" : "Light",
         "InternalState" : "Off",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-10-17 08:26:56",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "Roller Shutters 40",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Switch",
         "SwitchType" : "Push On Button",
         "SwitchTypeVal" : 9,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "push",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "107"
      }

So clicking the device sends an Off command which does nothing since the device was already Off, clicking again and it sends an On command which finally "works".

Hope this makes sense

**Comment by PatchworkBoy** [comment]
Fixed! See https://github.com/PatchworkBoy/homebridge-edomoticz/commit/74d995cfc01414884fa2ef54e9a6dee00663851b

**Comment by jonferreira** [comment]
done, fantastic work! thanks
