### ISSUE TITLE
Domoticz internal Security Panel

### ISSUE THREAD

**Issue by ergofreiberg** [PatchworkBoy/homebridge-edomoticz#54]
... support would be nice.

{
"ActTime" : 1476811451,
"ServerTime" : "2016-10-18 20:24:11",
"Sunrise" : "08:09",
"Sunset" : "18:04",
"result" : [
{
"AddjMulti" : 1.0,
"AddjMulti2" : 1.0,
"AddjValue" : 0.0,
"AddjValue2" : 0.0,
"BatteryLevel" : 255,
"CustomImage" : 0,
"Data" : "Normal",
"Description" : "",
"Favorite" : 1,
"HardwareID" : 1,
"HardwareName" : "Domoticz Internal",
"HardwareType" : "Domoticz Internal interface",
"HardwareTypeVal" : 67,
"HaveDimmer" : false,
"HaveGroupCmd" : false,
"HaveTimeout" : false,
"ID" : "148702",
"LastUpdate" : "2016-10-18 15:36:07",
"MaxDimLevel" : 0,
"Name" : "Security Panel",
"Notifications" : "false",
"PlanID" : "5",
"PlanIDs" : [ 5 ],
"Protected" : false,
"ShowNotifications" : true,
"SignalLevel" : "-",
"Status" : "Normal",
"StrParam1" : "",
"StrParam2" : "",
"SubType" : "Security Panel",
"SwitchType" : "Security",
"SwitchTypeVal" : 0,
"Timers" : "false",
"Type" : "Security",
"TypeImg" : "security",
"Unit" : 0,
"Used" : 1,
"XOffset" : "430",
"YOffset" : "192",
"idx" : "43"
}
],
"status" : "OK",
"title" : "Devices"
}

... and working nvalues.

Disarm - 0
Normal Delay - 1
Alarm - 2
Alarm Delayed - 3
Motion - 4
No Motion - 5
Panic - 6
Panic End - 7
? - 8
Arm Away - 9
Arm Away Delayed - 10
Arm Home - 11
Arm Home Delayed - 12
Disarm? - 13

**Comment by xTheRamon** [comment]
I have implemented this just now. See commit 77b4c8f. The only thing left to do here is to build the sending of arm and disarm commands.

I have not built this for now since I'm not sure on how to save the passcode. We'd need a passcode for arming and disarming, and saving the passcode in `.homebridge/config` is not a good idea..
We'd want something like a control panel popping up on the HomeKit(/ Eve) app where the user can input their passcode everytime a state is being changed.

Not sure how to do this for now. Anyhow, Security panel status can be accessed through HomeKit now, and you'll receive a push notification everytime the alarm status changes. (immediately too, MQTT!)

**Comment by PatchworkBoy** [comment]
Have you looked at the configurationhandler within homebridge dynamic platform sample? https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js

Wonder if similar is triggerable just for specific type/subtype to capture & cache when bridge is first added to home if sec type exists...?

**Comment by xTheRamon** [comment]
Oh wow. Nice! Didn't know such a thing existed. Downside is that the "password" is still saved in ’config.json’. If anyone has access to that file, that person could basically unlock your security system. I'd rather have the user input it everytime, just as you would do when using the physical device.

**Comment by ergofreiberg** [comment]
Reading of security status works really well - big thanks for that. But the more You give, the more they want ... So my question is that can You instruct me what to change in accessory file to get sending status also working. I understand the risks of storing security code in file and can live with that for now.

**Comment by xTheRamon** [comment]
Alright, I'll have to take a look and try and reverse engineer the sending part. That's something I haven't done yet. All of this is undocumented in the API so I'll have to take a look at the Domoticz code. Will let you know!

**Comment by ergofreiberg** [comment]
Thank's in advance. I must say that there seems to be no security systems that actually work with homekit (at least I can’t find any - only promises for future). So hope You can find something.

**Comment by xTheRamon** [comment]
Alright! I have just committed a new version (e5d1267) which is on npm, too.

This version supports status changing through Homekit. No need to input your passcode anywhere. Somehow the "Security Key" is saved in Domoticz's settings. I can just take that value and use it in my security calls. Simply works. Try it out! ✌🏼

**Comment by ergofreiberg** [comment]
Wow, that was fast. Working like charm. Thank You very much.
