### ISSUE TITLE
Changing colour w/ MQTT disabled

### ISSUE THREAD

**Issue by xTheRamon** [PatchworkBoy/homebridge-edomoticz#56]
Changing a colour when mqttenabled=0 does not work.

**NewFolk**

> All 3 command work fine for me.
> 
> 
> But not from homekit app or Eve.
> 
> In log i see only on/off
> CODE: SELECT ALL
> MQTT: Topic: domoticz/in, Message: {"command":"switchlight","idx":117,"switchcmd":"On"}
> 
> and brightness change

> 
> CODE: SELECT ALL
> MQTT: Topic: domoticz/in, Message: {"command":"switchlight","idx":117,"level":100,"switchcmd":"Set Level"}
> 
> but when color change I see only 
> CODE: SELECT ALL
> User: Admin initiated a switch command
> 
> 
> If i disable MQTT by
> CODE: SELECT ALL

> "mqttenable":0
> 
> On any action I see
> CODE: SELECT ALL
> User: Admin initiated a switch command
> 
> 
> All works fine before upgrade(before MQTT integration) and all works fine from domoticz
> 
> rwijbenga, did you find the solution?
> Btw I also you MilIght but not with RFlink. I use native WiFi interface and Domoticz.

**Comment by xTheRamon** [comment]
Sorry, cannot reproduce this issue. Please check if the issue has been resolved already with the last commit. I tend to think so.

efd58b6

**Comment by NewFolk** [comment]
I was on npm. On master branch colour control work with MQTT disadbled.
