### ISSUE TITLE
Dimmer sends "on" command right after "set value"

### ISSUE THREAD

**Issue by xTheRamon** [PatchworkBoy/homebridge-edomoticz#57]
**hpapagaj**

> Guys I just updated to iOS10 and now I am using the built in iOS 10 Home app.
> 
> There is a problem with slider switch (on iOS 9 with Eve app it worked fine). If I ask for any value it is switches back to a very low value. Ineresting, that in Domoticz the LED slider switch is at the correct position.
> 
> Here is a log:
> 
> Siri:
> 
> CODE: SELECT ALL
> 2016-11-02 20:27:03.516 User: Admin initiated a switch command (25/LED/Set Level)
> 2016-11-02 20:27:03.553 LUA: dev Set Level: 96 %
> 2016-11-02 20:27:03.553 LUA: Value received from Domoticz was 31
> 2016-11-02 20:27:03.553 LUA: Calculated value for ESP is 1023
> 2016-11-02 20:27:03.554 LUA: Dimming LED to 1023
> 2016-11-02 20:27:03.554 LUA: echo Fadetimer=2000,LED1_target=1023 | socat - TCP:192.168.1.10:43333
> 2016-11-02 20:27:03.518 (Quinled_1) Lighting 5 (LED)
> 2016-11-02 20:27:04.295 User: Admin initiated a switch command (25/LED/On)
> 2016-11-02 20:27:04.356 LUA: dev On
> 2016-11-02 20:27:04.356 LUA: Turning on LED
> 2016-11-02 20:27:04.357 LUA: echo Fadetimer=2000,LED1_target= 8 | socat - TCP:192.168.1.10:43333
> 2016-11-02 20:27:04.300 (Quinled_1) Lighting 5 (LED)
> 
> 
> Manual:
> 
> CODE: SELECT ALL
> 2016-11-02 20:28:38.825 User: Admin initiated a switch command (25/LED/Set Level)
> 2016-11-02 20:28:38.858 LUA: dev Set Level: 40 %
> 2016-11-02 20:28:38.858 LUA: Value received from Domoticz was 13
> 2016-11-02 20:28:38.858 LUA: Calculated value for ESP is 196
> 2016-11-02 20:28:38.858 LUA: Dimming LED to 196
> 2016-11-02 20:28:38.859 LUA: echo Fadetimer=2000,LED1_target=196 | socat - TCP:192.168.1.10:43333
> 2016-11-02 20:28:38.827 (Quinled_1) Lighting 5 (LED)
> 
> 
> From the log I see, that Siri is initiated a switch command 25/LED/Set Level -> that's correct, but immediately after that there is a 25/LED/On command. And this is the problem. The LED is already on and this should not be executed (my default brightness is 8 after switch on).
> 
> No output from the update command. Maybe I have the latest version (I installed around 12:00)?
> 
> Current state:
> 
> Siri Turn the LED off => works
> Siri Turn the LED on => works
> Siri set LED to 100% (LED was ON) => dim command -> then on command => NOT OK
> Siri set LED to 100% (LED was OFF) => dim command -> then on command => NOT OK
> 
> Home app => OK, after choosing the value it sends the dim command only.

**Comment by xTheRamon** [comment]
I'm guessing this is something internal. The actual problem here:

- Dimming light through HomeKit app
- `setPowerState` is called, _even if the light was already on_. (`Characteristic.On`)
- `setdValue` is called, with the right percentage. (`Characteristic.Brightness`)

I have just changed this to lazy switching. The plugin only switches if the Power value is different than the cached value. (This means if the switch is on, and on is sent again, it won't do anything).

Closing...
See commit 2cc6c91.

**Comment by gerard33** [comment]
Thanks for this solution.
I still see the command being send in MQTT after updating to the new version.
Is that correct?

`2016-11-08 23:55:08.700 Dummy: Light/Switch | Sonos kantoor volume 
2016-11-08 23:55:08.700 MQTT: Topic: domoticz/in, Message: {"command":"switchlight","idx":409,"level":16,"switchcmd":"Set Level"}
2016-11-08 23:55:08.543 Dummy: Light/Switch | Sonos kantoor volume 
2016-11-08 23:55:08.543 MQTT: Topic: domoticz/in, Message: {"command":"switchlight","idx":409,"switchcmd":"On"}`
