### ISSUE TITLE
Nest Thermostat Heating

### ISSUE THREAD

**Issue by simonrb2000** [PatchworkBoy/homebridge-edomoticz#59]
Hi, now the cold weather is approaching and this is my first winter with a smart (Nest) thermostat I was hoping to get the most out of it. I have it setup within Domoticz and expose it using eDomoticz to Homebridge/Homekit. All is working except it always says its heating the house, this didn't really matter before however the other day I we were driving home from being out all day and the heating being off as a result. I said to Siri through the car set heating to 22 degrees, I thought it had gone through as I then said "Is the heating on?" and Siri said, your thermostat is heating the house. We came home to a cold house, then I realised within HomeKit the house always shows as heating.

Would it be possible to get the heating bit to work? In the native Home App it shows as heating which I didn't realise. There is a separate switch which shows if the heating is on so I could expose that to HomeKit via eDomoticz and ask is the Heating Switch on however it would be great if it could some how be incorporated into the exiting thermostat settings within HomeKit.

I have to apologise as I have mentioned this a while back within the eDomoticz forum however thought this would be a more appropriate place to put a request in.

Hope this makes sense! 

Cheers!!! :D

**Comment by PatchworkBoy** [comment]
See response at https://github.com/PatchworkBoy/homebridge-edomoticz/issues/63

The separate switch is the thing to expose and let Siri key off... that’s what everyone with manually created thermostats (e.g.: separate temp probe per room, individual upper and lower setpoint sensors, separate heating on/off switch) has to do.

There are just too many various cases implemented inconsistently within Domoticz for us to code solutions that are easy to set for the end-user. Sorry!

**Comment by simonrb2000** [comment]
Ah ok, I'll try and figure out how to get Siri to key off using the separate Heating On switch. It's a normal Nest thermostat and thought it would have been quite popular and easy to implant but I know very little tbh.

Cheers anyways.. :-)

Sent from my iPad

On 20 Nov 2016, at 16:29, Marci <notifications@github.com<mailto:notifications@github.com>> wrote:


See response at #63<https://github.com/PatchworkBoy/homebridge-edomoticz/issues/63>

The separate switch is the thing to expose and let Siri key off... that's what everyone with manually created thermostats (e.g.: separate temp probe per room, individual upper and lower setpoint sensors, separate heating on/off switch) has to do.

There are just too many various cases implemented inconsistently within Domoticz for us to code solutions that are easy to set for the end-user. Sorry!

-
