### ISSUE TITLE
Possibility to add support for Energy meter (PVoutput)

### ISSUE THREAD

**Issue by odelma** [PatchworkBoy/homebridge-eDomoticz#6]
Hi,

as requested in Domoticz forum, here's the json-output of energy meter:

   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CounterToday" : "62.080 kWh",
         "CustomImage" : 0,
         "Data" : "50196.992 kWh",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 8,
         "HardwareName" : "PVOutput",
         "HardwareType" : "PVOutput (Input)",
         "HardwareTypeVal" : 30,
         "HaveTimeout" : false,
         "ID" : "00000002",
         "LastUpdate" : "2016-02-03 23:55:22",
         "Name" : "Energy Consumption",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "kWh",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "current",
         "Unit" : 1,
         "Usage" : "4019.0 Watt",
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "22"
      }
   ],

It contains the current consumption ("Usage" : "4019.0 Watt"), daily usage ("CounterToday" : "62.080 kWh") and then I guess the lifetime usage ("Data" : "50196.992 kWh").

Thanks again!

**Comment by PatchworkBoy** [comment]
Blimey that's a _lot_ of juice!! Will have a look tomorrow evening...

**Comment by odelma** [comment]
I think that's about four years of usage there and when you add together Finland + winter months + heating with electricity = a lot of juice :) But it is actually not that uncommon to have that kind of figure for one or two year's usage in case you have a bit older house.

**Comment by PatchworkBoy** [comment]
Put it this way, your CounterToday = my monthly total average...!

**Comment by odelma** [comment]
Whoa, that's nice! Surely you have some sort of solar system hooked up then? In our home just the base consumption from all the continuously running appliances (without any heating) is around 400W+ range (~10-12kWh/d). So basically we never get a month under 500kWh when even during the summer time the water needs to be heated. But I guess we need to start thinking of ways to reduce the usage as the company operating the grids just announced an increase of 40% to transmission prices...:)

**Comment by PatchworkBoy** [comment]
Nope. No renewables of any form. All the lights are LED tho, that brought things down significantly.
Baseline when we're tooked up in bed at night is 140w with occasional peaks to 300w when either the fridge or one of the 2x freezers' thermostats kick in. All our hot water and heating is via gas.

On a "heavy" electric use day, we go thru about 13kWh. On a normal day, about 4kWh.

**Comment by PatchworkBoy** [comment]
OK - so there’s no reason that shouldn’t be working... unless it’s down to the string length being too long... but then it wouldn’t have ever worked if that was the case so this one’s got me stumped.

Here’s the output from my sensor - the plugin just checks for Type: General, SubType: kWh, and then pulls in Usage, Data & CounterToday as you correctly identified.

`{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CounterToday" : "0.000 kWh",
         "CustomImage" : 0,
         "Data" : "6.195 kWh",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 5,
         "HardwareName" : "eOn Elec",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "00082028",
         "LastUpdate" : "2016-02-04 17:38:51",
         "Name" : "Household Electricity",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "kWh",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "General",
         "TypeImg" : "current",
         "Unit" : 1,
         "Usage" : "1113.0 Watt",
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "29"
      },`

Remove the homebridge device from within your app... no need to reset all HomeKit Data (that way you at least get to keep your room and scene names set up in home kit - all you have to do is add devices back to rooms and actions back to scenes).

Empty your ~/.homebridge/persist folder and restart Homebridge, then re-pair your app with the homebridge device for a complete refresh - all I can suggest at the moment!

**Comment by odelma** [comment]
Hi, this was my bad. I was looking at the logs from Homebridge and saw that it was registering the Energy device just fine. I then took a closer look at Eve app and noticed that for some reason, after the Homekit reset (and then reconnecting to Homebridge) the types Current Usage, Current Consumption and Total Consumption were not enabled by default in Eve. After enabling those, the energy meter devices (Total & current consumption) are visible once again. Sorry for all the trouble.

**Comment by odelma** [comment]
Well, I'll still add that the value from "CounterToday" is not showing anywhere (or I wasn't at least able to find it) but probably it wasn't even before the update.

**Comment by PatchworkBoy** [comment]
No worries - that's caught me out a few times too. CounterToday I tried adding this evening as previously wasn't there, but doesn't pull through for me either so I left it out for now. Saturdays are my main coding days so will be trying to get it going then...

**Comment by PatchworkBoy** [comment]
Righty - CounterToday is fixed... no need to trash persist, just update the files, restart Homebridge, restart your HomeKit apps once homebridge comes back up, and the Today value should appear. Ditto for WindChill with Domoticz DarkSkies Virtual Wind Meter.

Let me know that CounterToday’s shown up for you and I’ll close this issue!

**Comment by odelma** [comment]
Thanks, works great now! :smile:
