### ISSUE TITLE
Domoticz not responding to homekit commands. 

### ISSUE THREAD

**Issue by ncosper** [PatchworkBoy/homebridge-edomoticz#60]
I believe I have this all installed per the instructions, even started everything from scratch twice and get the same results. 
Domoticz controls the three switches I currently have set up perfectly. Homebridge seems to poll the switches from domoticz but I cannot get it to control any of them. 

I had this all working a few months ago but had to reinstall the os on the pi, since then cannot seem to get this to go. 

Not sure where to go from here. Below is log from debug and attempting to change the state twice. Below that is my config. 

Thanks!!

`[11/8/2016, 8:00:35 PM] Loaded plugin: homebridge-edomoticz
[11/8/2016, 8:00:36 PM] Registering accessory 'homebridge-edomoticz.eDomoticz'
[11/8/2016, 8:00:36 PM] Registering platform 'homebridge-edomoticz.eDomoticz'
[11/8/2016, 8:00:36 PM] ---
[11/8/2016, 8:00:36 PM] Loaded config.json with 0 accessories and 1 platforms.
[11/8/2016, 8:00:36 PM] ---
[11/8/2016, 8:00:36 PM] Loading 1 platforms...
[11/8/2016, 8:00:36 PM] [eDomoticz] Initializing eDomoticz platform...
[11/8/2016, 8:00:36 PM] [eDomoticz] Fetching Domoticz lights and switches...
[11/8/2016, 8:00:36 PM] [eDomoticz] Initializing platform accessory 'Kitchen'...
[11/8/2016, 8:00:36 PM] [eDomoticz] Initializing platform accessory 'Lights in the Backyard'...
[11/8/2016, 8:00:36 PM] [eDomoticz] Initializing platform accessory 'Master Bedroom'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
  EventedHTTPServer Server listening on port 51826 +0ms
[11/8/2016, 8:00:36 PM] Homebridge is running on port 51826.
[11/8/2016, 8:00:36 PM] [eDomoticz] Successfully connected to MQTT broker.
[11/8/2016, 8:00:36 PM] [eDomoticz] Data Received for Kitchen.
[11/8/2016, 8:00:36 PM] [eDomoticz] Data Received for Kitchen: 98
[11/8/2016, 8:00:36 PM] [eDomoticz] Data Received for Master Bedroom.
[11/8/2016, 8:00:36 PM] [eDomoticz] Data Received for Master Bedroom: 100
  EventedHTTPServer [::ffff:10.0.0.71] New connection from client +1s
  EventedHTTPServer [::ffff:10.0.0.71] HTTP server listening on port 46398 +3ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /pair-verify +18ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +6ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +43ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /pair-verify +146ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +3ms
  HAPServer [CC:22:3D:E3:CE:30] Client 3654C130-9AB3-4DA3-8525-34C258BC2429 verification complete +9ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /accessories +9ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +9ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /characteristics +109ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":12,"ev":true},{"aid":2,"iid":15,"ev":true},{"aid":3,"iid":11,"ev":true},{"aid":3,"iid":14,"ev":true},{"aid":4,"iid":12,"ev":true},{"aid":4,"iid":15,"ev":true}] +3ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +3ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Reachable" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Category" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /characteristics +245ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /characteristics +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +0ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /characteristics +27ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":9,"ev":true},{"aid":4,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Brightness" for events +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /characteristics +10ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":4,"iid":9,"ev":true},{"aid":4,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Brightness" for events +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /characteristics +8ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"ev":true},{"aid":2,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +0ms
  Accessory [Homebridge] Registering Characteristic "Brightness" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /characteristics +16ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"ev":true},{"aid":2,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge] Registering Characteristic "On" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Brightness" for events +0ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /characteristics +15s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"value":1}] +2ms
  Accessory [Homebridge] Setting Characteristic "On" to value 1 +0ms
  EventedHTTPServer [::ffff:10.0.0.71] Muting event '2.9' notification for this connection since it originated here. +15ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP request: /characteristics +9s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":2,"iid":9,"value":0}] +8ms
  Accessory [Homebridge] Setting Characteristic "On" to value 0 +0ms
  EventedHTTPServer [::ffff:10.0.0.71] Muting event '2.9' notification for this connection since it originated here. +7ms
  EventedHTTPServer [::ffff:10.0.0.71] HTTP Response is finished +1ms

`

Config.json
`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [

		{"platform": "eDomoticz",
					"name": "eDomoticz",
					"server": "127.0.0.1",
					"port": "8080",
					"ssl": 0,
					"roomid": 2,
					"mqttenable": 1,
					"mqttserver": "127.0.0.1",
					"mqttport": "1883",
					 "mqttauth": 0,
					 "mqttuser": "",
					 "mqttpass": ""}
		]
}
`

**Comment by pierrenicolasr** [comment]
Which version of domoticz are you running ?
I had no time to investigate, but domoticz has been updated very recently after month of stable release and I noticed that MQTT integration was kind of broken: it would send incorrect values (you can try with mosquitto sub client). 
I disabled MQTT support in eDomoticz and things were working again. Slow, but working.

**Comment by ncosper** [comment]
Im on Version: 3.5837. Looks like its from 10-31. Just installed so probably the latest version. Maybe Id have better luck reverting back a version?

**Comment by xTheRamon** [comment]
Might be a stupid question, but did you add the MQTT hardware device to Domoticz, so that it's actually sending and receiving MQTT messages?

**Comment by ncosper** [comment]
Not stupid at all. I saw no mention at all of adding that to domoticz in the readme. I guess that should have been obvious to add but I didn't know it was a possible hardware device. 
Added it and one it works perfect. Thanks!

**Comment by xTheRamon** [comment]
Wow, great to hear.

Closing then!
