### ISSUE TITLE
ventian blind are not supported

### ISSUE THREAD

**Issue by kolargol** [PatchworkBoy/homebridge-edomoticz#64]
Hi,

When changing blind type to "ventian blind" HomeKit do not recognize it (edomoticz). Is it possible to add that support to the plugin ? (it is needed to support stop command)

**Comment by kolargol** [comment]
Maybe i was not clear on this. Currently when Blinds are configured in domoticz (as "blinds") - edomoticz present it in Home app as Blind (%) with no stop command. When i change type in Domoticz to "ventian" i am able to stop blinds using domoticz but eDomoticz seems not recognize it and as a result Home app report blinds as unsupported. Is it possible to add support for "ventian blinds" in edomoticz so stop command will work as expected?

thanks,

**Comment by xTheRamon** [comment]
Excuse me for the late reply.

I have just added Venetian blind support in the plugin.

Can you please update to the latest version (git or through npm) and let me know if the issue is resolved?

Thank you!

**Comment by kolargol** [comment]
Hi,

Thanks for this! Blinds are now visible in Home app in iPhone and i am able to open/close them. Unfortunately i cannot stop them (so i can only fully open or fully close them). I am not sure this is Home app problem or anything else. (in Domoticz "stop" button work correctly)

**Comment by xTheRamon** [comment]
Good to hear! Yeah, there isn't any HomeKit functionality for this yet. It's open or close, no more, no less.
