### ISSUE TITLE
LightwaveRF switch being turned off when already on

### ISSUE THREAD

**Issue by lukeredpath** [PatchworkBoy/homebridge-edomoticz#66]
Bit of a weird problem I've observed with some of my LightwaveRF lights.

I have two lights in my living room that are controlled by a LightwaveRF master switch. Because the protocol is one way, when the lights are controlled from the master switch its impossible for Domoticz (and therefore HomeKit) to know that a light has been turned on or off.

In practice this shouldn't be a problem - if the light is on and HomeKit (or Domoticz) thinks its off then turning it on will just send a harmless on command which won't do anything.

However I'm sometimes finding that when HomeKit thinks a light is off (but its actually on), when I turn the light on using the Home app the light actually turns off!

Looking at the Homebridge and Domoticz logs, what seems to be happening is that instead of just sending an "on" command, Homebridge is sending an "on" and "off" command.

Example:

Light is on (turned on from master switch)
Domoticz and HomeKit show the light as being off.
Using Home app to turn light on results in following entries in Domoticz log:

```
[12/16/2016, 1:24:37 PM] [eDomoticz] Setting power state to on
[12/16/2016, 1:24:37 PM] [eDomoticz] Living Room sent command succesfully
[12/16/2016, 1:24:37 PM] [eDomoticz] Living Room sent command succesfully
```

And the following in the Domoticz event log for that light (with most recent commands at top):

```
2016-12-16 13:24:37	Off
2016-12-16 13:24:37	On
```

From the Homebridge log it definitely appears to be sending two commands even though its only receiving one instruction from HomeKit (to set power state to on).

I've tried this with another light that exhibits this behaviour and the same thing happens - two entries in the Domoticz log for sending a successful command and Domoticz showing an on followed by an off command.

I'll try and look into the code myself if I have time but wondered if anyone else has had this problem (its not necessarily a LightwaveRF specific problem).

I can't remember if the switches in Domoticz are emulating one of my remote switches or are directly paired up with the master switch, if that makes any difference (I suspect not). It also doesn't happen every time.

**Comment by xTheRamon** [comment]
Oh wow, nice find. I've been trying to reproduce the issue but I'm having a really hard time to do so.

The *only* way commands are sent to Domoticz is through the `setPowerState` function. That function, in it's turn, uses `updateDeviceStatus`.

From what I can see there's no way `setPowerState` can be called twice, unless two MQTT commands are coming in. Could you try and log your MQTT messages?

**Comment by lukeredpath** [comment]
I've been meaning to get back to this - incidentally since updating the plugin recently, I no longer experience the problem so its possible that this bug was fixed (unintentionally or otherwise). Annoyingly I forgot to record which version I was running before. I'm not using MQTT though (I'd like to try it though, is there a guide for getting up and running with MQTT?).

**Comment by xTheRamon** [comment]
Yeah I already thought you weren't. Ehh there's not much to it really. Make sure you're running a MQTT broker, mosquitto for example. The standard Domoticz SD Card already had this installed.
You could check if mosquitto's running by requesting a list of active processes: `ps afx`

Then simply set your config value `"mqtt"` to `1`. Please see my config below:

```{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:21:3E:E4:DE:33",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Configuration file for (e)xtended Domoticz platform.",
    "platforms": [
        {
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "ssl": 0,
            "roomid": 0,
            "mqtt": 1
        }
    ],
    "accessories": []
}
```

Also, don't forget to add the MQTT hardware device in Domoticz. Use `localhost` and `1883` for host and port respectively. 👍🏼
