### ISSUE TITLE
Evohome

### ISSUE THREAD

**Issue by JeroenCloo** [PatchworkBoy/homebridge-edomoticz#68]
I have installed this plugin and the Domoticz devices are available in Homebridge.
I have several Evohome zones. The values are shown well in Domoticz. In Homebridge I see all zones, but the temperature shown on the device in HomeKit is equal to the set temperature (and not to the actual zone temperature). I use the Insteon+ app in my iPhone.

**Comment by xTheRamon** [comment]
Could you please start homebridge once in debug mode and post the results here?
Please post the "set" and "actual" temperature values, too.

To start homebridge in debug mode:
`DEBUG=* homebridge -D`

**Comment by JeroenCloo** [comment]
It appears to be a Homekit issue. See https://github.com/luc-ass/homebridge-evohome/issues/14

**Comment by xTheRamon** [comment]
Alright, closing then!
