### ISSUE TITLE
Show MySensors humidity values in HomeKit (not yet supported?)

### ISSUE THREAD

**Issue by MaKin211** [PatchworkBoy/homebridge-edomoticz#70]
Is it possible to show the humidity values (from mySensors) in HomeKit? It used to work for me with HomeAssistant as the controller but the plugin seems to be buggy and the sensors do not appear anymore. :(

Temp sensors seem to work (actually they are mixed sensors with TempHum) but the temperature is shown. Is there a way to have the same for humidity?

**Comment by xTheRamon** [comment]
Hi,

Please see commit 512d724. This commit contains Humidity sensor support. You can also update through npm (version 1.0.9).
