### ISSUE TITLE
UUID Conflict

### ISSUE THREAD

**Issue by Lorccan** [PatchworkBoy/homebridge-edomoticz#71]
This check (in Accessory.js):

`  // check for UUID conflict
  for (var index in this.bridgedAccessories) {
    var existing = this.bridgedAccessories[index];
    if (existing.UUID === accessory.UUID)
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
  }`

Is throwing the error when I have two distinct Lightwaverf switches in Domoticz with the _same name_ but in _different rooms_.  I have found mention elsewhere on #GitHub (rooi / home bridge-lightwaverf under closed issues "Duplicate names and the 12 character limit" - sorry can't get a working URL) of a similar problem with a different implementation, but I don't know enough to be able to fix it.

**Comment by PatchworkBoy** [comment]
All devices must have a unique name in Domoticz to function with this plugin, regardless of room.
