### ISSUE TITLE
Making a switch into a light

### ISSUE THREAD

**Issue by tanuva** [PatchworkBoy/homebridge-edomoticz#73]
I have an on/off wall plug that has a light attached. Domoticz classifies it as Light/Switch. The problem is that it consequently is just a switch in HomeKit, too, so it isn't considered for something like "Hey Siri, turn all the lights off!". I rather need to order "Turn everything in *room* off!" to have those match the command.
Is there a way in homebridge (or Domoticz for that matter) to tell the system that this wall switch effectively is a light?

**Comment by PatchworkBoy** [comment]
In Home.app tap and hold the switch, then hit details button, then on next screen change type to light.

**Comment by tanuva** [comment]
Oh, I didn't even expect that to be possible from within Home.app. Sorry and thanks! :)
