### ISSUE TITLE
usage/consumption graphs in Eve.app

### ISSUE THREAD

**Issue by PatchworkBoy** [PatchworkBoy/homebridge-eDomoticz#8]
### Some notes on tapping into the Eve.app graphing abilities

![Image of Eve App](https://www.elgato.com/sites/default/files/styles/desktop_hidpi_two_thirds/public/eve-landing-ipadiphone_1.jpg)

I presume Homebridge needs the v.latest version of @KhaosT’s [hap-nodejs](https://github.com/KhaosT/HAP-NodeJS) submodule, to provide the [‘log’ characteristic](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L933).

Then I presume either Eve.app will handle that characteristic if it detects it, or it’ll need linking in via [elgato-specific characteristics](https://gist.github.com/gomfunkel/b1a046d729757120907c) (as discovered by @gomfunkel)

Retrieving log points from Domoticz:

```
http://127.0.0.1:8080/json.htm?
		type=lightlog
		&idx={_ID_}
```

```
http://127.0.0.1:8080/json.htm?
		type=graph
		&sensor={counter|Percentage|temp|rain|fan|wind|uv}
		&idx={_ID_}
		&method={int}
		&range={day|week|month|year}
			{
			&actmonth={month}
			&actyear={year}
			}
```

**Comment by KhaosT** [comment]
The "log" characteristic you're referring is different from what elgato eve is using. Elgato Eve only uses their custom characteristic for historical data. You can check [here](https://github.com/KhaosT/HAP-NodeJS/issues/140) for more details.

**Comment by PatchworkBoy** [comment]
Thanks!

**Comment by PatchworkBoy** [comment]
Interesting gist... https://gist.github.com/0ff/668f4b7753c80ad7b60b

**Comment by luc-ass** [comment]
Is there any progress? I would love to see historical energy usage...

**Comment by PatchworkBoy** [comment]
‘fraid not...

**Comment by PatchworkBoy** [comment]
This ain’t gonna happen I’m afraid...
