### ISSUE TITLE
MQTT connection retry

### ISSUE THREAD

**Issue by sfeakes** [PatchworkBoy/homebridge-edomoticz#80]
I notice that the MQTT retry count is hardcoded to 5.  This doesn't isn't even give enough time to stop and re-start the Mosquitto service without homebridge-edomoticz timing out and never re-connecting to Mosquetto
Can I suggest you use an infinite retry, but maybe reduce the poll interval time after 5 or 10 tries?

**Comment by xTheRamon** [comment]
Good suggestion! Please see commit `c24cefb`. I have changed the retry mechanism to retry for an infinite amount of tries. Also, with a five second delay.

**Comment by sfeakes** [comment]
Thanks so much, works perfectly.
