### ISSUE TITLE
Sonoff POW Tasmota

### ISSUE THREAD

**Issue by jeylites** [PatchworkBoy/homebridge-edomoticz#81]
Hi - how to get Sonoff POW-  KWH values to homebridge. Does it support it?

**Comment by xTheRamon** [comment]
I'm not sure, but if Domoticz supports the Sonoff device and displays it's values in the `Utility` tab, Homebridge should and must support it! 👍🏼

If you have not bought the Sonoff device yet, you could try asking this in the Domoticz forum.
