### ISSUE TITLE
New door close/open device

### ISSUE THREAD

**Issue by simonrb2000** [PatchworkBoy/homebridge-edomoticz#82]
Added a new door close/open sensor and is show switchval 0. Although it shows up as security in Domoticz.

Cheers

{
   "ActTime" : 1496274250,
   "ServerTime" : "2017-06-01 00:44:10",
   "Sunrise" : "04:48",
   "Sunset" : "21:10",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 100,
         "CustomImage" : 0,
         "Data" : "Normal",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 1,
         "HardwareName" : "RFXCom",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "8F05A0",
         "LastUpdate" : "2017-06-01 00:38:23",
         "MaxDimLevel" : 0,
         "Name" : "Front Door",
         "Notifications" : "false",
         "PlanID" : "4",
         "PlanIDs" : [ 4 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : 6,
         "Status" : "Normal",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "X10 security",
         "SwitchType" : "Security",
         "SwitchTypeVal" : 0,
         "Timers" : "false",
         "Type" : "Security",
         "TypeImg" : "security",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "379"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by simonrb2000** [comment]
I have managed to map the device inside Domoticz to a door lock which is working within HomeKit now although it says Locked or Unlocked. Is there a way for HomeKit to display Open and Closed like on a garage door?

Cheers

**Comment by simonrb2000** [comment]
Update:-
I added a dummy Contact and update the status of that to reflect the state of the door. For some reason it shows up as Closed all the time.

**Comment by xTheRamon** [comment]
Haha good to hear you fixed it. Great job.
