### ISSUE TITLE
 "SubType" : "Kangtai / Cotech" with  "SwitchTypeVal" : 8 - Motion sensor not supported.

### ISSUE THREAD

**Issue by jorgeruimachado** [PatchworkBoy/homebridge-edomoticz#86]
```json
{
   "ActTime" : 1498646892,
   "ServerTime" : "2017-06-28 11:48:12",
   "Sunrise" : "06:03",
   "Sunset" : "21:10",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 30.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 2,
         "HardwareName" : "RFXCOM",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "46D2",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-06-28 11:08:21",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Movimento Garagem",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Kangtai / Cotech",
         "SwitchType" : "Motion Sensor",
         "SwitchTypeVal" : 8,
         "Timers" : "false",
         "Type" : "Lighting 5",
         "TypeImg" : "motion",
         "Unit" : 7,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "4"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}
```

This device works fine on domoticz, but the stat does not pass to HomeKit. Can you take a look at it?
Thanks in advanced!

**Comment by xTheRamon** [comment]
Hi @jorgeruimachado 

I have just tested the motion sensor with the same configuration as you have specified. It shows up in HomeKit and also seems to work. What NodeJS version are you on? There are a few problems with 8+.

**Comment by jorgeruimachado** [comment]
Yes it shows on HomeKit, but does not alter the state, at least for me..

NodeJS version: v7.10.0

**Comment by xTheRamon** [comment]
Try restarting your HomeBridge. And try directly after. Does that have any effect?

The reason I'm saying this is because I have the same problem, but on NodeJS 8. NodeJS 7.1 works for me!

PS. Might be a stupid question, but is your garage sensor in range of your RFXComm? 🙈

**Comment by jorgeruimachado** [comment]
The sensor shows and works well on Domoticz, them it's in range...
After restarting no effect.

**Comment by jorgeruimachado** [comment]
I will update my NodeJS to 8. to see it there is any effect with that.

**Comment by jorgeruimachado** [comment]
After 1 day of fresh installed OS homebrige etc. Something continues to be wrong... The sensor show and work well on Domoticz, but HomeKit show is sometimes, the notification only worked 2 to 3 times, on a universe of 30+ activation.

Something is not good

**Comment by xTheRamon** [comment]
Wow, so weird! There is something wrong with the message throughput. Seems like the plugin gets the message every time though. Just that when it asks Homebridge to update it doesn't want to. I'm investigating... What iOS version are you on?

**Comment by xTheRamon** [comment]
Try and update your homebridge, homebridge modules (`npm update` in the homebridge directory) and homebridge-edomoticz and it's modules. The issue is now resolved for me!
