### ISSUE TITLE
Mi.Lights RGB+CCT - Not showing RGB/Saturation control

### ISSUE THREAD

**Issue by onkytonk** [PatchworkBoy/homebridge-edomoticz#87]
Hi there,
This plugin has seriously been the greatest! Just a few little quirks I'm trying to sort out.

So I'm using Mi.Lights from with domoticz that I've added into homekit. 
Unfortunately these RGB+CCT bulbs aren't giving me the colour/saturation option. 
The RGBW milight appears in homekit with these controls. 

I know there is a homebridge plugin that will directly control the MiLight system, but I'm hoping I can do it all through domoticz. 

Let me know how I can help get this working please.

**Comment by xTheRamon** [comment]
Hi! Should be possible yes. Could you please output your devices list so I can check what the difference is between your 'RGB+CCT' and RGBW MiLight? (Since the latter works?)

_Domoticz_url_ /json.htm?type=devices

**Comment by onkytonk** [comment]
Hey, thanks! 

I'm not sure how to output my device list. Could you tell me how please?

**Comment by xTheRamon** [comment]
What is your domoticz URL? How do you enter your web interface?

If that is, for example, http://192.168.1.2   please append the part I posted above so the url becomes:

http://192.168.1.2/json.htm?type=devices

**Comment by onkytonk** [comment]
So the first two devices are the living room lights and lamp (Both are RGB+CCT/RGBWW bulbs).
And the third device is the under TV lights (which is RGB/RGBW).

Is that all you need? I was going to post my entire device list, but I thought this would be simpler. 

Thanks. 

      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "MiLight Bridge",
         "HardwareType" : "Limitless/AppLamp/Mi Light with LAN/WiFi interface",
         "HardwareTypeVal" : 22,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "1",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-02 01:14:19",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 100,
         "Name" : "AppLamp All",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBWW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "dimmer",
         "Unit" : 0,
         "Used" : 0,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "1"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "MiLight Bridge",
         "HardwareType" : "Limitless/AppLamp/Mi Light with LAN/WiFi interface",
         "HardwareTypeVal" : 22,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "1",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-18 15:23:17",
         "Level" : 49,
         "LevelInt" : 49,
         "MaxDimLevel" : 100,
         "Name" : "Living Room Lights",
         "Notifications" : "false",
         "PlanID" : "3",
         "PlanIDs" : [ 3, 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBWW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "dimmer",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "250",
         "YOffset" : "474",
         "idx" : "3"
      },
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "MiLight Bridge",
         "HardwareType" : "Limitless/AppLamp/Mi Light with LAN/WiFi interface",
         "HardwareTypeVal" : 22,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "1",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-18 15:23:15",
         "Level" : 99,
         "LevelInt" : 99,
         "MaxDimLevel" : 100,
         "Name" : "Living Room Lamp",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2, 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBWW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "2"
      },


{
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 3,
         "HardwareName" : "MiLight Bridge",
         "HardwareType" : "Limitless/AppLamp/Mi Light with LAN/WiFi interface",
         "HardwareTypeVal" : 22,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "1",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-18 15:23:13",
         "Level" : 50,
         "LevelInt" : 50,
         "MaxDimLevel" : 100,
         "Name" : "Living Room TV Lights",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2, 3 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBW",
         "SwitchType" : "Dimmer",
         "SwitchTypeVal" : 7,
         "Timers" : "false",
         "Type" : "Lighting Limitless/Applamp",
         "TypeImg" : "dimmer",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "13"
      },

**Comment by xTheRamon** [comment]
Thanks a bunch! I'll have a look.

**Comment by xTheRamon** [comment]
I've had a look, and the issue should be resolved.

Please update to the latest version using npm. (1.0.15)
