### ISSUE TITLE
characteristic2 on fan type

### ISSUE THREAD

**Issue by morilm** [PatchworkBoy/homebridge-edomoticz#88]
Hi

Over the last weeks I have started to suffer a hombridge crash from time to time.
.
Seems to be related to line 676 when try to read characteristic2.

Do we know why this is implemented this way?  

Happy to support additional logs if needed

 /usr/lib/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:676
var characteristic2 = this.getService(Service.Switch).getCharacteristic(Characteristic.On);
 ^
TypeError: Cannot read property 'getCharacteristic' of undefined
 at eDomoticzAccessory.handleMQTTMessage (/usr/lib/node_modules/homebridge-edomoticz/lib/domoticz_accessory.js:676:60)

`
					if (this.name.indexOf("Fan") > -1) {
						var characteristic = this.getService(Service.Fan).getCharacteristic(Characteristic.On);
						callback(characteristic, message.nvalue);
					} else {
						var characteristic2 = this.getService(Service.Switch).getCharacteristic(Characteristic.On);
						callback(characteristic2, message.nvalue);
					}
					break;
`

**Comment by xTheRamon** [comment]
Thank you for noticing! I'll have a look! Seems like a problem in the code.

**Comment by xTheRamon** [comment]
This issue should be resolved now. Commit `ec09644`

I have just released a new version to npm. (v.1.0.13)

**Comment by morilm** [comment]
Thanks!!! Working 100% fine now... no more crashes!!!!  👍 :)
