### ISSUE TITLE
Blinds seen as switches

### ISSUE THREAD

**Issue by guiggess** [PatchworkBoy/homebridge-edomoticz#89]
Hello there,
I just finished the installation of Homebridge and eDomoticz plugin. Everything works fine so far. The only thing is that all of my Somfy blinds are shown up as switches. Not a big deal, but still annoying.
I just followed the official tutorial and installed node.js 8
Thanks a lot

**Comment by guiggess** [comment]
Also, the actual "blind switches" are inverted. I need to ask "Open..." to actually close the blinds...

**Comment by xTheRamon** [comment]
Hi! Weird. Could you please post your devices output? Will have a quick look then!

_Domoticz_url_ /json.htm?type=devices

**Comment by guiggess** [comment]
Hi !
Here is an example of one device output : 
`{
   "ActTime" : 1500323555,
   "ServerTime" : "2017-07-17 22:32:35",
   "Sunrise" : "05:45",
   "Sunset" : "21:24",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Closed",
         "Description" : "",
         "Favorite" : 0,
         "HardwareID" : 11,
         "HardwareName" : "RFXtrx433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "000005",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2017-07-17 22:08:09",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "Volet - Chambre - Jules",
         "Notifications" : "false",
         "PlanID" : "7",
         "PlanIDs" : [ 7 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Closed",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RFY",
         "SwitchType" : "Blinds",
         "SwitchTypeVal" : 3,
         "Timers" : "false",
         "Type" : "RFY",
         "TypeImg" : "blinds",
         "Unit" : 5,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "38"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}`

**Comment by xTheRamon** [comment]
Hi,

I have added an exception for Somfy blinds, as they seem to act like an 'inverted' blind over MQTT. Should work flawlessly in the new version. Thanks!

Npm version 1.0.14
d16fc74

**Comment by guiggess** [comment]
npm update -g
sudo reboot
Didn't fix my issue...

**Comment by xTheRamon** [comment]
Could you try with the latest version in npm? (2.0.8)
A lot has been changed. Might have also resolved your issue.

**Comment by guiggess** [comment]
Hi,
Should I "sudo sudo npm update -g homebridge-edomoticz" or reinstall ?

In the meantime I did a fresh install on another Micro SD and it worked fine. The blinds are seen as shades, but thats more or less OK for me (maybe not for you ;-).

I will try on my other SD and come back to you.

PS : First SD card (non-working) was installed with a Domoticz preconfigured SD image. Second SD card was installed (working) was installed last week with a Raspbian Jessie image.

**Comment by xTheRamon** [comment]
Ah right! Good to hear it somehow works. In order to update you can simply type `npm install -g homebridge-edomoticz`.
