### ISSUE TITLE
iOs 11 beta 4

### ISSUE THREAD

**Issue by Denna93** [PatchworkBoy/homebridge-edomoticz#93]
Hello. 

So I updated to the newest beta and the homebridge domoticz plugin doesnt work for the Home app anymore. Issue seems like it doesnt recognise the hub anymore. Cant find it. 

My other devices running older iOS works like a charm. So it worked up until iOS 11 beta 4

**Comment by xTheRamon** [comment]
Hi!

I had the same problem, ended up removing the accessories and persist folder in ~/.homebridge.
You’ll have to re-pair your HomeKit though.
