### ISSUE TITLE
iOS 11...  New devices in the air

### ISSUE THREAD

**Issue by morilm** [PatchworkBoy/homebridge-edomoticz#94]
Hi all,

If you are interested on what new devices are comming with iOS11:

https://9to5mac.com/2017/06/07/homekit-ios-11-sprinklers-faucets-qr-code-nfc-authentication/

Can't wait to have some of them soon (humidifiers/faucets) so we can sync from edomoticz

Hope it helps.
Miguel

**Comment by xTheRamon** [comment]
Thank you for this article! Will try and keep the devices up to date with the latest HomeKit additions!
