### ISSUE TITLE
How to check version and NPM

### ISSUE THREAD

**Issue by simonrb2000** [PatchworkBoy/homebridge-edomoticz#95]
Hi,

Been a while since I even look at eDomoticz, it has been working rather well. Thought I'd check for updates and looks like the Ramon has done a lot of work. How do I check what version I am currently running and are these upgrades via NPM or via git

Cheers

**Comment by xTheRamon** [comment]
Hi Simon!

Thank you! Simply run `npm outdated` or `npm -g outdated` to see all old packages.

If you want to update everything you'll have to upgrade your homebridge first. That's done using `npm install -g homebridge`.

After that, you can simply run `npm install -g homebridge-edomoticz` and your plugin will be updated.
Since there are so many changes, I recommend to remove your `~/.homebridge/persist` and `~/.homebridge/accessories` folders. Please note you'll have to re-pair your homekit with your app though.

Cheers!

**Comment by simonrb2000** [comment]
Ah ok, are all your changed pushed to the NPM version?

On 7 Aug 2017, at 16:05, xTheRamon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Simon!

Thank you! Simply run npm outdated or npm -g outdated to see all old packages.

If you want to update everything you'll have to upgrade your homebridge first. That's done using npm install -g homebridge.

After that, you can simply run npm install -g homebridge-edomoticz and your plugin will be updated.
Since there are so many changes, I recommend to remove your ~/.homebridge/persist and ~/.homebridge/accessories folders. Please note you'll have to re-pair your homekit with your app though.

Cheers!

**Comment by simonrb2000** [comment]
Thanks, I have updated and all working. Although it doesn't appear to work as good as the old version I had. You modified this a while back with the dimmers that when the switches are already on, it won't send an on command but just the dimmer value. That seems to have been removed in this version which makes Homebridge useless for all my dimmers, any ideas?

Many Thanks

Simon
On 7 Aug 2017, at 16:05, xTheRamon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Simon!

Thank you! Simply run npm outdated or npm -g outdated to see all old packages.

If you want to update everything you'll have to upgrade your homebridge first. That's done using npm install -g homebridge.

After that, you can simply run npm install -g homebridge-edomoticz and your plugin will be updated.
Since there are so many changes, I recommend to remove your ~/.homebridge/persist and ~/.homebridge/accessories folders. Please note you'll have to re-pair your homekit with your app though.

Cheers!

**Comment by xTheRamon** [comment]
Hi Simon,

You're right, I have double checked and yes, that update has been lost! I'll add that feature again and will let you know.

Erm.. that's weird. Normally `homebridge` and `homebridge-edomoticz` must both show up globally. It looks like you have another version of homebridge-edomoticz in your home folder. I guess it is safe to update that one though. But where's your homebridge? 🤷🏻‍♂️

**Comment by xTheRamon** [comment]
Simon,

I have just pushed version 2.0.9 to npm. Can you please check if your issue is resolved?

Thanks!

**Comment by simonrb2000** [comment]
I'll check once home where my homebridge is. I am experiencing really strange behaviour since updating everything. I have emptied the persist and accessories folder and started adding everything again. However it's not remembering rooms I create or modifications to devices using the official Home app. I am running the latest public iOS 10. Is there a log I can send you?

Thanks for your help.

On 8 Aug 2017, at 08:27, xTheRamon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Simon,

You're right, I have double checked and yes, that update has been lost! I'll add that feature again and will let you know.

Erm.. that's weird. Normally homebridge and homebridge-edomoticz must both show up globally. It looks like you have another version of homebridge-edomoticz in your home folder. I guess it is safe to update that one though. But where's your homebridge? 🤷🏻‍♂️

**Comment by simonrb2000** [comment]
On a side note homebridge-edomoticz does show up globally. I have updated that but when I ran the npm outdated I saw that other version of homebridge-edomoticz

On 8 Aug 2017, at 08:27, xTheRamon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Simon,

You're right, I have double checked and yes, that update has been lost! I'll add that feature again and will let you know.

Erm.. that's weird. Normally homebridge and homebridge-edomoticz must both show up globally. It looks like you have another version of homebridge-edomoticz in your home folder. I guess it is safe to update that one though. But where's your homebridge? 🤷🏻‍♂️

**Comment by simonrb2000** [comment]
> Simon,
> 
> I have just pushed version 2.0.9 to npm. Can you please check if your issue is resolved?
> 
> Thanks!

Didn't see this! That was really quick. Can confirm it is working again! Thank you so much. Its surprising how you get used to using the dimmers etc.. in Homebridge and then when you can't its hard lol. Thanks again for fixing it so quick!

**Comment by simonrb2000** [comment]
I am digressing here as the original issue was about what checking what version was NPM lol.

I have noticed that since updating, if I have HomeKit app open and something either switches on or off via domoticz, it doesn't update on HomeKit app. I have to close the app and reopen it for it to show the change. Previous version used to update within a second. Have you noticed this or is it something my end?

Cheers

**Comment by simonrb2000** [comment]
Idiot here didn't update the config file when moving from version 1.0 to 2.0. Thought I was on MQTT when I wasn't. Working now I updated the config file!

Thanks Ramon!
