### ISSUE TITLE
Door contact shown as lock

### ISSUE THREAD

**Issue by madcat-nl** [PatchworkBoy/homebridge-edomoticz#98]
Hi,

i have a few reed contacts connected to my raspberry pi which notice when a door is open or closed. Within domoticz i have it set as a "Door contact" (but i also tried it as a contact)

I have installed homebridge in combinarion with this great plugin and all the sensors are loaded from the room i have specified, but the contact sensors are seen as a lock.
it seems that IOS is receiving a Service.LockMechanism instead of a Service.ContactSensor.

How can i change this?

**Comment by xTheRamon** [comment]
I will have a look! Keep you updated.

**Comment by xTheRamon** [comment]
Hi @madcat-nl 

Could you try version 2.0.11 and see if your issue is resolved? Updating can be done through npm.

**Comment by madcat-nl** [comment]
Thanks for the quick fix, it works brilliant!

What also is great now, is that in the home app of IOS you can set if it is a contact sensor on a door, window or something else.
