### ISSUE TITLE
Thermostat type for air conditioner

### ISSUE THREAD

**Issue by marcotini** [PatchworkBoy/homebridge-edomoticz#99]
Is it possibile to use the thermostat type? Because I would like to manage the air conditioner's temperature with a Broadlink RM Mini (which should run a Bash script every time you send an IR code).

With the blinds type I have trouble to do it.

**Comment by PatchworkBoy** [comment]
You have to build a thermostat in Domoticz using 2x virtual setPoint sensors, an upper and lower temperature set point. In Domoticz use a blocky script to turn your actual aircon switch on or off dependant on whether above lower set point / below lower. The setPoint sensors will pull through to HomeKit correctly. This is as close to a thermostat as can be done as Domoticz’ thermostat type doesn’t match up to the HomeKit thermostat type’s required characteristics.
